### ISSUE TITLE
"Could not connect to the server" on all my mac

### ISSUE THREAD

**Issue by IXueGaoI** [zerotier/ZeroTierOne#1441] opened 2021-09-03 02:36 UTC
After install, just pop up this message "Could not connect to the server."
Can only retry and quit. Can’t even open the app, any help??? thx

run $ sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
result: /Library/LaunchDaemons/com.zerotier.one.plist: Could not find specified service
Unload failed: 113: Could not find specified service

run: $ sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
result: /Library/LaunchDaemons/com.zerotier.one.plist: Service is disabled
Load failed: 119: Service is disabled

![Screenshot2021-09-02 10 35 56PM](https://user-images.githubusercontent.com/17789685/131942021-1016de13-cbd1-4b3b-962c-fd187f8171b3.png)

**Comment by laduke** [comment] 2021-09-03 15:30
Sorry you're having trouble. Can you post steps to reproduce please? 
You could probably try enabling the service.

**Comment by joseph-henry** [comment] 2021-09-09 17:07
Looks like your install has been messed up somehow. I'd try reinstalling and trying again. I'm going to close this ticket since this issue is completely resolved in the upcoming `1.8` release. Thanks for reporting.

**Closed by joseph-henry** 2021-09-09 17:07 UTC

**Comment by IXueGaoI** [comment] 2021-09-09 21:16
> Looks like your install has been messed up somehow. I'd try reinstalling and trying again. I'm going to close this ticket since this issue is completely resolved in the upcoming `1.8` release. Thanks for reporting.

Thanks, reinstall didn't help, even tried to install old versions. I will wait for the new release and hope it can fix the issue.

**Comment by AbGhost-cyber** [comment] 2022-03-07 13:56
still occurring in current version
