### ISSUE TITLE
applied incorrectly when adding/removing managed ipv4

### ISSUE THREAD

**Issue by xuefer** [zerotier/ZeroTierOne#1166] opened 2020-03-21 15:50 UTC
**Describe the bug**
adding/removing managed ip for a member doesn't apply correctly

**To Reproduce**
1. in central: while member as an auto ip 192.168.123.124 by default, manually add 192.168.123.10
actual: member interface as 2 ip: 192.168.123.124, 192.168.123.10 (one added)
expected: same as result

2. in central: remove ip 192.168.123.124 by default, keep 192.168.123.10
actual: member interface has 0 ip: both ip is removed
expected: member interface has 1 ip: 192.168.123.10

3. in central: keep 192.168.123.10, add 192.168.123.101, add 192.168.123.102
actual: member interface has 2 ip: 192.168.123.101, 192.168.123.102
expected: member interface has 3 ip: 192.168.123.10, 192.168.123.101, 192.168.123.102

4. in central: keep 192.168.123.10, remove 192.168.123.101, keep 192.168.123.102
actual: member interface has 2 ip: 192.168.123.101, 192.168.123.102 (no ip removed)
expected: member interface has 2 ip: 192.168.123.10, 192.168.123.102

5. in central: keep 192.168.123.10, remove 192.168.123.102 (101 removed in step 4)
actual: member interface has 0 ip, (two removed at once)
expected: member interface has 1 ip: 192.168.123.10

**Desktop (please complete the following information):**
 - OS: Linux
 - OS/Distribution Version: Ubuntu
 - ZeroTier Version 1.4.6
 - Hardware x86_64
 
**Additional context**
- ZeroTier Network Configuration
auto assign from range 192.168.123.1~192.168.123.254

**Comment by joseph-henry** [comment] 2022-05-16 20:46
Closing since we cannot reproduce this. If you still see this issue, let us know and we can re-open this issue.

**Closed by joseph-henry** 2022-05-16 20:46 UTC
Labels: Central & Network Management, Status: Can't Reproduce, Linux
