### ISSUE TITLE
[request] Faster dead path detection and verbose logging 

### ISSUE THREAD

**Issue by zckevin** [zerotier/ZeroTierOne#877] opened 2018-11-13 07:24 UTC
ZeroTier version: 1.2.12 on Linux

I have two linux hosts H1 and H2 in the same LAN network, and a MOON cloud server S1. When I switch H1's physical connection from wired ethernet to 4G cellular, and trying to ping H2 from H1, it took **minutes** for H1's ZeroTier service to detect that the LAN connection is down and switch to using MOON server S1 as relay. 

After the LAN connection is down, ZeroTier api status was like this, the LAN path still `active`:

```
{
 "address": "490xxxxxxx",
 "latency": -1,
 "paths": [
  {
   "active": true,
   "address": "192.168.1.x/9993",
   "expired": false,
   "lastReceive": 1541994642950,
   "lastSend": 1541994642948,
   "preferred": true,
   "trustedPathId": 0
  }
 ],
 "role": "LEAF",
 "version": "1.2.12",
 "versionMajor": 1,
 "versionMinor": 2,
 "versionRev": 12
}
```

And after H1 switch to using MOON relay, ZeroTier api status was like this, there were no paths showing at all, seams like moon relay is not regarded as node's path?

```
{
 "address": "490xxxxxxx",
 "latency": -1,
 "paths": [],
 "role": "LEAF",
 "version": "1.2.12",
 "versionMajor": 1,
 "versionMinor": 2,
 "versionRev": 12
}
```

Refer to #272 , ZeroTier used to have dead path detection and fall back mechanism, which was removed in 1.1.17([referred commit](https://github.com/zerotier/ZeroTierOne/commit/e8f6b4b5d33e7b762b952d599e8cc9e730b21c03#diff-cb5203c3cda40cff9d56f2e7df3c3310)). I did not read the whole commit history so I was really curious why this got removed.

Finally, I found there's no verbose logging option in ZeroTier 1.2.12, tried `ZT_DEBUG=1`, but all I got was like `learned new path xxx to xxx`, that doesn't really help.

**Comment by adamierymenko** [comment] 2018-11-28 16:49
This is a duplicate of #210 and is done in `dev`.

**Closed by adamierymenko** 2018-11-28 16:49 UTC
