### ISSUE TITLE
By internet dropped from 700+ MBs to 10Mbs after using ZeroTier

### ISSUE THREAD

**Issue by NoshiEmperor** [zerotier/ZeroTierOne#1198] opened 2020-05-05 18:28 UTC
After I played with my friends some game, I have noticed that my internet got slower then before, I have tried to reset the network, delete all extra networks that were created by ZeroTier and still it's the same, any help?

**Comment by kompowiec** [comment] 2020-07-19 19:07
same i run ZT ping packets always drop in the vicinity 80-90%

CentOS 8

**Comment by joseph-henry** [comment] 2021-05-12 00:44
Closing due to age and inability to reproduce. If you still experience this issue please re-open.

**Closed by joseph-henry** 2021-05-12 00:44 UTC
Labels: question
