### ISSUE TITLE
Joining a network Causes internet connection drop

### ISSUE THREAD

**Issue by MRACHINI** [zerotier/ZeroTierOne#154] opened 2015-03-24 19:39 UTC
hello,

so when i connect to a network, i have internet access for about a minute or so, and then i cant access the internet anymore, its like the zerotier virtual adapter is taking priority for internet access over the actual network adapter that has the internet connection.

screenshot of network:
![2015-03-24 21-37-25 zerotier one network administration - mozilla firefox](https://cloud.githubusercontent.com/assets/1488414/6811089/1e307b1e-d26e-11e4-91a2-b1e8f8b87aa5.png)

**Comment by adamierymenko** [comment] 2015-03-24 19:40
Are you on Windows, Mac, or *nix?

**Comment by MRACHINI** [comment] 2015-03-24 19:47
Windows

**Comment by adamierymenko** [comment] 2015-03-24 19:53
Can you post 'netstat -r' output before and after this happens?

**Comment by MRACHINI** [comment] 2015-03-24 20:13
Before
![2015-03-24 21-57-12 administrator c windows system32 cmd exe](https://cloud.githubusercontent.com/assets/1488414/6811763/eced40aa-d272-11e4-8eb9-58ff1a343911.png)

After
![2015-03-24 22-08-11 administrator c windows system32 cmd exe](https://cloud.githubusercontent.com/assets/1488414/6811766/f70c1a0c-d272-11e4-90d0-07f426bcf6b2.png)

**Comment by MRACHINI** [comment] 2015-03-24 20:15
there is a new "Microsoft ISATAP Adapter #4"

**Comment by adamierymenko** [comment] 2015-03-24 20:20
ISATAP is an Ipv6 mechanism, so it's probably not related unless it's IPv6 you're having trouble with: https://en.wikipedia.org/wiki/ISATAP

This *may* be a duplicate of: https://github.com/zerotier/ZeroTierOne/issues/152

Does that sound like the same problem? If so we've had a tough time figuring this one out.

**Comment by MRACHINI** [comment] 2015-03-24 20:40
ah no the issue is IPv4 and its basically the same as #152.
Can it be solved by disabling zerotier management of IPv4 addresses ?

**Comment by adamierymenko** [comment] 2015-03-24 20:43
Unfortunately no.

The problem *may* be (unconfirmed) the 'fake route' that ZeroTier enters into the routing table. This is done so that the adapter may be categorized as per Windows firewall rules, as discussed in the other thread.

It should not be problem since the metric is so high. A metric of 10000 basically says 'do not use this route.' In our testing this appears to work fine, but for some reason it appears that Windows is somehow ignoring the route metric.

What happens if you manually delete this route with the 'route' command?

**Comment by adamierymenko** [comment] 2015-03-24 22:17
Duplicate.

**Closed by adamierymenko** 2015-03-24 22:17 UTC
