### ISSUE TITLE
OpenVPN won't connect if ZeroTier is running

### ISSUE THREAD

**Issue by sveeke** [zerotier/ZeroTierOne#368] opened 2016-07-25 09:42 UTC
Hi,

I had this problem also on Windows some time ago. The ZeroTier adapter prevented OpenVPN from working as intended so I deleted ZeroTier and thought: let's use it on my smartphone instead. Unfortunately the same problem exists on Android: if the ZeroTier service is running (which by the way isn't really transparent without a gui running in the foreground or without some notice in the notificationscreen), VPN will be unable to start.

After looking at the logfiles (with help of @fkooman) we got:
2016-07-25 11:24:38 VPN permission revoked by OS (e.g. other VPN program started), stopping VPN

Then I remembered all the issues on Windows and deleted the ZeroTier app on my phone. Since then everything works like a charm again :).

**Comment by adamierymenko** [comment] 2016-07-25 15:33
On Android there is an OS-enforced limitation of one active VPN connection at a time, period. That's not something we can do anything about. I believe the same limitation exists on iOS as well. I don't think you can connect to multiple VPNs at once on any mobile device.

Disconnecting ZeroTier should allow you to use OpenVPN though. If it doesn't we'll have to test that and figure that one out. Maybe the app is leaving something 'on' that it shouldn't be.

On Windows I believe this may be related to #308 and other Windows issues that unfortunately we still can't reproduce over here. We've tested installing OpenVPN alongside ZeroTier on Windows on 7 and 10 (x64) and have not had any problems so far.

I'm closing this but tagging #308 for further investigation.

**Closed by adamierymenko** 2016-07-25 15:33 UTC

**Comment by adamierymenko** [comment] 2016-07-25 15:45
Also tagging #357 which may be related to or identical to #308

**Comment by sveeke** [comment] 2016-07-26 08:30
Hi Adam,

Thanks for your reply. I always thought that Android kills the previously established VPN-connection when a new one is created/connected as that is the standard intended behaviour. See also the [Android reference guide on VPN](https://developer.android.com/reference/android/net/VpnService.html):

> There can be only one VPN connection running at the same time. The existing interface is deactivated when a new one is created.

And:

> Only one application can be granted at the same time. The right is revoked when another application is granted. The application losing the right will be notified via its onRevoke(). Unless it becomes prepared again, subsequent calls to other methods in this class will fail. 

Wouldn't it be better to disconnect ZeroTier if the user wants to enable another VPN? Especially on a platform like Android (which is used primarily for smartphones) I don't see a lot of benefits to be always connected to ZeroTier networks, despite the user wanting to connect to another VPN. 

Also, when a user on Android wants to enable another VPN, he will do that anyway. But now they have to first disconnect ZeroTier in order to be able to use another VPN. This is somewhat cumbersome/not user friendly. 

What do you think?

**Comment by zitanix** [comment] 2019-02-10 18:08
remove another vpn app permission 
donw! :)
