### ISSUE TITLE
"zerotier-cli listpeers -j" produces loads of duplicates

### ISSUE THREAD

**Issue by guideloom** [zerotier/ZeroTierOne#1654] opened 2022-04-26 20:41 UTC
zerotier-cli listpeers works as expected.  It lists 11 peers.

![image](https://user-images.githubusercontent.com/35501348/165381548-4ff9bbe9-bfa8-4aef-8533-fe318546fd6b.png)

Getting the json version of the same thing using "-j" (zerotier-cli listpeers -j) not so much. The output is over 2300 lines long, has 246 paths listed, and has loads of duplicates.

Excerpt from "zerotier-cli listpeers -j | jq '.[].paths[]' -c". As you can see, there are way more lines of output then what the non-json output provides and most are duplicates. Any reason why? or is this a bug?

![image](https://user-images.githubusercontent.com/35501348/165388135-fea12c83-69d9-4f3f-926c-08020ebc7d90.png)

**Comment by joseph-henry** [comment] 2022-04-26 22:07
Definitely a bug. What version is this client? Describing how you use ZeroTier might help us understand why this is happening.

**Comment by guideloom** [comment] 2022-04-27 19:20
zerotier-cli returns : ZeroTier One version 1.8.7 build 0 (platform 1 arch 4)

Just using zt like anyone else. Trying to create an SD-WAN for use among different servers. We host our own controller if that helps. That output is from the controller.

**Comment by guideloom** [comment] 2022-04-27 19:34
Just upgraded to 1.8.9.. same issue. I believe the number of peers listed in json seem to increase over time. Let me monitor for the next few days and report back.

**Comment by joseph-henry** [comment] 2022-04-28 16:20
Ok, thank you, this is very helpful. Looking into this today.

**Comment by joseph-henry** [comment] 2022-04-28 23:00
So, duplicates are sometimes ok since they only appear to be duplicates but are actually different listening sockets. This commit https://github.com/zerotier/ZeroTierOne/commit/55ec325961ef0d9b314e768d769781fa39515280 will add a `localSocket` field to the JSON output, you as long as the <ip:port:socket> triplet is different it isn't a duplicate.

**Comment by joseph-henry** [comment] 2022-04-28 23:02
Using the following:

```
zerotier-cli peers -j | jq -r '.[] |  (.address + " " + .role + " " + .paths[].address + " " + (.paths[].active|tostring))' | wc -l
```
I get ~900 lines, but when I compare it to the raw JSON output I can see there is something wrong with the `jq` usage since the raw JSON output doesn't show as many dups as the `jq` processed version. I'll dig in more later but I think this is just a problem in how we're processing the output.

**Comment by laduke** [comment] 2022-04-28 23:33
that was my bad jq query. OP is using :

`zerotier-cli listpeers -j | jq '.[].paths[]` which seems accurate

**Comment by laduke** [comment] 2022-04-29 16:27
I think what is building up is ipv6 addresses 

```
address           localSocket              path
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:5cc0:b978:ec52:7ab8/9993
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:5cc0:b978:ec52:7ab8/23020
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:e50d:df10:6d03:346d/23020
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:e50d:df10:6d03:346d/9993
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:b925:2027:4c64:47af/9993
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:b925:2027:4c64:47af/23020
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:e50d:df10:6d03:346d/23019
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:5cc0:b978:ec52:7ab8/23019
fcxxxxxxxx      140382833758112 2001:xxxx:xxxx:xxxx:b925:2027:4c64:47af/23019
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:5cc0:b978:ec52:7ab8/23019
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:5cc0:b978:ec52:7ab8/9993
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:e50d:df10:6d03:346d/9993
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:e50d:df10:6d03:346d/23019
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:e50d:df10:6d03:346d/23020
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:5cc0:b978:ec52:7ab8/23020
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:b925:2027:4c64:47af/23020
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:b925:2027:4c64:47af/23019
fcxxxxxxxx      140382878843360 2001:xxxx:xxxx:xxxx:b925:2027:4c64:47af/9993
```

**Comment by joseph-henry** [comment] 2022-04-29 16:33
> But then why do some lines have the exact same timestamps for both lastreceive and lastsend? How could so many differing listening sockets register at literally the exact same second? Confused.

If you look at the raw JSON output (before processing with `jq`) there shouldn't be too many with the exact same timestamps, a few per peer but not dozens or hundreds. This is explainable by the fact that in some cases there isn't much time between the receipt of a packet and a subsequent recording of its response. The timestamps are only down to millisecond resolution and can sometimes be both updated within a single function call or two.

**Comment by glimberg** [comment] 2022-04-29 16:38
> I think what is building up is ipv6 addresses

Hrm...I thought some code got added to not use temporary IPv6 addresses.  Wonder if it's collecting & advertising those addresses anyway

**Comment by laduke** [comment] 2022-04-29 17:55
what version are you on @guideloom

**Comment by laduke** [comment] 2022-04-29 18:02
are you seeing the same thing for peers that aren't on your LAN? Can you update both ends to 1.8.9 so we're all on the same page?

**Comment by guideloom** [comment] 2022-04-29 18:33
Yes, we are seeing this on multiple systems, even those not our our LAN. All systems are at 1.8.9.
Ex: one with 23 duplicate entries..
`{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}
{"active":true,"address":"84.17.53.155/9993","expired":false,"lastReceive":1651257090280,"lastSend":1651257145149,"preferred":false,"trustedPathId":0}`

**Comment by guideloom** [comment] 2022-04-29 18:34
Also note, for the systems also running IPv6, same issue. Some of the IPv6 addresses have duplicates.

**Comment by laduke** [comment] 2022-04-29 19:56
Thank you. This isn't happening to me. What operating systems are involved?

**Comment by guideloom** [comment] 2022-04-29 22:17
Linux and windows.

**Comment by guideloom** [comment] 2022-05-02 15:48
BTW, I don't understand  if "listpeers" returns 11 peers, why would "listpeers -j" return any number different than that? Isn't "-j" just the json version of listpeers? They should always return the identical number of items, yes?

**Comment by glimberg** [comment] 2022-05-02 15:51
It's not returning a different number of peers.  It's returning multiple paths.  Peers:Paths is a 1:many relationship as a peer can have multiple endpoints (or Paths)

**Comment by guideloom** [comment] 2022-05-02 16:03
Then shouldn't the command be "listpaths -j" ?

**Comment by glimberg** [comment] 2022-05-02 16:03
Paths are a property of a peer, so no

**Comment by joseph-henry** [comment] 2022-05-03 16:58
To further clarify grant's point, there is a discrepancy as you've pointed out but it's explained by the fact that any peer may have `N` known paths, `listpeers` only prints the path currently in use whereas `listpeers -j` shows all known paths. Perhaps if we displayed all of the known paths in `listpeers` that might be less confusing but that command dates from a time when ZT wasn't keeping track of as many paths per peer.

**Comment by guideloom** [comment] 2022-05-03 17:16
Thanks for the update. Perhaps to make outputs match, (meaning listpeers = listpeers -j), make "-j" also only show the path currently in use. Additionally, add another option for  listpeers (--all, -a) to list all known paths?

**Comment by guideloom** [comment] 2022-05-11 00:10
1) No.. not at all, at least not that I've noticed.
2) pretty quickly in comes cases. Minutes after brining up the zt interface.
3) unfortunately, not that I've noticed. I've seen as high as over 60 actual duplicates of a single entry (vs the total output of 250+ paths)

**Comment by guideloom** [comment] 2022-06-01 21:57
Standing by to help when I can...

**Comment by guideloom** [comment] 2022-08-17 20:16
Still standing by to help when I can.

**Comment by guideloom** [comment] 2022-08-24 18:12
Others who have experienced this issue in ztncui reverted back to version 1.6.5 of zerotier. That version does not display any duplicated. (see this thread for info : https://github.com/key-networks/ztncui/issues/91#issuecomment-1214484022

**Comment by MANKUD** [comment] 2022-12-13 09:12
any updates on a fix for the above issue? 😢

**Comment by laduke** [comment] 2022-12-13 16:58
Need steps to reproduce

**Comment by laduke** [comment] 2023-02-06 18:21
#1870

**Comment by mamoniot** [comment] 2023-02-15 15:54
The cause of this bug has been discovered and fixed in pull request https://github.com/zerotier/ZeroTierOne/pull/1870. It would happen whenever a path expires; a duplicate of a non-expired path would be generated to overwrite the expired path. The fix will go live soon. I am closing this issue unless it appears again.

**Closed by mamoniot** 2023-02-15 15:54 UTC
Labels: Type: Bug, Status: Can't Reproduce

**Comment by guideloom** [comment] 2023-02-19 21:00
Looking forward to testing!
