### ISSUE TITLE
ZT 1.2.4 orbit failed.

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#507] opened 2017-05-15 00:47 UTC
ZT version: 1.2.4

```
# cp root/0000001c52a83ddf.moon root/moons.d/
# ./zerotier-cli -Droot status
200 info 1c52a83ddf 1.2.4 ONLINE
# ./zerotier-cli -Droot listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 8841408a2e 45.32.248.87/9993;6421;1237;1.00 203 1.1.5 PLANET
200 listpeers 9d219039f3 128.199.197.217/9993;6229;1066;1.00 248 1.1.5 PLANET
# ./zerotier-cli -Droot orbit 1c52a83ddf 1c52a83ddf
200 orbit OK
# ./zerotier-cli -Droot listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 8841408a2e 45.32.248.87/9993;3126;3025;1.00 209 1.1.5 PLANET
200 listpeers 9d219039f3 128.199.197.217/9993;13137;7837;1.00 290 1.1.5 PLANET
# ls -alF root/moons.d/
total 12
drwxr-xr-x 2 root root 4096 May 15 08:43 ./
drwxr-xr-x 5 root root 4096 May 15 08:43 ../
-rw-r--r-- 1 root root  259 May 15 08:43 0000001c52a83ddf.moon
```

**Comment by sbilly** [comment] 2017-05-15 01:30
After  `rm -rf root/moons.d/*` and restart ZT

```
# ./zerotier-cli -Droot orbit 1c52a83ddf 1c52a83ddf
200 orbit OK
# ./zerotier-cli -Droot listmoons
[]
# ./zerotier-cli -Droot listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 1c52a83ddf - 0 - LEAF
200 listpeers 8841408a2e 45.32.248.87/9993;7131;2063;1.00 195 1.1.5 PLANET
200 listpeers 9d219039f3 128.199.197.217/9993;1952;1952;1.00 284 1.1.5 PLANET
```

**Comment by Jamesits** [comment] 2017-10-12 08:47
I can reproduce the same issue on zerotier-one 1.2.4 (Windows/macOS/Linux). If you add more than 4 server entries to one moon, the client will refuse to add this moon (but always return success). Using 4 or fewer servers worked for me for now.

**Comment by adamierymenko** [comment] 2017-11-29 15:56
Closing this issue since it's fixed in `dev` and since this whole thing is getting an overhaul in the next-next version.

**Closed by adamierymenko** 2017-11-29 15:56 UTC
