### ISSUE TITLE
1.8.3 regression issue for Raspberry Pi

### ISSUE THREAD

**Issue by harishpillay** [zerotier/ZeroTierOne#1500] opened 2021-11-20 03:25 UTC
I have a two Raspberry Pis running zerotier-one successfully, provisioned when it was version 1.8.1. They have been updated to 1.8.3 and work fine.

I just added two more RPis and did the installation and both show this:
```
Preparing to unpack .../zerotier-one_1.8.3_armhf.deb ...
Unpacking zerotier-one (1.8.3) ...
Setting up zerotier-one (1.8.3) ...
Processing triggers for man-db (2.9.4-2) ...

*** Enabling and starting ZeroTier service...
Synchronizing state of zerotier-one.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable zerotier-one

*** Waiting for identity generation...
```

and keeps waiting. I can terminate it, remove the packages, reinstall it and hit the same wait state.

If I ran (after stopping the wait):
```
sudo zerotier-cli join <MYNETWORK>
```
it returns
```
Illegal instruction
```
for obvious reasons because the identity was not generated (I think).

Seems to be a regression.

**Comment by 07pepa** [comment] 2021-11-20 13:56
having same issue on raspberry pi zero http://download.zerotier.com/debian/bullseye bullseye InRelease and maybe caused by buster

**Comment by dbz2k** [comment] 2021-11-21 20:20
having the same problem using Raspberry Pi Zero W Rev 1.1, and using Raspbian GNU/Linux 11 (bullseye) armv

**Comment by laduke** [comment] 2021-11-21 23:24
Please post what model pi you're seeing this on, if you haven't.

**Comment by 07pepa** [comment] 2021-11-27 10:17
zero w  bullseye

**Comment by michalpirchala** [comment] 2021-11-29 09:20
Same problem here on pi zero. I tried to run zerotier-one binary:
```
# zerotier-one
Illegal instruction
```
So I compiled zerotier from source using `make` and then replaced pre-compiled binary with the new one:
`cp zerotier-one /usr/sbin/zerotier-one`

Now it works.

**Comment by hoppke** [comment] 2021-11-29 12:49
I hit that same issue on my pi zero, "Illegal instruction" error. Last working build is 1.8.1.
Perhaps the effective compiler flags for armhf changed between 1.8.1 & 1.8.2 ?

HW details:
❯ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 997.08
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 900093
Serial          : 00000000f42846e0
Model           : Raspberry Pi Zero Rev 1.3

**Comment by laduke** [comment] 2021-12-08 00:57
check 1.8.4!

**Comment by hoppke** [comment] 2021-12-09 10:03
1.8.4 works (tested on Pi Zero rev 1.3)
Thanks!

**Comment by 07pepa** [comment] 2021-12-09 16:38
1.8.4 works 

thanks  please close this

**Comment by laduke** [comment] 2021-12-10 17:59
Thanks!

**Comment by harishpillay** [comment] 2021-12-20 11:25
it was fixed. thanks.

**Closed** 2021-12-20 11:24 UTC
