### ISSUE TITLE
zerotier 1.4.2 not runing in openvz

### ISSUE THREAD

**Issue by mbcc2006** [zerotier/ZeroTierOne#1006] opened 2019-08-13 02:55 UTC
![image](https://user-images.githubusercontent.com/1826057/62911877-82f16100-bdb8-11e9-8783-b8cb298cb8bd.png)
![image](https://user-images.githubusercontent.com/1826057/62911901-913f7d00-bdb8-11e9-803c-afba1a807043.png)
I am a tiro in linux ,but i upgrade zerotier ,all openvz server zerotier is killed ,i try restart service or restart server or reinstall zerotier it's not work.

**Comment by mbcc2006** [comment] 2019-08-13 03:24
I try create new openvz vps ，but not work 
![image](https://user-images.githubusercontent.com/1826057/62912962-c8179200-bdbc-11e9-8141-c77c45b7e5cd.png)
![image](https://user-images.githubusercontent.com/1826057/62912997-e8dfe780-bdbc-11e9-852f-fe71db19ff24.png)

**Comment by adamierymenko** [comment] 2019-08-13 16:31
Dupe of #1007

**Closed by adamierymenko** 2019-08-13 16:31 UTC
