### ISSUE TITLE
Add diagnostics tab/dialog to UI with diagnostic information and in-depth network info (e.g. peers)

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#251] opened 2015-11-20 03:39 UTC
The peers tab is essential for troubleshooting, and has come useful for me a few times in the past, (especially related to IPv6 dual-stack or transition networks). I feel that it should be hidden instead of completely removed. This would help when asking remote-located users to send a screenshot of the peers tab. End-users would cry if the command-line was needed for something that used to be a simple email.

Maybe a keyboard modifier plus keystroke would unhide the tab. Another way would be to enter a special word into the network-id input box.

```
Both UIs no longer have the "Peers" tab, since several users reported that non-
   technical users found this confusing and even alarming (does this mean people
   can access my system?). This information is visibile with "listpeers" from the
   command line (zerotier-cli).
```

**Comment by adamierymenko** [comment] 2015-11-22 20:06
Yes, the problem is that non-technical users apparently mis-interpret this as 'people are logged into my machine!'

We'd like to create a *diagnostics* tab or dialog, and the information could be presented there in a more comprehensible and better designed form. Will re-title this appropriate.

**Comment by adamierymenko** [comment] 2016-09-08 00:14
Closing since #377 will be closer to the approach we will take, as well as circuit testing from the controller.

**Closed by adamierymenko** 2016-09-08 00:14 UTC
Labels: backlog, usability
