### ISSUE TITLE
Central UI: warn about bad net masks on member IP assignments and offer to renumber.

### ISSUE THREAD

**Issue by oneguynick** [zerotier/ZeroTierOne#351] opened 2016-07-07 13:06 UTC
**Use Case**
The client installs, but on CentOS/RHEL 6.7/6.8 following the connection coming online, a route is not added. After the install, network coming online, and a managed IP address being assigned I can then issue an `ip route add xxx.xxx.xxx.xxx/24 dev zt0` and have access.

**Environment**

- RHEL 6.8
- Tried with firewall enabled/disabled
- Static IP address assigned via /etc/sysconfig/network-scripts/ifcfg-eth0
- network manager and GUI not in use

**Comment by adamierymenko** [comment] 2016-07-07 16:11
Going to give this a try... probably something with libraries or /sbin/ip. We'll update the package if needed.

**Comment by adamierymenko** [comment] 2016-07-07 16:12
Oh this is RHEL -- again we do not have an image. :frowning:

I've worked in a RHEL environment before and it's indeed a strange beast with occasional compatibility issues vs. CentOS. Will need to find some way to test with RHEL. Maybe Amazon has AMIs.

**Comment by jdrews** [comment] 2016-07-07 18:04
@adamierymenko Something worth looking at. RHEL gives out free developer subscriptions now. I know it's not part of any docker farm but it's better than nothing. 

http://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available/

**Comment by oneguynick** [comment] 2016-07-07 18:05
I am more than happy to test any branches or tests. You can download the basic RHEL images for free and test against them as @jdrews also pointed out. Does this work against CentOS 6?

**Comment by adamierymenko** [comment] 2016-07-07 18:40
I just tested on an Amazon RHEL 6 AMI and it worked, but all I did was join our test network (8056c2e21c000001) and ping earth.zerotier.net.

What kind of routes are you trying to add? Did you configure them through the new UI?

If that's the case I think we may have a documentation problem not a bug.

**Comment by oneguynick** [comment] 2016-07-07 18:51
I have the zerotier network I join with a managed zerotier IP range of 192.168.192.0/24. The route is specified at the top of the UI. I am just adding a route that puts zerotier traffic through zt0 and network traffic through the eth0.

**Comment by adamierymenko** [comment] 2016-07-07 19:18
Can you take a screenshot of the routes or give me the network ID so I can take a look? (if it's on my.zerotier.com and not your own)

**Comment by oneguynick** [comment] 2016-07-07 19:58
Sent you an email with the information.

**Comment by adamierymenko** [comment] 2016-07-07 20:01
I see nothing wrong. Is an IP being assigned? When an IP is assigned, the route is actually added automatically by the kernel so ZT doesn't even have to do anything in that case... or shouldn't.

What does `ip addr list` show for the interface after joining?

So far I can't duplicate any problem on a RHEL 6.8 box on AWS.

**Comment by oneguynick** [comment] 2016-07-07 20:14
Are you assigning the eth0 a static IP address and disabling network-manager? Most server installs do not use network-manager.

Here is the flow from start to finish:

[root@notimportant ~]# ip addr list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:0b:22:65 brd ff:ff:ff:ff:ff:ff
    inet 10.1.3.70/16 brd 10.1.255.255 scope global eth0
[root@notimportant ~]# service zerotier-one start
Starting zerotier-one:                                     [  OK  ]
[root@notimportant ~]# ip addr list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:0b:22:65 brd ff:ff:ff:ff:ff:ff
    inet 10.1.3.70/16 brd 10.1.255.255 scope global eth0
4: zt0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc pfifo_fast state UNKNOWN qlen 500
    link/ether 3e:d6:52:be:8c:ee brd ff:ff:ff:ff:ff:ff
    inet 192.168.192.70/32 brd 255.255.255.255 scope global zt0
[root@notimportant ~]# ip route show
169.254.0.0/16 dev eth0  scope link  metric 1002 
10.1.0.0/16 dev eth0  proto kernel  scope link  src 10.1.3.70 
default via 10.1.1.1 dev eth0 
[root@notimportant ~]#

**Comment by adamierymenko** [comment] 2016-07-07 20:18
I see it. Go to whatever member this is and delete its IP assignment and re-add it with /24 instead of /32. Setting /32 assigns the IP with a netmask of 255.255.255.255 which implies no route anywhere else.

**Comment by adamierymenko** [comment] 2016-07-07 20:18
I think this is a Central UI problem -- it should warn about and offer to correct bad net masks.

**Comment by adamierymenko** [comment] 2016-07-07 20:21
Ahh... and I understand the rest of the problem. ZT does not bother setting routes that overlap with assigned IPs because it assumes (correctly if the netmask is correct) that this is redundant.

So yeah... UI issue.

**Comment by oneguynick** [comment] 2016-07-07 20:26
Moved them from /32 to /24. It is odd that the UI automatically selects /24 for some of them and /32 for others. I didn't even think to look at the mask because of the inconsistent nature. Thanks for the quick replies and action on this. I agree with your assessment on it being a UI issue.

**Comment by oneguynick** [comment] 2016-07-07 20:26
Do you want to leave this open for the UI issue?

**Comment by adamierymenko** [comment] 2016-07-07 20:28
Yeah, planning to do more UI work soon so I will leave it open for now as a reminder.

Eventually we need to do Central bug tracking somewhere else because that's technically another project. (It's the only closed source thing we have. It's our "enterprise" control panel :)

**Comment by adamierymenko** [comment] 2016-07-07 23:37
Instead of doing that, I'm just going to take the netmask for assigned IPs from the corresponding LAN-local route that they belong to -- e.g. IPs in 10.0.0.0/24 would have /24.

There is absolutely no point to having assigned IPs have their own per-IP netmasks. I can't think of any conceivable use for it and it's just a source of bad UX. Closing since this is done in -dev and Central -dev.

**Closed by adamierymenko** 2016-07-07 23:37 UTC
Labels: compatibility

**Comment by oneguynick** [comment] 2016-07-08 00:06
Agreed. Should be an option, but not the default 

---
Nicholas Schmidt
P: +1.661.724.6438
E: oneguynick@gmail.com
