### ISSUE TITLE
connection drops during bandwidth bursts

### ISSUE THREAD

**Issue by kylemcdonald** [zerotier/ZeroTierOne#593] opened 2017-09-27 04:28 UTC
I've been noticing some really weird behavior with zerotier recently, I think this is new over the last few days. I don't know a lot about networking so I'm just going to do my best to describe the failure case I can reliably reproduce.

1. I'm on a wireless network with my Mac.
2. `ssh 10.241.230.97` to connect to an Ubuntu 16.04 machine on my zt2 interface.
3. `ps aux` on the remote machine. After 9 lines of results, the connection hangs and never recovers.
4. Close the terminal, create a new one, ssh in again.
5. `sudo /sbin/ifconfig zt0 mtu 1394 ; ps aux` and it works. It also works if I set my local mtu to 1394 with `sudo ifconfig zt2 mtu 1394`.

I can get the mtu up to 1394, at 1395 it hangs.

Default mtu seems to be 2800, both on the Ubuntu machine and on my Mac.

This isn't restricted to ssh, I started a web server and tried curling an image (at mtu 2880):

```
> curl -o image.png "http://10.241.230.97:8888/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0^C
```

It stalls indefinitely.

Interestingly, if I set either mtu to 1395, it downloads part of the image but then hangs, with "Current Speed" dropping to 0, and total bytes staying at 5922:

```
> curl -o image.png "http://10.241.230.97:8888/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 16  5922   16   983    0     0    188      0  0:00:31  0:00:05  0:00:26     0
```

I'm not sure what to do next. If the answer is "just set your mtu to 1394" that's ok with me :) But I'm pretty sure I wasn't having this problem until recently, and I'm not sure what changed...

Edit/update: one more datapoint I noticed, when the mtu is 2800 on both ends, I can `ping -s 1500 10.241.230.97` with no problems, all the way up to 2799.

**Comment by adamierymenko** [comment] 2017-10-16 19:37
What's the MTU of the underlying interface? Are you on something like PPPoE that really limits MTU?

**Comment by prutschman** [comment] 2017-10-18 20:27
I'm seeing this as well. Specifically, problems that look an awful lot like broken path MTU discovery, though that doesn't make a whole lot of sense since I'm directly connecting to a peer node when this happens. I've been setting the mtu to 1400 to try to work around it. What's also strange is that it seems to be affecting TCP but not ICMP. I don't have a trace handy, but in the past wireshark shows one side trying to send a packet bigger than the underlying physical interface supports, but it never sees an ICMP "too big" reply so the connection stalls. Obviously at least some aspects of ZT fragmenting packets over the smaller interface must be working, since the large pings work.

Naturally this doesn't occur predictably. I'll try to get captures of both sides the next time I see it happen.

**Comment by dafyre** [comment] 2017-10-20 13:15
I checked this on my Windows 10 (1709) system.  I usually keep remote desktop up to my laptop at home.  It's connected via WiFi.  My connection will drop several times a day, and sometimes even several times an hour -- in the middle of me using it.

I edited the interface and dropped the MTU down to 1394 as Kyle did, and for 2 days, my connection has been much more solid.

**Comment by kylemcdonald** [comment] 2017-10-20 17:37
@adamierymenko I'm not familiar with PPPoE but I just looked it up and neither my connection nor the remote connection are over DSL. If there's some other way that PPPoE might be used or influencing this setup I can try to check that.

Also: I've switched back to 2800 on both ends some time since the original post (probably from a restart), and this problem hasn't reoccured for me recently.

**Comment by adamierymenko** [comment] 2017-11-17 22:07
Marking as likely duplicate of #619

**Comment by hiway** [comment] 2017-11-25 00:39
Found this issue while searching for the issue I'm having with ZeroTier One on MacOS Sierra - default MTU is 2800 and I am able to ping machines, however if I try to transfer a large file the connection 'hangs'. Setting the MTU on zt0 to 1280 fixes the issue.

Also, this does not look like a diplicate of #619 since I do not have a dual-homed device, although I am on an ADSL line which gives ~8 Mbps over copper wire. 

Could this issue be investigated further? I am a new user and am absolutely loving ZeroTier, however this issue and manually setting MTU every time network reconnects is holding me back from having a network that just works.

**Comment by prutschman** [comment] 2019-01-10 20:36
I've also seen connection hangs that seem to go away when setting the MTU smaller. The odd thing is that it seems to affect TCP but not ICMP; when the bad behavior is happening I can send a large ping.

For testing TCP, I generally try something like:
`ssh host "dd if=/dev/zero count=1 bs=16"` for a small packet (this usually works)
`ssh host "dd if =/dev/zero count=1 bs=1024"` to stimulate larger TCP packets (this fails)

Looking at packet traces, the source side is sending a 2800-byte TCP segment. The destination never receives it. During this same time period, a similarly large ICMP packet will go through. The source will continue attempting to re-send that large segment, and it will continue to fail.

It seems to resolve spontaneously after a while.

**Comment by jusplainmike** [comment] 2019-03-24 15:59
Any update on this? Also do I only need to shrink the MTU on my windows client? My other clients Linux to Linux don't have this issue when using ps and top. My MTU is down to 1200 and still having the issue.

**Comment by kylemcdonald** [comment] 2019-06-03 21:50
I'm staying at a hotel where I've previously had this issue, and it is still present.

Running `ps aux` drops the connection after 9-12 lines of output. Running `sudo /sbin/ifconfig ztnfan5bng mtu 1394 ; ps aux` works fine. The server is a Google Cloud Compute Engine. Connecting to a different machine with a larger MTU of 2800 works fine. So there are just some rare cases where these bursts cause a problem.

**Closed** 2019-06-11 19:25 UTC

**Comment by mrvanes** [comment] 2019-06-12 09:37
Closed without fix?

**Comment by kylemcdonald** [comment] 2019-07-09 01:22
updated to Ubuntu 18.04 on a machine that previously worked, and seeing this again. `sudo ip link set ztnfan5bng mtu 1394` fixed it (for now?)

not sure why this is closed.

**Comment by kosli** [comment] 2024-12-03 22:51
i am seeing still this issue... anybody else too?
