### ISSUE TITLE
Big Windows adapter issues thread!

### ISSUE THREAD

**Issue by schumann2k** [zerotier/ZeroTierOne#152] opened 2015-02-27 04:36 UTC
Hi there, I keep having weird connectivity issues while running zerotier on Windows.
Sometimes websites wouldn't load or connections would be dropped at random (especially noticeable with instant messengers). Other times copying files in my local LAN would slow to a crawling 10mbit/s, the same bitrate as the zerotier adapter, while everything is connected with gigabit ethernet and I usually max out at ~800mbit/s.

As far as I can tell, those anomalies happen because the ZeroTier adapter has a default gateway set: *25.255.255.254*
If I stop the ZeroTier service my problems go away and if I restart the service the problems will reoccur after a seemingly random length of time, could be anytime from a few minutes to a few days.
My ZeroTier network runs on 10.251.251.0/24 and I'm not sure what the point of the gateway on a completely different and unreachable subnet is.

My ZeroTier network configuration is as follows:
* Access Control: [x] Private Network 
* Frame Types Allowed: [x] IPv4 
* Have ZeroTier Assign IPv4 Addresses: 10.251.251.0/24
* Multicast Limit: 32
* Broadcast: [x] Enable Wildcard MAC

My next step would be to see if I can host my own DHCP server to serve IP's to my ZeroTier network, without a gateway set.
These problems have been around for as long as I can remember but I dismissed them as harmless bugs, at this point I've grown rather dependent on ZeroTier VPN and the connectivity issues are becoming major annoyances.

Based on my observations running version 1.0.1.

**Comment by adamierymenko** [comment] 2015-03-02 18:00
This is a very odd issue.

ZeroTier does add a default gateway, but I doubt it's the problem. It's given a very, very low metric, meaning it would not be used unless there is no other default route or the default route's metric was set abnormally low. Can you show your routing table and see what the metrics are?

The reason ZeroTier adds a default gateway is to hack around a piece of Windows networking brain damage. Windows uses the MAC address of the default gateway on an interface to classify that interface in its own internal databases. Without a default gateway of some kind, you will not get a popup asking you to classify the network as 'public' or 'private,' etc., and firewall rules will not be applied to it. While this is unbelievably stupid, it's not something we have any control over... so we hacked around it.

ZeroTier networks normally don't have default gateways -- they're normally used to connect multiple hosts in a peer-to-peer fashion.

It is possible to use DHCP with ZeroTier, but it's a bit difficult right now. We have plans to make this easier in future releases.

**Comment by schumann2k** [comment] 2015-03-03 03:15
Interesting, thank you for the clarification.
Here are my routes as of now: https://gist.github.com/schumann2k/574a4af28c1d3dfbcb91
I'll make another dump the next time the issue occurs.

**Comment by schumann2k** [comment] 2015-03-03 04:05
It just happened again, here's the diff for my routes: https://gist.github.com/schumann2k/574a4af28c1d3dfbcb91/revisions
The "new" routes look just like the old ones, nothing really changed except for the order - the ZT adapter is in first place now.
I also made a wireshark capture which shows that windows is using the 10.251.251.184 IP to try and connect the internet.
Only IPv6 connections continued to function while this was going on and once I stopped the ZeroTier service the problems went away.

I don't know what else I can provide to make debugging easier, let me know if I can do anything to help. :)

**Comment by adamierymenko** [comment] 2015-03-03 19:57
This is very strange. I looked at your gist and I don't see an issue -- note that higher metrics are lower. The 25.255.255.254 route should have the lowest priority there.

What happens if you tracert (Windows traceroute) to a known-good IP on the Internet? I think the -n option will do it without trying to do DNS lookups.

**Comment by adamierymenko** [comment] 2015-03-03 19:59
It would also be possible if you have WinDump (Windows tcpdump) installed to dump the ZeroTier interface while attempting to ping something on the Internet. If Windows is attempting to use the ZeroTier faux-route, you would see the packets on that interface. Otherwise you would see them on the real physical interface.

I just attempted and I cannot duplicate anything like this issue here, nor have I received any reports like this. Not saying it's not happening -- just that something odd is definitely occurring here.

**Comment by Arffeh** [comment] 2015-03-03 22:09
For the sake of asserting, my Windows 7 machine sometimes does this as 
well. The moment I drop the ZT1 interface, connectivity is restored on 
the main interface.
Thumbs up for Windows being stupid.

**Comment by adamierymenko** [comment] 2015-03-03 23:38
According to everything I can find, Windows *should* honor the metric and choose the gateway with the lowest metric value. I have no idea what's happening here.

**Comment by schumann2k** [comment] 2015-03-04 05:03
https://www.dropbox.com/s/ir9hbnykqltyn0t/zt_ping.pcapng?dl=0 
```
1	0.000000000	10.251.251.184	8.8.8.8	ICMP	74	Echo (ping) request  id=0x0001, seq=61/15616, ttl=128 (no response found!)
2	4.669235000	10.251.251.184	8.8.8.8	ICMP	74	Echo (ping) request  id=0x0001, seq=62/15872, ttl=128 (no response found!)
3	9.667746000	10.251.251.184	8.8.8.8	ICMP	74	Echo (ping) request  id=0x0001, seq=63/16128, ttl=128 (no response found!)
4	14.66929600	10.251.251.184	8.8.8.8	ICMP	74	Echo (ping) request  id=0x0001, seq=64/16384, ttl=128 (no response found!)
```
Not much to see there, I'll try to reproduce it in a VM.

**Comment by maci0** [comment] 2015-03-04 13:20
is your windows all updated ?

**Comment by schumann2k** [comment] 2015-03-04 14:12
Yes, I'm on Windows 8.1 with no updates left to install on Windows Update.

**Comment by adamierymenko** [comment] 2015-03-24 20:43
Issue #154 may be a duplicate.

**Comment by MRACHINI** [comment] 2015-03-24 20:53
nothing changed, i always have to reboot so i can get internet back.
![2015-03-24 22-49-30 administrator c windows system32 cmd exe](https://cloud.githubusercontent.com/assets/1488414/6812584/87dbba9c-d278-11e4-852a-d4833b5d27fa.png)

**Comment by schumann2k** [comment] 2015-03-24 21:00
I haven't had any more connectivity issues on my desktop this whole time, it happen once or twice on my laptop though. Same deal, metric is as it should be, ping's wont get through.. very unpredicable! :/

**Comment by adamierymenko** [comment] 2015-03-24 21:00
Very very strange -- so far we are completely unable to reproduce it in VMs.

**Comment by MRACHINI** [comment] 2015-03-24 21:02
mmm come to think about it, i think my desktop doesn't have this issue, only my laptops and friend's laptops, I'll check and update.

**Comment by adamierymenko** [comment] 2015-03-24 21:02
Do any of you per chance have any of the following installed?

 * Third party firewall or network filter/monitoring software
 * Third party remote network admin software
 * Other network virtualization, VPN, SDN, or similar products (e.g. OpenVPN, Tunngle, Hamachi, Cisco)
 * Any 'weird' network drivers like legacy Novell/IPX, etc.

Finally, what exact version of Windows is this? @MRACHINI are you on Win8 too?

**Comment by MRACHINI** [comment] 2015-03-24 21:15
I have:
Laptop, windows 7, netlimiter, openVPN uninstalled, Proxycap, proxifier.
Laptop, windows 7, netlimiter, proxifier.
Laptop, windows 7, netlimiter.
Laptop, windows 8, netlimiter.
Desktop windows 7, netlimiter, proxifier.

**Comment by MRACHINI** [comment] 2015-03-24 22:09
so i just checked and my desktop is NOT having this issue, also another Windows 7 Desktop and 2 other windows VPSs are not having this issue!

**Comment by adamierymenko** [comment] 2015-03-24 22:12
So only the laptops? *All* the laptops?

Could it be somehow related to WiFi vs. physical wired connectivity? Don't know how, but it seems like the only potential difference.

**Comment by MRACHINI** [comment] 2015-03-24 22:15
i think devices with more than one adapter have this issue, or maybe wifi vs physical, but this is not logical!

**Comment by adamierymenko** [comment] 2015-03-24 22:17
No, it makes no sense but neither does anything else in Windows networking. I am not exaggerating. It's utterly insane in so many ways.

Try disabling the adapter that is not in use if it's enabled but 'unplugged.'

**Comment by Arffeh** [comment] 2015-03-24 22:58
Do the laptops have any extra network management features? Eg Intel Network
Manager, ASUS Networking, etc.

Any fleet of laptops I prep, I specifically get rid of them, as I've
experienced some insanely erratic behaviour from them in the past.

Some interfere so badly that I simply don't allow them anymore. :)

**Comment by Arffeh** [comment] 2015-03-24 22:59
I totally composed this to the wrong ticket. :)

**Comment by MRACHINI** [comment] 2015-03-24 23:29
disabled all adapters not is use, and still same issue.

**Comment by adamierymenko** [comment] 2015-03-24 23:30
This is really, really bizarre. Did you see @Arffeh 's comment above?

**Comment by schumann2k** [comment] 2015-03-25 06:32
My desktop and laptop both run Windows Firewall, SysInternals/MS Process Explorer, GlassWire and VMware. Disabling the VMware virtual network adapters seems to have no effect.

**Comment by MRACHINI** [comment] 2015-03-25 23:20
Update
all my desktops are still working with no issues, only had the issue one time when i unplugged my router and internet dropped, after plugging back the router i had to reboot to get internet connection back.

**Comment by adamierymenko** [comment] 2015-03-25 23:21
A bit of 'meta' on this:

Windows is probably the weakest currently supported platform. We're planning a whole lot of Windows testing and some changes to the Windows implementation in the near future to try to address a whole set of reported Windows issues.

**Comment by schumann2k** [comment] 2015-03-26 09:32
I think its related to loosing internet connection.
My ISP forces everyone to disconnect once every 24 hours and assigns a new random IP (and IPv6 prefix) from their pool and I tried reconnecting manually a couple of times but the glitch didn't happen. The daily forced disconnect used to happen while I was working and I moved it to the middle of the night a few weeks ago, maybe that's why I haven't had any more problems.

I regularly put my laptop to sleep rather than shut it down (most of the time at least), that may have a similar effect as loosing connectivity (goes to sleep, wakes up, ZT adapter still active from before but no WiFi, wifi reconnects but isn't the default route anymore).

**Comment by adamierymenko** [comment] 2015-03-26 23:57
@schumann2k : those issues are getting attention in 1.0.3 -- we're moving away from trying to manually detect network 'fingerprint' changes and will just rely on empirical methods to determine network config. It should also pick up on external IP changes when no internal IP has changed, which the current version has trouble with.

**Comment by adamierymenko** [comment] 2015-05-25 18:49
Wanted to reference issue #107 which I am now closing, since NDIS6 is in on -dev. Will see with 1.0.3 beta release whether this addresses all our reported Windows issues or not.

**Comment by adamierymenko** [comment] 2015-06-04 02:38
Those who have been having these issues -- please try 1.0.3:

http://download.zerotier.com/dist/ZeroTier%20One.msi

This version contains an NDIS6 driver for the Ethernet tap. To use this driver, you'll have to *uninstall* your old version and install the new one. If you install it overtop of 1.0.1, it'll continue using the NDIS5 driver.

**Comment by adamierymenko** [comment] 2015-06-04 23:06
Going to close this for now since we have NDIS6 -- we'll add issues for any Windows issues that come up from here on out.

**Comment by heri16** [comment] 2015-06-29 10:54
How can we verify that we have the NDIS6 driver?

**Comment by adamierymenko** [comment] 2015-06-29 16:39
If you uninstalled and reinstalled 1.0.3, you have NDIS6. Otherwise it keeps using your existing NDIS5 driver.

Note that 1.0.3 has a known issue: when you join new networks, existing networks can go into a 'coma'. This is fixed in -dev so it'll be fixed in 1.0.4. We're still working on one more issue though: if you sleep/wake your machine, sometimes networks go into a coma. It only manifests on real hardware, so I won't be able to fix until I can use a real Windows machine. Might go over to a friend's house tonight to debug with his Windows desktop. :)

**Comment by adamierymenko** [comment] 2015-06-29 16:41
![screen shot 2015-06-29 at 9 40 58 am](https://cloud.githubusercontent.com/assets/591635/8413109/ff08728e-1e42-11e5-8e99-46ea545ee3f6.png)

**Comment by adamierymenko** [comment] 2015-06-29 16:41
If it says 'zttap300' it's NDIS6. zttap200 is NDIS5.

Reopening this thread and retitling 'Windows driver issues' since there is still one outstanding (sleep/wake).

**Comment by adamierymenko** [comment] 2015-07-31 19:18
I you've had Windows adapter or sleep/wake issues, try 1.0.4:

https://www.zerotier.com/blog/?p=468

**Comment by adamierymenko** [comment] 2015-08-03 15:49
Closing for now, will re-open if more issues arise.

**Closed by adamierymenko** 2015-08-03 15:49 UTC
Labels: bug, compatibility

**Comment by keesbos** [comment] 2015-11-17 13:25
Just encountered the (or a similar) problem today. Or, at least it looks similar. That's why I drop a note here. This particular problem appears to be a dns lookup issue.

As soon as zt-interface comes up, lookups on the name server fail (which looks like everything is unreachable).

It truned out that the nameservers assigned (dhcp) to the primary interface where in the same network as the zerotier interface. The connectivity was all right (pinging the name servers succeeded), but lookups failed. The zt interface had a ip address assigned by zt. Adding the nameserver ipaddresses to the zt-interface ip4v properties (had to enable dhcp too) solved the issue. Apparently windows binds the dns queries to the interface that has the name servers assigned. Thus (I guess) the ping goes out via the zt-interface and the dns query via the primary interface and therefore fails miserably.

**Comment by neinWur5** [comment] 2015-12-18 10:57
I can confirm this still happens.
Laptop, Avast! AV.
Connection lost. Regained connection after doing:

    route delete 0.0.0.0 mask 0.0.0.0 if 11

being IF 11 ZeroTier One Virtual Port, zttap300.sys.

**Comment by pglizniewicz** [comment] 2016-05-25 12:10
This is the same thing that happens with Hamachi. And the solution [pedro7](https://github.com/zerotier/ZeroTierOne/issues/152#issuecomment-165748355) mentioned is the one I've used with it. While it never happened on a PC with a stable Ethernet connection, it often happened on a laptop where I've used a GSM connection on demand. Changing the metrics didn't make any difference - Windows is stubborn and for some reason will choose the connection with higher metrics. [This](https://github.com/zerotier/ZeroTierOne/issues/327) might be the same problem.

**Comment by donald-tt** [comment] 2017-08-24 22:47
I think I saw something like this last week, when using my laptop with the wifi hotspot on a bus.  Windows 10, with the ZeroTier (1.2.4) interfaces up my web browsers couldn't make DNS requests.

**Comment by sampoon** [comment] 2019-09-01 10:12
> Hi there, I keep having weird connectivity issues while running zerotier on Windows.
> Sometimes websites wouldn't load or connections would be dropped at random (especially noticeable with instant messengers). Other times copying files in my local LAN would slow to a crawling 10mbit/s, the same bitrate as the zerotier adapter, while everything is connected with gigabit ethernet and I usually max out at ~800mbit/s.
> 
> As far as I can tell, those anomalies happen because the ZeroTier adapter has a default gateway set: _25.255.255.254_
> If I stop the ZeroTier service my problems go away and if I restart the service the problems will reoccur after a seemingly random length of time, could be anytime from a few minutes to a few days.
> My ZeroTier network runs on 10.251.251.0/24 and I'm not sure what the point of the gateway on a completely different and unreachable subnet is.
> 
> My ZeroTier network configuration is as follows:
> 
> * Access Control: [x] Private Network
> * Frame Types Allowed: [x] IPv4
> * Have ZeroTier Assign IPv4 Addresses: 10.251.251.0/24
> * Multicast Limit: 32
> * Broadcast: [x] Enable Wildcard MAC
> 
> My next step would be to see if I can host my own DHCP server to serve IP's to my ZeroTier network, without a gateway set.
> These problems have been around for as long as I can remember but I dismissed them as harmless bugs, at this point I've grown rather dependent on ZeroTier VPN and the connectivity issues are becoming major annoyances.
> 
> Based on my observations running version 1.0.1.
hi SharkyRawr. i come across same issue in windows 7 and 10, both in laptop and desktop. im a new user for zt. my version is 1.4.2. but it drives crazy to stop zt adapter to get back to normal. is there solution now? could you share? so much thank you in advance.

**Comment by sampoon** [comment] 2019-09-01 10:20
> Closing for now, will re-open if more issues arise.

hello Adam. im from China, a new zt user for about two months. but i encouter the same problem as this topic shows on 1.4.2 verion. i check my drier information: it is zttap300. so is there any solution now as this topic happens in 2015? so much thank you in advance~

**Comment by dfc643** [comment] 2019-09-22 09:22
same issue here,
zt1.4.6 with zttap300 and windows 8.1

i has been joined two zt networks
when i plugout ethernet cable or plugin cable

windows network changes
and internet connection has been lost.
when i disable zt virtual adapters
my internet back again

or waiting for 2~3 mins, internet back again
