### ISSUE TITLE
[ASUSWRT] zerotier-one: abnormal termination: memory allocation failure

### ISSUE THREAD

**Issue by 2senel** [zerotier/ZeroTierOne#164] opened 2015-04-27 07:20 UTC
After reboot, I get this error:

zerotier-one: abnormal termination: memory allocation failure

tried to reinstall - still same.

node.log:
[Mon Apr 27 07:15:02 2015] starting version 1.0.2
[Mon Apr 27 07:15:02 2015] no identity found or identity invalid, generating one... this might take a few seconds...
[Mon Apr 27 07:15:02 2015] terminating: memory allocation failure

**Comment by mwarning** [comment] 2015-05-01 12:59
May I ask , where did you get your binaries from?

**Comment by 2senel** [comment] 2015-05-02 07:16
Compiled from source using entware/openwrt toolchain.

**Comment by mwarning** [comment] 2015-05-02 08:39
If you have 32MB RAM, then this might be too low. In this case, I assume you compiled ZT not using uClibc++. Otherwise, ZT will allocate too much memory.

**Comment by adamierymenko** [comment] 2015-05-20 20:02
I think this is a duplicate of #149 so I am closing -- please see that issue.

**Closed by adamierymenko** 2015-05-20 20:02 UTC
