### ISSUE TITLE
Unstable connections / flapping

### ISSUE THREAD

**Issue by StrikerTwo** [zerotier/ZeroTierOne#614] opened 2017-11-07 14:13 UTC
My devices constantly switch between "ONLINE" and "x.yy s" in central. Some connections (especially between  5e96a8e284 and the device I ran this on) are very unstable.

If I run `zerotier-cli listpeers` in a loop, it looks like this:
```
200 listpeers 17d709436c 37.59.34.61/33525;1794;2542;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;18446744073709551084;312;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 78.47.80.xxx/54437;2074;872;1.00 62 1.2.4 LEAF
200 listpeers 5e96a8e284 - 63 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;4688;4282;0.84 91 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;18446744073709550866;186;0.85 346 1.1.5 PLANET
200 listpeers d21968ea9c 87.138.83.xxx/45345;7448;7448;0.94 123 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;18446744073709550866;186;0.99 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;1440;1314;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;1470;5208;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 78.47.80.xxx/54437;92;92;0.98 86 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;844;15078;0.84 230 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;6880;11796;0.85 346 1.1.5 PLANET
200 listpeers b1d366e81f - 0 - LEAF
200 listpeers d21968ea9c 87.138.83.xxx/45345;1564;3890;0.95 123 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;1564;1502;0.99 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;2156;7034;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;2186;10928;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.xxx/54437;30;30;1.00 79 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;1544;20766;0.84 260 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;2082;17484;0.85 287 1.1.5 PLANET
200 listpeers b1d366e81f - 0 - LEAF
200 listpeers d21968ea9c - 123 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;2218;7160;0.99 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;656;656;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;2146;1904;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.xxx/54437;30;0;1.00 79 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;1310;2248;0.84 260 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;4764;20166;0.85 287 1.1.5 PLANET
200 listpeers b1d366e81f - 0 - LEAF
200 listpeers d21968ea9c 87.138.83.xxx/45345;2506;2506;0.95 123 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;4900;9842;0.99 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;8280;8280;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;2338;2400;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.xxx/54437;32;0;1.00 62 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;280;1776;0.84 322 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;4260;5166;0.85 326 1.1.5 PLANET
200 listpeers d21968ea9c - 124 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;4260;9182;1.00 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;2292;13820;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;2166;1886;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.xxx/54437;30;30;1.00 62 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;5790;7286;0.84 473 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;1216;2198;0.85 350 1.1.5 PLANET
200 listpeers d21968ea9c - 124 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;9802;4696;1.00 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;3152;1574;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd - 154 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.xxx/54437;30;30;1.00 62 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;1054;158;0.84 399 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;158;86;0.85 265 1.1.5 PLANET
200 listpeers d21968ea9c 87.138.83.xxx/45345;126;30;0.95 124 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;3152;8114;1.00 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;5820;9242;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;7266;7328;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.xxx/54437;562;592;1.00 62 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;8754;7858;0.84 310 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;750;750;0.85 206 1.1.5 PLANET
200 listpeers d21968ea9c - 124 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;5882;5820;1.00 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;6788;6788;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd - 154 1.2.4 LEAF
200 listpeers 5e96a8e284 78.47.80.xxx/9993;32;32;1.00 62 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;5274;7212;0.84 379 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;1246;12202;0.85 369 1.1.5 PLANET
200 listpeers d21968ea9c 87.138.83.xxx/45345;18446744073709551084;188;0.95 124 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;3148;3084;1.00 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;7884;7884;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd - 154 1.2.4 LEAF
200 listpeers 5e96a8e284 78.47.80.xxx/9993;32;0;1.00 62 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;6338;62;0.84 379 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;94;13298;0.85 369 1.1.5 PLANET
200 listpeers d21968ea9c - 124 1.2.4 LEAF
200 listpeers fe23c4c5bd 40.68.42.255/9993;4214;4150;1.00 81 1.2.4 LEAF

200 listpeers 17d709436c 37.59.34.61/33525;18446744073709551584;8694;0.99 592 1.2.5 LEAF
200 listpeers 4ccda4c8dd 188.174.141.xxx/9993;652;714;0.95 154 1.2.4 LEAF
200 listpeers 5e96a8e284 78.47.80.xxx/9993;30;30;1.00 62 1.2.4 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;7178;902;0.84 330 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.xxx/9993;934;14138;0.85 371 1.1.5 PLANET
200 listpeers d21968ea9c - 124 1.2.4 LEAF
200 listpeers fe23c4c5bd - 81 1.2.4 LEAF
```
Is any of this normal?

**Comment by adamierymenko** [comment] 2017-11-07 23:04
This is more than one issue. The first is a UI issue in Central which is being fixed soon. The second is an actual path flapping issue that's going to be addressed in 1.2.6, which has re-worked path selection and stability code that's been designed in preparation for multi-path and more advanced SD-WAN features.

**Comment by adamierymenko** [comment] 2017-11-07 23:10
I believe this stuff is fixed in `dev` for both zerotier-one and Central but labeling nonetheless to remind us to test more. :)

**Comment by StrikerTwo** [comment] 2017-11-08 08:46
OK, great. Is there an ETA for 1.2.6?

Any way to mitigate the problem until then? That device has a static IP, can I use a fixed path or something? I only remember reading that somewhere in an old issue ;)

**Comment by adamierymenko** [comment] 2017-11-17 22:04
Marking as dupe of #619

**Closed by adamierymenko** 2017-11-17 22:04 UTC
Labels: bug
