### ISSUE TITLE
Windows coexistence problems with HyperV and/or OpenVPN

### ISSUE THREAD

**Issue by jdrews** [zerotier/ZeroTierOne#357] opened 2016-07-13 03:22 UTC
Receiving the following message on a Windows 10 client with 1.1.12.

```
Error joining Network: Cannot connect to ZeroTier service
```

![screenshot_071216_111300_pm](https://cloud.githubusercontent.com/assets/172766/16790766/784abe5e-4886-11e6-8b54-4a9e17292ec2.jpg)

I confirmed the ZeroTier service is running. Is there a log file somewhere for further information?

If I close the client and then open it again I receive the following message after about 2 minutes:

```
Unable to connect to ZeroTier Service
```

![screenshot_071216_111645_pm](https://cloud.githubusercontent.com/assets/172766/16790794/b5564764-4886-11e6-837d-fa7c8fc3df85.jpg)

Then stopping the ZeroTier service (via services.msc) results in 

```
Windows could not stop the ZeroTier One service on Local Computer
Error 1053: The service did not respond to the start or control request in a timely fashion
```

![screenshot_071216_111923_pm](https://cloud.githubusercontent.com/assets/172766/16790836/136128ba-4887-11e6-9613-e959b1def7e3.jpg)

The service then says it is stopped. Turning it on again takes a 1-2 seconds, but does not fix above issues.

**Comment by adamierymenko** [comment] 2016-07-13 04:08
What version of Windows is this? 32 or 64 bit?

**Comment by jdrews** [comment] 2016-07-13 04:32
64  bit. 

Further information. I rebooted client host (windows) and it was able to join a zerotier network. Then I joined and left it twice. On the second leave, I experienced this behavior... Unfortunately it looks to be an intermittent issue...

**Comment by adamierymenko** [comment] 2016-07-13 16:28
We'll try repeatedly adding and leaving networks on Windows 10 x64 and see if we can reproduce.

Is this host running other VPN, tunnel, or network virtualization software or VM software like HyperV? We've heard intermittent reports of issues when other things like that are installed but so far have not been able to reproduce.

**Comment by jdrews** [comment] 2016-07-13 19:00
Good call on that. The Windows 10 host did have OpenVPN installed (client was not running, service was running though) and Hyper-V. I'll look into those when I get some time.

**Comment by adamierymenko** [comment] 2016-07-14 13:59
This may be related to or a duplicate of #308

**Comment by adamierymenko** [comment] 2016-07-14 20:19
Absolutely no problem on CLEAN Windows 10 after many leave/joins... now installing OpenVPN.

**Comment by adamierymenko** [comment] 2016-07-14 20:32
Another question: does your account have administrator rights?

**Comment by adamierymenko** [comment] 2016-07-14 21:05
Added Hyper-V and am still unable to reproduce this problem.

Can you post some information about your Hyper-V settings? Are you running any VMs? Do you have any virtual switches configured?

**Comment by jdrews** [comment] 2016-07-14 21:25
The account does have administrator rights. 

It does have a virtual switch configured on the primary ethernet interface as well as the wireless interface. No VMs were running when this issue occurred.

**Comment by adamierymenko** [comment] 2016-07-18 18:05
Okay, going to try replicating a similar config and testing.

**Comment by adamierymenko** [comment] 2016-11-29 19:41
I believe we have *FINALLY* been able to duplicate this on a bare metal Windows machine with HyperV. I think this is also a duplicate of #308 since that's part of the symptom.

Working on it!

**Comment by adamierymenko** [comment] 2016-11-29 19:43
Reproduced with 1.1.14 -- almost certainly a driver issue related to coexistence with HyperV and possibly other things.

**Comment by adamierymenko** [comment] 2016-11-30 18:09
We've narrowed it down-- when ZT starts on a bare metal HyperV host, a single core gets MAX'd out... but the CPU thrashing is happening in `bridge.sys` which is part of Windows. Not sure yet if it's a HyperV component or a Windows component but that's where the evil is happening.

My guess is that our virtual network port driver (which is a pretty thin fork of OpenVPN's open source tap-win32 NDIS6 version) is not responding to something or is responding in a way `bridge.sys` doesn't like and is triggering a bug in MS's code. Unfortunately we are going to have to eat it because MS is not going to fix this for us.

**Comment by adamierymenko** [comment] 2016-11-30 18:13
Googling shows a *lot* of issues with `bridge.sys`. :(

**Comment by glimberg** [comment] 2016-12-08 18:24
@jdrews Is your Hyper-V virtual switch bridged to a wireless network card?

**Comment by jdrews** [comment] 2016-12-09 05:09
@glimberg Yes I had two Hyper-V virtual switches bridged to physical devices. One to my external ethernet device, and one to my wireless device. See screenshot earlier in this thread.

**Comment by glimberg** [comment] 2016-12-09 17:03
OK.  That mirrors what we're seeing here in the office.  It only happens when bridged with a wireless network card.  

We have a ticket open with Microsoft and their networking group is looking into the issue.   Hopefully they can either issue a fix for Windows, or let us know what we can change in our driver to prevent the issue from happening.

**Comment by glimberg** [comment] 2016-12-09 20:07
@jdrews Good news!  With some feedback from Microsoft we got this morning, it looks like we have this issue fixed internally and should make it into the 1.2.0 release.

**Comment by adamierymenko** [comment] 2016-12-09 20:09
https://www.youtube.com/watch?v=PHQLQ1Rc_Js

**Comment by jdrews** [comment] 2016-12-11 16:36
Great news! Thanks!

**Comment by gbraad** [comment] 2017-02-16 15:48
This issue is still happening and causes what seems Wireless to not receive DHCP when a Virtual Switch setup for Hyper-V exists.

**Comment by adamierymenko** [comment] 2017-02-16 15:55
Is this still happening with the 1.2.0 preview beta release?

https://download.zerotier.com/RELEASES/1.1.17-pre1.2.0/dist/

This should be fixed in `dev`.

**Comment by gbraad** [comment] 2017-02-16 15:59
OK, will check with the preview release...

**Comment by gbraad** [comment] 2017-02-16 16:22
@adamierymenko took a while to download, but have been able to confirm that with this file it seems to work. The Wireless adapter acts as expected... I am pretty sure now, this has also been the problem on another system. What is the ETA for a release with this fix?

**Comment by adamierymenko** [comment] 2017-02-16 16:25
We are in final testing and documentation for 1.2.0. We wanted it out a month or so ago, so we're heads down on it!

**Comment by adamierymenko** [comment] 2017-02-16 16:25
1.2.0 contains a **lot** of improvements and new capabilities.

**Comment by adamierymenko** [comment] 2017-02-16 16:26
It remains backward compatible with 1.1.14 (and all the way back to 1.0.1).

**Comment by gbraad** [comment] 2017-02-16 16:33
will keep the current version installed, but looking forward to the 1.2.0 release

**Closed** 2017-03-15 15:13 UTC
Labels: bug

**Comment by layer4down** [comment] 2018-05-21 03:38
Experienced this same issue with FortiClient VPN client (Error: Cannot connect to ZeroTier service)... uninstalled FortiClient software and ZeroTier, then reinstalled ZT client.. ZT immediately began working correctly as advertized (didn't even need to reboot). HTH!

Windows 10 Home v1709 Build 16299.431
