### ISSUE TITLE
Join/Leave => Join/Leave + Connect/Disconnect

### ISSUE THREAD

**Issue by jrz** [zerotier/ZeroTierOne#326] opened 2016-05-18 13:03 UTC
I'd like to be able to set each network to auto-connect (true / false), and to manually connect / disconnect.

**Comment by jdrews** [comment] 2016-05-20 21:43
I believe this is a duplicate of #49

But I wholeheartedly agree! :+1:

**Comment by adamierymenko** [comment] 2016-05-25 22:06
Closed as duplicate of #49

**Closed by adamierymenko** 2016-05-25 22:06 UTC
