### ISSUE TITLE
DHCP support: Android devices, Windows DHCP enable on Windows interface, etc.

### ISSUE THREAD

**Issue by dafyre** [zerotier/ZeroTierOne#243] opened 2015-11-02 05:04 UTC
I seem to have noticed a few issues when using ZeroTier and my own DHCP server.

Once I set ZeroTier to not manage IP addresses at all, none of the devices will get an address from my DHCP server.  I must go to the NIC properties on each device (in Windows), and reset the Network Card to use DHCP for the IP address and DNS settings.

On Linux, I must manually call dhclient zt#  (where zt# is the Nic interface name which may not necessarily be 0 (zero) (Tested on Ubuntu 14 and Fedora 22).

This also causes me to not be able to use the Android client, as it will not pull an IP address from the system, and as such, does not show any interfaces for me to execute dhclient against...  (Samsung Note 4, Android 5.0.1).

**Comment by adamierymenko** [comment] 2015-11-04 23:18
Hmm... two things this brings up: (1) DHCP is disabled on the interface by default in Windows and would have to be manually enabled, and (2) Android has no DHCP!

The second should probably be listed in the Android app's page as a limitation. I'm adding this to the feature queue because there are several issues that this brings to light.

**Comment by dafyre** [comment] 2015-11-04 23:26
For Windows, maybe you could set the NICs to do DHCP whenever the ZeroTier controller is set to not manage the IP addresses.

Manually setting the the NICs to DHCP works fine in Windows.

On my Linux boxes, I have to either run DHClient directly on zt0 or directly assign them an IP at the end of the boot process.

For the Android Client...  add DHCP!...  Or at least give us a box to plug in an IP addy. :-)

**Comment by adamierymenko** [comment] 2016-06-21 22:07
This is a duplicate of #322 -- closing since it's a subset of future more-native DHCP support.

**Closed by adamierymenko** 2016-06-21 22:07 UTC
Labels: backlog, enhancement
