### ISSUE TITLE
listpeers by networks

### ISSUE THREAD

**Issue by maci0** [zerotier/ZeroTierOne#292] opened 2016-01-13 12:05 UTC
The listpeers syntax should be changes to something like
```zerotier-cli listpeers [network] [network]...         - List all peers, optionally list peers in provides network(s).```
This helps in instances where you are connected to earth and some other networks at the same time but only want to see the peers of certain networks

**Comment by adamierymenko** [comment] 2016-01-14 01:50
This is sort of a duplicate of #159 - closing and this will pop up as a reference over there.

It will require a small bit of refactoring so it has to go behind a few other things, but it's in the backlog. We will also want the Peer object to be aware of networks for other reasons in the future.

**Closed by adamierymenko** 2016-01-14 01:50 UTC
Labels: backlog
