### ISSUE TITLE
Espressobin performance

### ISSUE THREAD

**Issue by alejandroed** [zerotier/ZeroTierOne#914] opened 2019-02-04 13:12 UTC
Hi!

I'm trying a few Espressobin v7 boards with Armbian (Linux 4.19.14) and ZeroTier (1.2.12 and 1.2.13) compiled from sources and the repo packages as well. These are  my homelab results with iPerf3 with and without ZeroTier:

Without ZT:
- Between two espressobin v7, ~977.2 Mbits/sec
- Between one espressobin v7 and a Xeon Server with AES-NI support, ~974,2 Mbits/sec

With ZT:
- Between two espressobin v7, ~77.2 Mbits/sec
- Between one espressobin v7 and a Xeon Server with AES-NI support, ~120 Mbits/sec

I've tried with [marvell-cesa and cryptodev](https://forum.armbian.com/topic/8486-helios4-cryptographic-engines-and-security-accelerator-cesa-benchmarking/) offload with no luck.

All my peers are in the same subnet in the same switch and <1ms latency, i've not problems with NAT but it seems that the Cortex A53 processor is not enough for this crypto task. I guess that this is the same ARM board that edge has and edge promises Gbps performance... Any ideas?

**Comment by adamierymenko** [comment] 2019-02-05 19:51
Those seem like low numbers to me!

Is your ARMbian 64-bit? I know that some AARCH64 cores do not run ARM32 code at the same speed due to microcode emulated instructions.

**Comment by alejandroed** [comment] 2019-02-06 09:07
Hi Adam!

Yes it is:

`root@espressobin:~# uname -ar
Linux espressobin 4.14.79-mvebu64 #2 SMP PREEMPT Sat Jan 12 16:40:48 CET 2019 aarch64 GNU/Linux`

This is my /proc/crypto:

`root@espressobin:~# cat /proc/crypto
name         : hmac(sha1)
driver       : safexcel-hmac-sha1
module       : crypto_safexcel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : ahash
async        : yes
blocksize    : 64
digestsize   : 20

name         : sha256
driver       : safexcel-sha256
module       : crypto_safexcel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : ahash
async        : yes
blocksize    : 64
digestsize   : 32

name         : sha224
driver       : safexcel-sha224
module       : crypto_safexcel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : ahash
async        : yes
blocksize    : 64
digestsize   : 28

name         : sha1
driver       : safexcel-sha1
module       : crypto_safexcel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : ahash
async        : yes
blocksize    : 64
digestsize   : 20

name         : cbc(aes)
driver       : safexcel-cbc-aes
module       : crypto_safexcel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ecb(aes)
driver       : safexcel-ecb-aes
module       : crypto_safexcel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : des3_ede
driver       : des3_ede-generic
module       : des_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 8
min keysize  : 24
max keysize  : 24

name         : des
driver       : des-generic
module       : des_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 8
min keysize  : 8
max keysize  : 8

name         : lz4
driver       : lz4-scomp
module       : lz4
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : scomp

name         : lz4
driver       : lz4-generic
module       : lz4
priority     : 0
refcnt       : 3
selftest     : passed
internal     : no
type         : compression

name         : cbc(aes)
driver       : cbc(aes-ce)
module       : kernel
priority     : 250
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : jitterentropy_rng
driver       : jitterentropy_rng
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_nopr_hmac_sha256
module       : kernel
priority     : 207
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_nopr_hmac_sha512
module       : kernel
priority     : 206
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_nopr_hmac_sha384
module       : kernel
priority     : 205
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_nopr_hmac_sha1
module       : kernel
priority     : 204
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_pr_hmac_sha256
module       : kernel
priority     : 203
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_pr_hmac_sha512
module       : kernel
priority     : 202
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_pr_hmac_sha384
module       : kernel
priority     : 201
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : drbg_pr_hmac_sha1
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 0

name         : stdrng
driver       : ansi_cprng
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : rng
seedsize     : 48

name         : lzo
driver       : lzo-scomp
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : scomp

name         : lzo
driver       : lzo-generic
module       : kernel
priority     : 0
refcnt       : 6
selftest     : passed
internal     : no
type         : compression

name         : crct10dif
driver       : crct10dif-generic
module       : kernel
priority     : 100
refcnt       : 2
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 2

name         : crc32
driver       : crc32-generic
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 4

name         : crc32c
driver       : crc32c-generic
module       : kernel
priority     : 100
refcnt       : 5
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 4

name         : zlib-deflate
driver       : zlib-deflate-scomp
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : scomp

name         : deflate
driver       : deflate-scomp
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : scomp

name         : deflate
driver       : deflate-generic
module       : kernel
priority     : 0
refcnt       : 2
selftest     : passed
internal     : no
type         : compression

name         : aes
driver       : aes-generic
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 16
min keysize  : 16
max keysize  : 32

name         : sha224
driver       : sha224-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 28

name         : sha256
driver       : sha256-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 32

name         : sha1
driver       : sha1-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 20

name         : md5
driver       : md5-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 16

name         : digest_null
driver       : digest_null-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 0

name         : compress_null
driver       : compress_null-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : compression

name         : ecb(cipher_null)
driver       : ecb-cipher_null
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : blkcipher
blocksize    : 1
min keysize  : 0
max keysize  : 0
ivsize       : 0
geniv        : <default>

name         : cipher_null
driver       : cipher_null-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 1
min keysize  : 0
max keysize  : 0

name         : aes
driver       : aes-arm64
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 16
min keysize  : 16
max keysize  : 32

name         : sha224
driver       : sha224-arm64-neon
module       : kernel
priority     : 150
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 28

name         : sha256
driver       : sha256-arm64-neon
module       : kernel
priority     : 150
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 32

name         : sha224
driver       : sha224-arm64
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 28

name         : sha256
driver       : sha256-arm64
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 32

name         : xts(aes)
driver       : xts-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ctr(aes)
driver       : ctr-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : cbc(aes)
driver       : cbc-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ecb(aes)
driver       : ecb-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : cbcmac(aes)
driver       : cbcmac-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 16

name         : xcbc(aes)
driver       : xcbc-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 16
digestsize   : 16

name         : cmac(aes)
driver       : cmac-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 16
digestsize   : 16

name         : __xts(aes)
driver       : __xts-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ctr(aes)
driver       : ctr-aes-neon
module       : kernel
priority     : 199
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __ctr(aes)
driver       : __ctr-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __cbc(aes)
driver       : __cbc-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __ecb(aes)
driver       : __ecb-aes-neon
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : xts(aes)
driver       : xts-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ctr(aes)
driver       : ctr-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : cbc(aes)
driver       : cbc-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ecb(aes)
driver       : ecb-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : cbcmac(aes)
driver       : cbcmac-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 16

name         : xcbc(aes)
driver       : xcbc-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 16
digestsize   : 16

name         : cmac(aes)
driver       : cmac-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 16
digestsize   : 16

name         : __xts(aes)
driver       : __xts-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ctr(aes)
driver       : ctr-aes-ce
module       : kernel
priority     : 299
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __ctr(aes)
driver       : __ctr-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __cbc(aes)
driver       : __cbc-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __ecb(aes)
driver       : __ecb-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : ccm(aes)
driver       : ccm-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : aead
async        : no
blocksize    : 1
ivsize       : 16
maxauthsize  : 16
geniv        : <none>

name         : aes
driver       : aes-ce
module       : kernel
priority     : 250
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 16
min keysize  : 16
max keysize  : 32

name         : gcm(aes)
driver       : gcm-aes-ce
module       : kernel
priority     : 300
refcnt       : 1
selftest     : passed
internal     : no
type         : aead
async        : no
blocksize    : 1
ivsize       : 12
maxauthsize  : 16
geniv        : <none>

name         : ghash
driver       : ghash-ce
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 16
digestsize   : 16

name         : sha256
driver       : sha256-ce
module       : kernel
priority     : 200
refcnt       : 2
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 32

name         : sha224
driver       : sha224-ce
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 28

name         : sha1
driver       : sha1-ce
module       : kernel
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 20`

and my loaded modules:

`root@espressobin:~# lsmod
Module                  Size  Used by
crypto_safexcel        40960  0
cryptoloop             16384  0
crypto_engine          16384  0
cryptodev              57344  0
marvell_cesa           45056  0
des_generic            24576  1 marvell_cesa
lz4                    16384  2
lz4_compress           32768  1 lz4
zram                   28672  3
zsmalloc               28672  1 zram
bridge                131072  0
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
ip_tables              28672  0
x_tables               40960  1 ip_tables
autofs4                36864  0`

**Comment by alejandroed** [comment] 2019-04-24 08:57
Hi!

I've done some progress in my lab to determine where is the bottleneck, using Wireguard (chacha20+poly1305) instead of Zerotier (Salsa20+Poly1305) I can get 2.5x performance at similar CPU loads. Maybe the salsa20 algorithm is causing the performance problems?

**Comment by genieinfo** [comment] 2019-04-28 17:42
Hi,
I jump in as i recently received 2 Edge's, Zerotier in-house espressobin based devices.
I will call them ZT Edge.
The performance is very poor compared to what i experienced with all my others Zerotier software-based devices, whether it being installed on x86_64 Windows VM, x86_64 MacOS, x86_64 Linux VM, ARM Raspi 3B+, ARM Android, x86_64 AMD Geode LX OPNsense appliance.
All of them have 4-core except the VM's that count 2 cores each.
I'm talking straight about CPU cores because i now think the ZT Edge performance problem is clearly related to the numbers of cores (which sounds logical :p)
Sorry it will be quite a long post but i want to be as precise as possible before i ask my final question to Zerotier team (you can scroll directly to the end of this post if you want to know what is my question first :)

Back to ZT Edge and all the machines involved in testing.
We consider that every machine is physically wired @ gigabit speeds with MTU 1500 everywhere.
Also, i installed CLI versions of the following binaries/scripts on desired machines at every location :
iperf3 / htop / speedtest-cli / iftop

Here under is a brief setup summary of the 2 distant sites i use for real-world scenario performance tests. 
I will call them LAN1/WAN1 and LAN2/WAN2. 
LAN1 sits behind WAN1 (NAT with UDP 9993 in/out bound to ZT Edge, upnp active for testing only)
LAN2 sits behind WAN2 (DC hosted NAT i guess but so far, ZT had no problem finding its peers and communicate directly with them)

WAN1 (consumer ISP) 
200mb/s down and 20mb/s up

LAN1
. ZT Edge 2-cores Marvell 64bit ARM A53 (espressobin based) / aarch64 Linux 4.19.1zerotier / ZT 1.2.12 ??
(i couldn't get the exact ZT software version with privileged cmd zerotier-cli as sudo is prohibited on my ZT Edge, nor i found the relevant info on ZT Edge Status web-page)
. Router with 4 Gigabit LAN ports
. Gigabit switches (unmanaged and no tweaks, raw L2 switching)
. Synology NAS 4-cores x86_64 Atom CPU / 5x 7,2k rpm HDD in RAID5 / Linux 3.10.105 kernel / ZT 1.2.8
. Macbook pro 4-cores x86_64 Intel i7@2,3GHz / macOS 10.11.6 / ZT 1.2.12
. VMware VM 2-vcores x86_64 Intel i7@2,3GHz / Windows 7 pro 64 bits up to date / ZT 1.2.12
. Raspberry Pi 3B+ 4-cores ARM Cortex A53 / Raspbian Linux 4.xx / ZT 1.2.12

WAN2 (DC hosted)
1Gb/s down and 100mb/s up
 
LAN2 
. RedHat VM / Quad-core Xeon 3,2GHz / 12GB RAM / Windows 10 64bits v1809 / ZT 1.2.12 installed


I could verify the reliability of the advertised WAN speeds @ the 2 locations numerous times and can assure they perform as intended : 
. speedtest-cli could verify that
. iperf3 could verify that
. raw SMB copy of files and folders could verify that

Each time i did measurements, i got similar and constant results by any of the 3 bandwidth and speed test methods mentionned above.

Results:

. iperf3 LAN1 pulling from LAN2 - ZT DIRECT CONNECTION - Synology ZT 1.2.8 <> Windows 10 64bits ZT 1.2.12 = 100mb/s constant during 120s.
. iperf3 LAN1 pulling from LAN2 - ZT EDGE BRIDGING - Synology Gigabit Native Interface <> Windows 10 64bits ZT 1.2.12 = 33mb/s average during 120s.
. iperf3 LAN1 pulling from LAN2 - ZT RASPI3B+ BRIDGING - Synology Gigabit Native Interface <> Windows 10 64bits ZT 1.2.12 = 60mb/s average during 120s.

. SMB raw file copy (15GB .iso) LAN1 pulling from LAN2 - ZT DIRECT CONNECTION - Synology ZT 1.2.8 <> Windows 10 64bits ZT 1.2.12 = 100mb/s constant with very very few drops, never under 70 mb/s
. SMB raw file copy (15GB .iso) LAN1 pulling from LAN2 - ZT EDGE BRIDGING - Synology Gigabit Native Interface <> Windows 10 64bits ZT 1.2.12 = 33mb/s average with variations from 16Mb/s to 55mb/s
. SMB raw file copy (15GB .iso) LAN1 pulling from LAN2 - ZT RASPI3B+ BRIDGING - Synology Gigabit Native Interface <> Windows 10 64bits ZT 1.2.12 = 60mb/s average with variations from 40Mb/s to 70mb/s

. speedtest-cli WAN1 193mb/s down and 19mb/s up (very constant across tests, across devices, always close to the advertised values)
. speedtest-cli WAN2 998mb/s down and 107mb/s up (very constant across tests, across devices, always close to the advertised values)

htop on the ZT Edge Bridge would exhibits very very high CPU usage values (close to 100% on the 2 cores) during the 55mb/s -very rare- peaks. 
And be sitting constantly around 60-70% on the 2 cores when transferring at 33mb/s.

htop on the ZT Raspi3B+ Bridge would exhibits reasonnably high CPU usage values during the average 60mb/s transfers and never fully load the 4 CPU cores during the rare 70mb/s peaks. 
And be sitting constantly around 60-70% on the 2 first cores and 30-40% on the the 2 other cores when transferring at 60mb/s.

I've never experienced any relaying during my tests, direct connection had always been possible between all the devices. 
zerotier-cli on LEAFs were all giving useful information on their status and it was clear they weren't being relayed but spoke directly to each others
iftop also gave me very precious infos as it would show them in a source <> destination fashion, doubled with speeds, very useful to see from where to where the traffic went and it was clear the devices talked to each other directly.
(and i can tell that, based on another test i did, showing some relay occurring, the speeds where never above 10mb/s in that case, and very often close to 5mb/s)

So, my question : is the ZT Edge capable of sustained and acceptable cyphering with its 2-cores ARM CPU, above let's say 60mb/s average ?
Thanks a lot in advance for your answers as i can't explain myself why the in-house optimized Zerotier Edge device can not perform as well as other devices i set up myself.

Sebastien

**Comment by sjansen1** [comment] 2019-06-12 07:27
I get around 65-70mbit/sec if everything goes well. If the connection is not perfect it goes down to 2-5mbit/sec. For me It looks like out of order UDP Pakets from Zerotier increases the CPU usage on the Edge alot and there is not enough CPU Power to keep up the bandwith/encryption.

**Comment by genieinfo** [comment] 2019-06-26 20:41
@sjansen1 and alejandroed
Many thanks for posting your results here. 
I experienced the exact same constant ~250mb/s performance between Windows/Linux ZT clients located in 2 sites where WAN connections allowed 300Mb up on one side and 1Gb down on the other side. Which is great for most usages. 
Would it be the maximum Zerotier is capable of regardless of the CPU arch ?
Again thanks for sharing this.
I'll try a few more tests now i have these 2 much-more-than-acceptable WAN connections at my disposal.
See you

@adamierymenko 
When do you release Zerotier 1.4 ? I'm impatient :)
Again, thanks for this wonderful tool you wrote

**Comment by adamierymenko** [comment] 2020-02-26 20:35
Closing since 2.x makes some large improvements here

**Closed by adamierymenko** 2020-02-26 20:35 UTC
Labels: performance, question
