### ISSUE TITLE
GUI client 1.2.12 not working on windows 7 after rebooot.

### ISSUE THREAD

**Issue by canidorichard** [zerotier/ZeroTierOne#849] opened 2018-09-13 08:02 UTC
**Describe the bug**
I have installed ZertoTier One on WIndows 7 and used the GUI to join a network which was then displayed in the GUI as expected.  When the computer is rebooted however, the GUI has no details of the network and the Node ID is shown as unknown. Seecting "Show Networks..." display a window with a plain white background and nothing else.

The service is running and executing the command zerotier-cli shownetworks from the command prompt shows the connected network details as expected and ipconfig shows the interface with the expected IP address

Removing and re-installing ZeroTier One fixes the issue temporarily until the computer is rebooted again.

My WIndows 7 machine is a VMWare virtual machine but I do not see as this should make a difference.  I don't have a physical Windows 7 machine.

**To Reproduce**
1. Install ZeroTier One
2. Join a network
3. Confirm GUI shows network information correctly and that machine is reachable o ZeroTier IP.
4. Reboot computer
5. Note that GUI no longer has details of the network (THIS IS THE ERROR)
6. Confirm that machine is still reachabe over ZeroTier IP
7. Confirm that command line client correclty displays details.
[zerotier_issue_win7.pdf](https://github.com/zerotier/ZeroTierOne/files/2378258/zerotier_issue_win7.pdf)

**Expected behavior**
In step 5 above it is expected that the GUI displays details of the connected network and allows management of that connection.

**Screenshots**
PDF document zerotier_issue_winz.pdf attached containing screenshots of this issue.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - ZeroTier Version: 1.2.12
 - Hardware: VMWare Virtul Machine

**Comment by adamierymenko** [comment] 2018-11-28 16:52
Labeling as duplicate of #865 since it's likely a similar issue

**Closed by adamierymenko** 2018-11-28 16:52 UTC
Labels: bug
