### ISSUE TITLE
Ubuntu Artful failed to install

### ISSUE THREAD

**Issue by Split7fire** [zerotier/ZeroTierOne#674] opened 2018-02-04 04:45 UTC
Trying to install zerotier-cli on freshly installed Ubuntu 17.10, but it fails with 
`http://download.zerotier.com/debian/artful artful Release                                              
  404  Not Found [IP: 88.198.33.108 80]
`
Any suggestions?

P.S. apt-transport-http already installed

**Comment by metawindow** [comment] 2018-02-04 16:03
+1 This is more urgent since Ubuntu has EOL'd Zesty, nudging everyone that is not running LTS to use Aardvark.  Issue #607 was closed because Aardvark is "now in the build farm" but apparently that build needs to make its way into actually being downloadable.

**Comment by Saloqin** [comment] 2018-02-05 10:18
+1 Got the same issue. Would be awesome to have it fixed soon because everyone is updating to 17.10 right now.

**Comment by ChaosZero112** [comment] 2018-02-07 01:26
+1 Adding my voice to the Aardvark choir.

**Comment by Split7fire** [comment] 2018-02-07 13:00
Sadly, 3 days passed and no answer from developers.

**Comment by nate8199** [comment] 2018-02-08 20:32
I'm using 17.10 and I don't remember having any issues installing zerotier,
I must have installed it a few months ago, I picked 17.10 for my VM to be a
docker host since it worked by default better than Debian.

**Comment by laduke** [comment] 2018-02-08 20:56
Artful download Coming Soon™️

You could download the script and modify it to point artful at the zesty download. Or modify the /etc/apt/sources.list.d/zerotier.list that you probably have now. I dunno.

**Comment by ChaosZero112** [comment] 2018-02-08 21:20
Thanks for the update, @laduke 
That's exactly what I did (modified zerotier), It's working okay but I'll patiently wait for an Artful version.

**Comment by lwisdomnova** [comment] 2018-02-08 22:56
+1 please fix this.

**Comment by victorhooi** [comment] 2018-03-03 20:04
I hit this issue as well.

The script bailed out - saying artful wasn't there.

As suggested, I edited `/etc/apt/sources.list.d/zerotier.list`, replacing `artful` with `stretch`.

I then ran:
```
sudo aptitude install zerotier-one
sudo systemctl enable zerotier-one
sudo systemctl start zerotier-one
```

**Comment by adamierymenko** [comment] 2018-03-29 17:51
Fixed in current build farm, will be fixed in public release with 1.2.6 release which is almost ready.

**Closed by adamierymenko** 2018-03-29 17:51 UTC

**Comment by gsomoza** [comment] 2018-04-28 18:02
Still same issue

**Comment by gsomoza** [comment] 2018-04-29 11:55
Oh, I thought he meant release 1.2.6 for this repo (which is already at 1.2.8). Also, victorhooi's solution worked for me, thanks for that tip :) 👍

**Comment by Plantain** [comment] 2018-04-30 14:11
Can we reopen this until the problem is actually resolved?
