### ISSUE TITLE
Windows 10 64bit, lots of cpu usage when network was down, and lots of memory usage when the network came back

### ISSUE THREAD

**Issue by kangjianbin** [zerotier/ZeroTierOne#277] opened 2015-12-18 05:59 UTC
Hi, I found ZeroTier wasted too many CPU when network was down (> 30%) and after the network came back again, it allocated memory more than 1.2GB.
Platform: Windows 10 64bit

Reproduce:
1. Use wifi as the network connection
2. close Wifi. The cpu usage of ZeroTier was above 30% in 'Task manager'
3. Wait for 10 seconds
4. Re-open wifi. Now ZeroTier allocated more than 1.2GB memory and system hang.

**Comment by adamierymenko** [comment] 2015-12-21 18:16
Will investigate. Sounds like some sort of loop attempting to establish connectivity on a non-existent connection.

**Comment by adamierymenko** [comment] 2016-02-19 23:12
Tried today and could not reproduce... will leave open for now.

**Comment by adamierymenko** [comment] 2016-02-26 19:29
Does this box have HyperV on it or is it a HyperV guest?

**Comment by kangjianbin** [comment] 2016-02-27 14:23
No. It has virtualbox(which installs a Host-Only Ethernet adapter) and winpcap.

**Comment by adamierymenko** [comment] 2016-04-01 21:27
Closing since #308 is almost certainly a duplicate...

**Closed by adamierymenko** 2016-04-01 21:27 UTC
Labels: bug, cantreproduce
