### ISSUE TITLE
Zerotier difficulties to communicate with planets

### ISSUE THREAD

**Issue by cctesa** [zerotier/ZeroTierOne#1214] opened 2020-06-05 11:36 UTC
We've been testing ZeroTier for some weeks now and our network was working well till this last Tuesday 2nd of June 2020.  That day we were connected through remote desktop to some of the machines when suddenly the connection through zerotier failed. 

The zerotier connection includes some machines inside a big local network and some domestic machines. The big local network is not managed by us, so we have no real control on it or what it is filtered and we are not able to check logs their logs. But we can contact with the people on charge of it, if we know what to ask for. 

Until last Tuesday, all the machines in the Zerotier network were available through remote desktop. On Tuesday, most of the machines on the big local network failed while the domestic machines seems to be still accessible. We said most of the machines, not all of them. There are still 2 or 3 machines inside the big local network that are sill accessible through zerotier network. And others  that become alive for some minuts and then offline again.

We don't know what to start looking for and which kind of information compilate to investigate the problem.

As far as we have seen, the machines that are not working in zero tier network appear to give this information when executing:      zerotier-cli peers | grep PLANET
```
34e0a5e174 -      PLANET    -1 RELAY
3a46f1bf30 -      PLANET    -1 RELAY
778cde7190 -      PLANET    -1 RELAY
992fcf1db7 -      PLANET    -1 RELAY
```
In this case, Zerotier seems to not being able to connect to any of the planets. We guess this is needed in order to work properly.  Some of the problematic machines connect only to one or two planets, but not to the four of them.

Those machines that cannot connect with the planets, give this information when executing: zerotier-cli listnetworks
```
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks XXXXX XXXXX XXXXXX OK PRIVATE ztmjfnnfbw XXXXXXX/24
```

or this: zerotier-cli status
`200 info 585d489748 1.4.6 TUNNELED`

Which it aparently says the zero tier client is connected to the network but then:
zerotier-cli info
`200 info 585d489748 1.4.6 OFFLINE`

And also in the ZeroTier Central these machines appear offline.

We've verified that these machines have the port 9993 open (we've been testing it with telnet command from inside the local network and from the outside when the machine has a public IP). So it seems this port is not blocked. All the machines have acces to Internet and can ping the PLANET IPs.  We've also tried to restart zerotier service on them and also the machine itself. We've tested them without any firewall aswell to discard things. But the problem remains.

Are there any other tests we could make so we can get more information and see where the problem remain? The ZeroTier client has any place to look for logs? How we can force zerotier client to reconnect with their planets?(apart of restarting the service which seems not to be working) What could be blocking the access to them?

Any help will be much appreciated it.
Thanks!

**Comment by laduke** [comment] 2020-06-05 17:11
That's pretty strange. It does look like a firewall/networking issue but you've checked that.

I looked up your network and see it has an interesting setup (with the routes and rules). 

Were any of the config changes made on that day possibly? 
Do any of your zerotier subnets overlap with any of your physical subnets? 
Did a machine get cloned, and now multiple machines have the same ID?

Tangent: 
There may be simpler ways to segment your network... either by just using multiple zerotier networks, or by using tags
https://www.zerotier.com/manual/#3_5_4

**Comment by cctesa** [comment] 2020-06-08 06:04
Hi laduke, thanks for answering!

We did not make any change that day, nor added new nodes or cloned any machine. We lost the ZeroTier conection from one moment to another without apparently any reason.

We think there might be a problem with the big local network (the one we don't have control of it). They might have changed something that is affecting most of the machines with zero tier vpn but not all of them. We would like to know what kind of tests we could do in order to get any evidence of that so we could talk to the people that manages that local network knowing what to ask for. 

What kind of test we could make on the machines that are still working versus the ones that cannot connect to the root servers/Planets?

Best regards

**Comment by cctesa** [comment] 2020-06-08 11:55
Hi again,

Just to discard few more things, we have:

- Created a new ZeroTier network with another user so it is completly separated from the one that is malfunctioning.  
- Tested the new ZT network with a domestic machine and checked it has no problems to connect with it, so we can authorize it from my.zerotier.com. We try to discard that the problem is anything related with the IDs in the previous network. This new network is pretty simple and has no segmentation.
- Selected one of the machines in the big local network that is not currently working.  Completly unninstalled the ZeroTier client and also removed the configuration files located in ProgramData/ZeroTier (this is a Windows 10 machine). 
- Installed again the ZeroTier client in this machine and the id fcf1dc25ed was given. We tried to join the new network we created before and checked that ZT client is not capable to connect to it. The given status is: REQUESTING_CONFIGURATION PRIVATE ethernet_32775 

The request is not seen in my.zerotier.com so we cannot authorize the machine and if we check _zerotier-cli peers_:
```
34e0a5e174 -      PLANET    -1 RELAY
3a46f1bf30 -      PLANET    -1 RELAY
992fcf1db7 -      PLANET    -1 RELAY
de8950a8b2 -      PLANET    -1 RELAY
```
It seems the ZT client still cannot contact with ZeroTier central or their planets/root servers even though this is a new network and we have reinstalled everything. The Windows firewall has also been automatically modified by ZT to allow communications from the zerotier client and we have checked that the ZT is running. And we can see that this machine has created a new network adapter for ZT which has an IP address 169.254.x.x  that has been automatically given and it is not one valid IP address for the ZT network we created (should be 192.168.195.x)

**Comment by graphixillusion** [comment] 2020-06-14 22:14
This problem is happening more frequently lately. Anyone can enlight us about this? Thank you!

**Comment by cctesa** [comment] 2020-06-15 08:55
We finally got some traces from both a working versus a problematic machine using the software Wireshark. 

In the machine where Zerotier was working, we could check there was packets exchange between the machine and the IPs of the ZeroTier planets we have been assigned. On the other hand, the machine where it was not working, we've captured that there was no exchange. The machine sent packages to the planets but the planets never answered back.

With this traces we've been able to talk with the people responsible of the big local network where the problem was located and it seems they have done something so now all machines in that network are available again through ZeroTier. We are still facing some intermitent connection with some of them, but we are not sure if it could be a exceptional case due to network issues of the day or not. We will be testing a litlle more.

**Comment by graphixillusion** [comment] 2020-06-18 13:13
Nothing, after every reset, it works for around two/three days then some machines get the connection on Relay with the PLANET servers and zerotier-cli shows them as offline. This problem is becoming very annoying sadly...

**Comment by laduke** [comment] 2020-06-18 20:17
Hey, we're watching this thread, but are not seeing this anywhere on our own stuff. 

Could everyone summarize their environment where they are seeing this?  Hosting provider/hardware/ISP type/Linux Distro

**Comment by graphixillusion** [comment] 2020-06-18 21:13
@laduke, thanks for answering.

In my scenario, zerotier is the latest version, 1.4.6 installed everywhere. I have 3 machines with Windows 10 2004, 1 Raspberry Pi4 running Raspberry Pi OS 32bit (raspbian), and 1 Android device. I must say that this issue usually happened randomly with the Windows clients: never happened yet on my raspberry so far. Windows Server 2016 seems to suffer randomly the same thing too. I have a residential connection with a national ISP in two different locations.

**Comment by graphixillusion** [comment] 2020-06-20 16:18
I've tried to disable and re-enable the virtual network card, stop and start the zerotier services, leave and join the network: nothing of this worked. The only way to make it work again is to reset and reauthorize the identity.

**Comment by abclution** [comment] 2020-06-24 21:07
I also am encountering something quite similar, on one particular pc (Debian, baremetal, nat ) that looses connectivity.

This pc was working fine for months and has only started showing this behavior for the last 15 days or so.
Network connectivity in the network, ping to other clients in the same network doesn't work. My.zerotier shows online, but the status output in the pc says offline. Leaving / rejoining the network doesn't work.

What works for me is stopping the zerotier services for 10-15 seconds, and restarting it. Just restarting the service does not work. I must stop the service for 10 - 15 seconds and then start it again. The it finally will go online for some period of time, network connectivity resumes and all is well.  Until it decides to do that again some indeterminate time later..

**Comment by graphixillusion** [comment] 2020-06-25 12:05
And here we are: after 5 days of activity, OFFLINE again...

**Comment by graphixillusion** [comment] 2020-06-28 16:50
Today, the issues happened again. Until a proper fix will eventually comes out, i made a little script which checks the zerotier's online status and when offline it will stop the Zerotier services, wait 10 min, then restart it. This is the script for Windows cmd:
```
@echo off
setlocal EnableDelayedExpansion
FOR /F "tokens=5 delims= " %%A IN ('"zerotier-cli status | findstr "ONLINE""') DO set var=%%A
if NOT %var% == ONLINE (
goto RESTART
)
exit /B

:RESTART
sc stop zerotieroneservice
timeout /t 600 >nul
sc start zerotieroneservice
exit /B

```

**Comment by abclution** [comment] 2020-06-29 14:16
@graphixillusion Glad to hear this works for you. Yes, it is a very strange issue, and has appeared pretty recently but it is PERSISTENTLY an issue for me. Every ~12 to 16 hours I have to do this. Really sad.

Nice script, I will keep it saved for any Windows boxes I encounter with this error.

I need to write a similar script for linux...

According to the ZT documents, this should not be necessarily. ZT client is supposed to NEVER give up trying to connect, but obviously, it is just giving up once it hits this odd OFFLINE status. No logging makes this impossible to understand better.

**Comment by graphixillusion** [comment] 2020-06-29 18:23
@abclution i'm still testing this script on one box, let's see if this will do the job. Yes, it's a very strange issue, i hope we'll get a proper fix sooner than later...

**Comment by abclution** [comment] 2020-07-02 10:51
For anyone encountering this issue in linux, here is an extremely simple script for linux that can be put in cron. You can schedule it whenever 


`#!/bin/bash
SERVICECMD="/usr/sbin/service"
SERVICENAME="zerotier-one"
ZTCLI="/usr/sbin/zerotier-cli"
ZTSLEEP=15
ISOFFLINE=`$ZTCLI status | grep OFFLINE`


if [[ -z "$ISOFFLINE" ]]; then
   echo "ZEROTIER is not in an offline status."
else
   echo $ISOFFLINE
   echo "STOPPING SERVICE FOR 15 SECONDS"
   $SERVICECMD $SERVICENAME stop
   sleep $ZTSLEEP
   echo "STARTING SERVICE"
   $SERVICECMD $SERVICENAME restart
   echo "ZEROTIER RESTARTED"
fi

`

**Comment by laduke** [comment] 2020-07-02 17:17
Nice. 

Hey, can you @abclution can capture some info when it's in the offline state, before restarting?

```
zerotier-cli peers -j > $(date -d "today" +"%Y%m%d%H%M").log 
```

If you don't want to paste it here, you can email support@zerotier.com or DM my @zt-travis on the my.zerotier.com community.

**Comment by abclution** [comment] 2020-07-02 20:52
Hey sure, yea I already updated my personal script for some logging and failure times.  
Will update when I know more.

**Comment by abclution** [comment] 2020-07-04 11:03
@laduke Small update

So, 2 days have gone by and I have minute by minute checking for online status, and logging of the situation.
So far the issue occurred at exactly the same time each day, and for exactly the same amount of time. 

The following in the log directory if you look at exactly 4:40 - 5:02, on both days ZT is in an OFFLINE state (those are the peer dumps you asked for) This leads me to believe there is a local job issue so I investigated further.

```
-rw-r--r--  1 root root 5044 Jul  3 04:40 202007030440.log
-rw-r--r--  1 root root 1230 Jul  3 04:41 202007030441.log
-rw-r--r--  1 root root 2392 Jul  3 04:42 202007030442.log
-rw-r--r--  1 root root 1230 Jul  3 04:43 202007030443.log
-rw-r--r--  1 root root 2392 Jul  3 04:44 202007030444.log
-rw-r--r--  1 root root 1230 Jul  3 04:45 202007030445.log
-rw-r--r--  1 root root 2392 Jul  3 04:46 202007030446.log
-rw-r--r--  1 root root 1230 Jul  3 04:47 202007030447.log
-rw-r--r--  1 root root 2391 Jul  3 04:48 202007030448.log
-rw-r--r--  1 root root 1230 Jul  3 04:49 202007030449.log
-rw-r--r--  1 root root 2392 Jul  3 04:50 202007030450.log
-rw-r--r--  1 root root 1230 Jul  3 04:51 202007030451.log
-rw-r--r--  1 root root 2391 Jul  3 04:52 202007030452.log
-rw-r--r--  1 root root 1229 Jul  3 04:53 202007030453.log
-rw-r--r--  1 root root 2392 Jul  3 04:54 202007030454.log
-rw-r--r--  1 root root 1229 Jul  3 04:55 202007030455.log
-rw-r--r--  1 root root 2391 Jul  3 04:56 202007030456.log
-rw-r--r--  1 root root 1230 Jul  3 04:57 202007030457.log
-rw-r--r--  1 root root 2391 Jul  3 04:58 202007030458.log
-rw-r--r--  1 root root 1229 Jul  3 04:59 202007030459.log
-rw-r--r--  1 root root 2392 Jul  3 05:00 202007030500.log
-rw-r--r--  1 root root 1229 Jul  3 05:01 202007030501.log
-rw-r--r--  1 root root 2391 Jul  3 05:02 202007030502.log
-rw-r--r--  1 root root 4841 Jul  4 04:40 202007040440.log
-rw-r--r--  1 root root 1230 Jul  4 04:42 202007040442.log
-rw-r--r--  1 root root 1229 Jul  4 04:43 202007040443.log
-rw-r--r--  1 root root 2392 Jul  4 04:44 202007040444.log
-rw-r--r--  1 root root 1230 Jul  4 04:45 202007040445.log
-rw-r--r--  1 root root 2391 Jul  4 04:46 202007040446.log
-rw-r--r--  1 root root 1229 Jul  4 04:47 202007040447.log
-rw-r--r--  1 root root 2392 Jul  4 04:48 202007040448.log
-rw-r--r--  1 root root 1229 Jul  4 04:49 202007040449.log
-rw-r--r--  1 root root 2392 Jul  4 04:50 202007040450.log
-rw-r--r--  1 root root 1230 Jul  4 04:51 202007040451.log
-rw-r--r--  1 root root 2392 Jul  4 04:52 202007040452.log
-rw-r--r--  1 root root 1230 Jul  4 04:53 202007040453.log
-rw-r--r--  1 root root 2391 Jul  4 04:54 202007040454.log
-rw-r--r--  1 root root 1229 Jul  4 04:55 202007040455.log
-rw-r--r--  1 root root 2392 Jul  4 04:56 202007040456.log
-rw-r--r--  1 root root 1230 Jul  4 04:57 202007040457.log
-rw-r--r--  1 root root 2392 Jul  4 04:58 202007040458.log
-rw-r--r--  1 root root 1229 Jul  4 04:59 202007040459.log
-rw-r--r--  1 root root 2392 Jul  4 05:00 202007040500.log
-rw-r--r--  1 root root 1230 Jul  4 05:01 202007040501.log
-rw-r--r--  1 root root 2391 Jul  4 05:02 202007040502.log
```

So, I started poking at my cron jobs to see what was going on, and it looks like a misconfigured job, may be breaking networking for approximately 20 minutes. I have taken the steps to fix this issue and will see what happens after.

What is odd though is still ZT is not attempting to reconnect after the 20 minutes of downtime. ZT just stays stuck in offline until stopping for 10-15 seconds, then restarting the service. 

I was under the impression from the docs that ZT doesn't ever stop trying to reconnect I believe we may need some more robust connectivity checking options.

As I said before this machine, with the bad configuration was working fine and ZT reconnecting when possible, for months at a time, (even with the 20 mins network downtime, it was reconnecting after.)

Let me give it a few more days to see if the miscreant job is to blame, then we can figure out why ZT gives up on reconnecting even when network connectivity is restored.

**Comment by graphixillusion** [comment] 2020-07-06 17:35
I'm agree with @abclution : zerotier goes offline when it loses connection for whatever reason. When the connection is back, it stays offline until you stop and restart the service. In my case i need to stop it for about 10 min to make it works again.

**Comment by laduke** [comment] 2020-07-06 17:52
thanks for working on this. 

Hmm. My internet goes out a few times a day here, but this doesn't happen to me. 
How many cores and how much RAM do you all have on your machines that experience this? 
Where approximately are they located geographically? (I'm on a 16GB quad core mac in California)

**Comment by graphixillusion** [comment] 2020-07-06 18:54
@laduke, i have it running on a lattepanda alpha SBC with 8GB of ram and on a VM with 2GB or ram. It happens on a laptop with 4GB of ram too. Every machines with Windows 10.

**Comment by abclution** [comment] 2020-07-07 16:10
@laduke 

The machine encountering the issue is a  Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz with 32 gigabytes of ram. (Hetzner Dedicated server)

Hey so the problem has not happened again, so it was definitely caused by loosing internet access for those 20 minutes. The service that was causing the internet outage was a firewall virtual machine that the baremetal gets its internet through.

Now how do we debug this further.. I can probably reliably reproduce this error, should I email you the peers logs from the time period after it disconnects and doesn't try to reconnect?

**Comment by graphixillusion** [comment] 2020-07-07 17:22
I think that this issue has nothing to do with the amounts of ram in the system...

**Comment by laduke** [comment] 2020-07-07 18:36
We're able to reproduce this internally (sometimes) and are working on it. 

> I think that this issue has nothing to do with the amounts of ram in the system...
I think you are right.

**Comment by laduke** [comment] 2020-07-17 06:44
Hey, can anyone who ends up in the OFFLINE state send their `listpeers` output, collected while offline. 

What kind of router are your devices behind?

**Comment by graphixillusion** [comment] 2020-07-17 08:25
@laduke when OFFLINE listpeers output is like in this comment: https://github.com/zerotier/ZeroTierOne/issues/1214#issuecomment-640557587
I'm running a normal router, ISP branded

**Comment by laduke** [comment] 2020-07-17 14:56
Sorry. With the `-j` flag; it has more info.

**Comment by graphixillusion** [comment] 2020-07-19 19:05
@laduke here's my listtpeers -j output while offline:

```
[
 {
  "address": "xxxxxxxxxx",
  "latency": -1,
  "paths": [
   {
    "active": true,
    "address": "185.180.13.82/9993",
    "expired": false,
    "lastReceive": 1595101962420,
    "lastSend": 1595185181400,
    "preferred": false,
    "trustedPathId": 0
   }
  ],
  "role": "PLANET",
  "version": "-1.-1.-1",
  "versionMajor": -1,
  "versionMinor": -1,
  "versionRev": -1
 },
 {
  "address": "xxxxxxxxxx",
  "latency": -1,
  "paths": [
   {
    "active": true,
    "address": "50.7.252.138/9993",
    "expired": false,
    "lastReceive": 1595101962500,
    "lastSend": 1595185181400,
    "preferred": false,
    "trustedPathId": 0
   }
  ],
  "role": "PLANET",
  "version": "-1.-1.-1",
  "versionMajor": -1,
  "versionMinor": -1,
  "versionRev": -1
 },
 {
  "address": "xxxxxxxxxx",
  "latency": -1,
  "paths": [
   {
    "active": true,
    "address": "34.94.131.223/21008",
    "expired": false,
    "lastReceive": 1595185214840,
    "lastSend": 1595185214840,
    "preferred": true,
    "trustedPathId": 0
   }
  ],
  "role": "LEAF",
  "version": "1.4.6",
  "versionMajor": 1,
  "versionMinor": 4,
  "versionRev": 6
 },
 {
  "address": "xxxxxxxxxx",
  "latency": -1,
  "paths": [
   {
    "active": true,
    "address": "103.195.103.66/9993",
    "expired": false,
    "lastReceive": 1595101962312,
    "lastSend": 1595185181400,
    "preferred": false,
    "trustedPathId": 0
   }
  ],
  "role": "PLANET",
  "version": "-1.-1.-1",
  "versionMajor": -1,
  "versionMinor": -1,
  "versionRev": -1
 },
 {
  "address": "xxxxxxxxxx",
  "latency": -1,
  "paths": [
   {
    "active": true,
    "address": "195.181.173.159/9993",
    "expired": false,
    "lastReceive": 1595101962312,
    "lastSend": 1595185181400,
    "preferred": false,
    "trustedPathId": 0
   }
  ],
  "role": "PLANET",
  "version": "-1.-1.-1",
  "versionMajor": -1,
  "versionMinor": -1,
  "versionRev": -1
 },
 {
  "address": "xxxxxxxxxx",
  "latency": 7,
  "paths": [
   {
    "active": true,
    "address": "192.168.1.250/9993",
    "expired": false,
    "lastReceive": 1595185206356,
    "lastSend": 1595185206356,
    "preferred": true,
    "trustedPathId": 0
   }
  ],
  "role": "LEAF",
  "version": "1.4.6",
  "versionMajor": 1,
  "versionMinor": 4,
  "versionRev": 6
 }
]
```

**Comment by unquietwiki** [comment] 2020-08-12 02:09
#1186 might be related to this.

**Comment by graphixillusion** [comment] 2020-08-12 14:16
@unquietwiki in my case i get the OFFLINE status when the router losts the connection with the ISP: when the connection is re-established, zerotier will always stays at OFFLINE status until i stop the service for atlast 5mins and then start it again. Infact in my script file i have set a sleep time of 10 mins, just to be sure it will works good.

**Comment by unquietwiki** [comment] 2020-08-12 18:44
@graphixillusion what device and/or OS are you doing this on? That might help identify if its a particular package/distro issue.

**Comment by unquietwiki** [comment] 2020-08-12 19:38
@graphixillusion we're still looking into it; thank you for your patience. There may be a couple different things going on; I know @laduke is looking into some Windows client bugs, and there may be another issue I'm looking into.

**Comment by laduke** [comment] 2020-08-19 16:03
Is anyone experiencing using Allow Global / Full Tunnel Mode ?

**Comment by graphixillusion** [comment] 2020-08-19 18:56
@laduke In my case the only flag checked is "Allow Managed IP". "Allow Global IP" and "Allow Default Route" are both disabled.

**Comment by shellus** [comment] 2020-10-27 06:16
> I'm agree with @abclution : zerotier goes offline when it loses connection for whatever reason. When the connection is back, it stays offline until you stop and restart the service. In my case i need to stop it for about 10 min to make it works again.

+1

```bash
root@v-master:~# zerotier-cli info
200 info 6c23152a38 1.4.6 OFFLINE

root@v-master:~# curl baidu.com
<html>
<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
</html>

root@v-master:~# systemctl restart zerotier-one.service

root@v-master:~# zerotier-cli info
200 info 6c23152a38 1.4.6 ONLINE

```
I have to restart manually to be online

**Comment by bennytheshap** [comment] 2020-12-11 04:48
Experiencing the same issue here. Any prospects for a fix?

**Comment by ALTinners** [comment] 2021-03-03 22:27
@laduke Looking at something that seems like this issue on baremetal Ubuntu 16.04 machines. In our case - the machine that couldn't connect acts as a router - a largely identical machine connected right next to it (and connecting to the net via the first machine) can see planets just fine. 

Interesting was that for planets my machine could not contact - the numAliveLinks was negative. Is that ... possible? Or indicative of something overflowing?  

For the failing one
```
 {
  "address": "778cde7190",
  "bondingPolicy": -1039076096,
  "isBonded": false,
  "isHealthy": true,
  "latency": -1,
  "numAliveLinks": -1039072001,
  "numTotalLinks": 32764,
  "paths": [],
  "role": "PLANET",
  "version": "-1.-1.-1",
  "versionMajor": -1,
  "versionMinor": -1,
  "versionRev": -1
 },
```

For the happy one
```
 {
  "address": "778cde7190",
  "bondingPolicy": 0,
  "isBonded": false,
  "isHealthy": false,
  "latency": 275,
  "numAliveLinks": 0,
  "numTotalLinks": 0,
  "paths": [
   {
    "active": true,
    "address": "103.195.103.66/9993",
    "expired": false,
    "lastReceive": 1614810325487,
    "lastSend": 1614810325209,
    "preferred": true,
    "trustedPathId": 0
   }
  ],
  "role": "PLANET",
  "version": "-1.-1.-1",
  "versionMajor": -1,
  "versionMinor": -1,
  "versionRev": -1
 },
```

We are running this config in many places and have seen some nasty sporadic failures recently - ping me if there is any specific info that would help

**Comment by joseph-henry** [comment] 2021-03-03 23:36
@ALTinners Thanks for this clue. We definitely should not see overflows like this. We'll take a look and get back.

**Comment by ALTinners** [comment] 2021-03-04 00:02
@joseph-henry Is this likely to have been a recent introduction (ie: 1.6.2/4)? We have a fair few production machines that have been running zerotier since 1.2.12 and have not seen this issue before. We have development machines that we will keep at 1.6.4 but I'm thinking for safety that I need to downgrade the production ones.

**Comment by ALTinners** [comment] 2021-03-04 06:55
For reference with the case I've posted above - think this may have been related to duplicate keys or a key being transferred from one machine to another (in this case - 2x industrial PCs having hard disks swapped). I downgraded it to 1.2.12 - observed basically  the same bug (no `peers -j` in 1.2.12 - sorry) - then rerolled the cert with `zerotier-idtool` , reenrolled it and am now seeing the machine fairly happy. 

Obviously the overflow is still an issue :) but may not be a root cause of other peoples issues in this thread. I will update this post if I can confirm that this issue ends up still occurring

**Comment by joseph-henry** [comment] 2021-03-08 17:33
@ALTinners It's been four days now, how is 1.6.4 treating you? I still suspect something is broken in 1.6.4 but I'm curious how it's going for you.

**Comment by ALTinners** [comment] 2021-03-08 21:43
@joseph-henry Still collecting data. We have about ~10 machines now that should be running 1.6.4 is a variety of configurations and networking scenarios - we should be able to isolate some patterns soon. Any hints on what could cause the overflow cases would be greatly appreciated - right now we are casting a very wide (and slow) net

**Comment by joseph-henry** [comment] 2021-03-09 20:50
Additionally,

Here is another smaller fix to try on our `dev` branch: https://github.com/zerotier/ZeroTierOne/commit/353905394e79c54a4f479d722b74de8ea06a38b7

This fixes a potential interface binding issue that might be relevant. Please let us know if this helps.

**Comment by ALTinners** [comment] 2021-04-12 04:02
Found this issue recurring in a production context for my job - we found a few things that may help others diagnose their issues. 

In our case - we are running embedded devices - a Teltonika RUT240 4G modem (running an OpenWRT derivative) and the actual ZT device. Both power on at the same time. 

Our issue of not-having-planets came about due to a firmware bug on the router - `conntrack` state would persist despite a `MASQUERADE` rule having come into effect shortly after boot (and after ZT would have started) that would invalidate any existing state. 

Essentially - for a given planet (`195.181.173.159`) and our device on `192.168.51.10` - we saw entries in `/proc/net/nf_conntrack` on the router like
```
ipv4     2 udp      17 57 src=192.168.51.10 dst=195.181.173.159 sport=9993 dport=9993 packets=524 bytes=81149 [UNREPLIED] src=195.181.173.159 dst=192.168.51.10 sport=9993 dport=9993 packets=0 bytes=0 mark=0 use=2
```

And the packets from `51.1` would never hit the `POSTROUTING` chain in `iptables` and get forwarded. 

Running `echo f > /proc/net/nf_conntrack` (which is OpenWRT specific) then caused a flush. Almost immediately after - packets re-establish a route with the correct `MASQUERADE`ing and ZT springs to life. 

The 10min wait that some people have reported as working above is also explained by this - that would be the time it took (roughly) for this `conntrack` state to expire and drop. 

So - as is probably the case for a lot of ZT issues - look at your intermediate infrastructure if possible and see if you can ascertain what the state of the connection is. 

For the ZT developers - unsure on the ramifications here - but you could provide some defence against issues like this by re-randomising the ZT client's ports if the planets are unresponsive for a long enough period of time. Obviously not a total solution - but if there is no major risk there it could help with some other edge cases.

**Closed** 2021-06-08 17:40 UTC
Labels: bug, duplicate, management, networking & routing

**Comment by bennytheshap** [comment] 2021-06-08 18:40
@joseph-henry Has this issue been fixed?

**Comment by glimberg** [comment] 2021-06-08 18:43
@bennytheshap Read the post directly above yours.  We've found and can confirm that this issue is due to factors external to zerotier.

**Comment by bennytheshap** [comment] 2021-06-08 18:46
In that case, I wonder if there are multiple issues then... I have been experiencing this on "regular" linux, e.g. on raspbian on Pi and on Ubuntu server on an intel machine.

**Comment by glimberg** [comment] 2021-06-08 18:47
It is your router or some other external machine in the path that is blocking communication between your nodes & the roots.

**Comment by bennytheshap** [comment] 2021-06-08 18:49
In these cases, it seems like the only way to fix the issue is to kill Zerotier's state (rm -Rf /var/lib/zerotier...) and re-add it on the web portal. Given this, it seems fixable in the ZT client. So, I wonder: is there a way to make Zerotier retry whatever is failing?

**Comment by glimberg** [comment] 2021-06-08 18:53
The reason that the `rm -rf /var/lib/zerotier-one` works is that in the current & previous releases, the ports used is deterministic based on Node ID.  Removing that directory changes the ports being used.  See here for more info.  The problem is not ZeroTier.  it's something in the path between you & the roots and is likely your router.  See here for more info: https://discuss.zerotier.com/t/coma-bug-update/3138

**Comment by bennytheshap** [comment] 2021-06-08 20:12
Thanks, @glimberg. The network is out of my control, and it would be great if zerotier were able to work around network breakage (e.g. by changing ports).
