### ISSUE TITLE
Non-responsiveness after 24 hours behind symmetric NAT

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#146] opened 2015-01-30 16:11 UTC
When multiple zerotier nodes are behind a symmetric NAT, which accesses a zerotier node with a Public Routable Internet Address, zerotier service will not work after about 24hours and will need to be restarted via Windows Task Manager. Strange thing is that external public node can ping the internal Natted nodes, but the internal nodes can no longer ping to the external node. This means that RDP works from the external node to internal nodes behind NAT, but not the other way around, after between 24 hours or so.

The symmetric NAT is RouterOS from Mikrotik.
There is a single simple firewall forward rule that drops all connections that originate from the Internet interface. But it doesn't matter if this rule is enabled or disabled.

This is a major issue that is leading to great dissatisfaction from our user base.

**Comment by adamierymenko** [comment] 2015-01-30 18:09
A few questions:

Are the internal nodes running the normal Windows firewall? Any third party firewall or network security access control software (e.g. Symantec or McAfee)?

Would you mind taking one of the internal nodes and joining another ZeroTier network that I create temporarily for test purposes? I can then monitor the node myself and perhaps perform some remote network diagnostics when the issue resurfaces.

For future reference: http://wiki.mikrotik.com/wiki/MikroTik_RouterOS

**Comment by heri16** [comment] 2015-01-31 00:49
‎My existing network is created on the zerotier website. Would giving you my network id suffice? Or should I add another network id to one of the internal nodes, while keeping the existing too?

**Comment by adamierymenko** [comment] 2015-01-31 00:51
That is a good point. E-mail the network ID you want to use to adam.ierymenko@zerotier.com (instead of posting here) and I'm going to join it with dc3ab0788e -- a box where I have some diagnostic tools. Also include in the e-mail some of the internal IPs of some of the machines you have that are behind NAT (their virtual network IPs, not their "real" ones). I'm just going to set something up to ping them for now and see what the ping history looks like.

**Comment by adamierymenko** [comment] 2015-02-04 01:25
Was thinking about this a little more... Does your external IP address change frequently? Some ISPs reassign DHCP leases frequently.

If so, that might cause issues. Some work is underway to improve detection of external network circumstance changes.

**Comment by heri16** [comment] 2015-02-06 00:35
I don't think this is likely the reason as our public ip address is static

**Comment by adamierymenko** [comment] 2015-03-26 00:04
I believe this is related to #153

**Comment by adamierymenko** [comment] 2015-04-04 19:39
Closing -- duplicate of issue #153

**Closed by adamierymenko** 2015-04-04 19:39 UTC
Labels: bug
