### ISSUE TITLE
Reduce overhead traffic

### ISSUE THREAD

**Issue by ravz** [zerotier/ZeroTierOne#1174] opened 2020-04-01 07:25 UTC
**Is your feature request related to a problem? Please describe.**
We've found ZeroTier to be a great solution for our IoT gateway deployments. Our one issue however is the volume of additional traffic that's generated.

![image](https://user-images.githubusercontent.com/1230289/78109735-202f0180-743d-11ea-9f0e-974c54f91b48.png)

The above image is usage for 1 day. This may seem marginal but we use mobile networks for communication and the additional volume across all sites is becoming an issue.

**Describe the solution you'd like**
Some more options to allow reduced traffic. This may understandably result in reduced functionality but at least it allows the user to configure that for their scenario.

**Comment by glimberg** [comment] 2020-05-21 06:12
Duplicate of #1018

**Closed by glimberg** 2020-05-21 06:12 UTC
