### ISSUE TITLE
Alignment trap

### ISSUE THREAD

**Issue by ycxzfforever** [zerotier/ZeroTierOne#789] opened 2018-06-14 06:14 UTC
I recently cross-compiled a zerotier-one under the arm platform, the following issue appears，
“Alignment trap: zerotier-one (1058) PC=0x0001db0c Instr=0xe89c000f Address=0xbef19aca FSR 0x001“

**Comment by joseph-henry** [comment] 2018-06-14 23:46
Interesting. What specific architecture are you targeting? Also, can you build with `ZT_DEBUG=1` set and run a debugger against it?

**Comment by joseph-henry** [comment] 2018-10-03 22:17
Since we haven't received any further feedback on this issue and we have never reproduced this we will be closing this ticket. Feel free to request that it be re-opened. Thanks.

**Closed by joseph-henry** 2018-10-03 22:17 UTC
Labels: bug, cantreproduce, compatibility
