### ISSUE TITLE
Reduce ZeroTier "chattiness" when idle

### ISSUE THREAD

**Issue by nolanl** [zerotier/ZeroTierOne#1018] opened 2019-08-22 23:43 UTC
**Describe the bug**
On an idle network, Zerotier uses around 270 bytes/sec TX, 130 bytes/sec RX.

This is an problem for my use case because I want to use ZeroTier to connect to a raspberry pi acting as an out-of-band backup serial link via a cellular modem, and it ends up using 22MB of data per day.

There is an active but low bandwidth TCP connection between 2 other hosts on the same ZT network.

```
# tcpdump -l -n -i wwan0 > /tmp/wwan0 & tcpdump -l -n -i ztppiquz62 > /tmp/zt & sleep 60; killall tcpdump
# wc -l /tmp/wwan0 /tmp/zt
  234 /tmp/wwan0
    1 /tmp/zt
  235 total
# cat /tmp/zt

# cat /tmp/wwan0
00:22:18.256517 IP 71.19.155.206.9993 > 21.251.248.115.42390: UDP, length 321
00:22:18.312473 IP 35.236.47.35.32149 > 21.251.248.115.42390: UDP, length 28
00:22:18.369583 IP 21.251.248.115.42390 > 35.236.47.35.32149: UDP, length 37
00:22:19.749811 IP 21.251.248.115.9993 > 159.203.2.154.9993: UDP, length 137
00:22:19.749996 IP 21.251.248.115.42389 > 159.203.2.154.9993: UDP, length 137
00:22:19.750112 IP 21.251.248.115.42390 > 159.203.2.154.9993: UDP, length 137
00:22:19.750288 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:19.750402 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:19.750506 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:19.750679 IP 21.251.248.115.9993 > 159.203.97.171.9993: UDP, length 137
00:22:19.750784 IP 21.251.248.115.42389 > 159.203.97.171.9993: UDP, length 137
00:22:19.750886 IP 21.251.248.115.42390 > 159.203.97.171.9993: UDP, length 137
00:22:19.859822 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 59
00:22:19.859907 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 41
00:22:19.859935 IP 159.203.2.154.9993 > 21.251.248.115.42390: UDP, length 59
00:22:19.860011 IP 159.203.2.154.9993 > 21.251.248.115.42390: UDP, length 41
00:22:19.860036 IP 159.203.2.154.9993 > 21.251.248.115.42389: UDP, length 59
00:22:19.860058 IP 159.203.2.154.9993 > 21.251.248.115.42389: UDP, length 41
00:22:19.884698 IP 159.203.97.171.9993 > 21.251.248.115.42390: UDP, length 59
00:22:19.884758 IP 159.203.97.171.9993 > 21.251.248.115.42390: UDP, length 41
00:22:19.884781 IP 159.203.97.171.9993 > 21.251.248.115.9993: UDP, length 59
00:22:19.884803 IP 159.203.97.171.9993 > 21.251.248.115.9993: UDP, length 41
00:22:19.886162 IP 21.251.248.115.9993 > 107.170.197.14.9993: UDP, length 137
00:22:19.886891 IP 21.251.248.115.9993 > 159.203.97.171.9993: UDP, length 137
00:22:19.888160 IP 21.251.248.115.42390 > 107.170.197.14.9993: UDP, length 137
00:22:19.888823 IP 21.251.248.115.42390 > 159.203.97.171.9993: UDP, length 137
00:22:19.890452 IP 159.203.97.171.9993 > 21.251.248.115.42389: UDP, length 59
00:22:19.890513 IP 159.203.97.171.9993 > 21.251.248.115.42389: UDP, length 41
00:22:19.892052 IP 21.251.248.115.42389 > 107.170.197.14.9993: UDP, length 137
00:22:19.949378 IP 107.170.197.14.9993 > 21.251.248.115.9993: UDP, length 59
00:22:19.950361 IP 107.170.197.14.9993 > 21.251.248.115.42390: UDP, length 59
00:22:19.951334 IP 107.170.197.14.9993 > 21.251.248.115.42389: UDP, length 59
00:22:20.013490 IP 159.203.97.171.9993 > 21.251.248.115.42390: UDP, length 59
00:22:20.013539 IP 159.203.97.171.9993 > 21.251.248.115.42390: UDP, length 41
00:22:20.014862 IP 21.251.248.115.42390 > 107.170.197.14.9993: UDP, length 137
00:22:24.755586 IP 21.251.248.115.9993 > 46.101.160.249.9993: UDP, length 28
00:22:24.755835 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:24.755950 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:24.756053 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:24.756210 IP 21.251.248.115.42390 > 107.170.197.14.9993: UDP, length 28
00:22:24.976503 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 37
00:22:24.976588 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 41
00:22:29.761910 IP 21.251.248.115.42390 > 45.32.198.130.9993: UDP, length 28
00:22:29.762101 IP 21.251.248.115.42389 > 107.191.46.210.9993: UDP, length 28
00:22:29.762232 IP 21.251.248.115.42390 > 45.32.248.87.9993: UDP, length 28
00:22:29.762354 IP 21.251.248.115.42389 > 45.32.246.179.9993: UDP, length 28
00:22:29.762476 IP 21.251.248.115.42390 > 45.32.246.179.9993: UDP, length 28
00:22:29.762596 IP 21.251.248.115.9993 > 159.203.2.154.9993: UDP, length 28
00:22:29.762775 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:29.762881 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:29.762992 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:29.763168 IP 21.251.248.115.9993 > 188.166.94.177.9993: UDP, length 137
00:22:29.763273 IP 21.251.248.115.42389 > 188.166.94.177.9993: UDP, length 137
00:22:29.763374 IP 21.251.248.115.42390 > 188.166.94.177.9993: UDP, length 137
00:22:29.763697 IP 21.251.248.115.42390 > 35.236.47.35.32149: UDP, length 144
00:22:29.822602 IP 35.236.47.35.32149 > 21.251.248.115.42390: UDP, length 651
00:22:29.920562 IP 45.32.248.87.9993 > 21.251.248.115.42390: UDP, length 37
00:22:29.920663 IP 45.32.248.87.9993 > 21.251.248.115.42390: UDP, length 41
00:22:29.967475 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 37
00:22:29.967530 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 41
00:22:29.972450 IP 45.32.246.179.9993 > 21.251.248.115.42389: UDP, length 37
00:22:29.972510 IP 45.32.246.179.9993 > 21.251.248.115.42389: UDP, length 41
00:22:29.976403 IP 45.32.246.179.9993 > 21.251.248.115.42390: UDP, length 37
00:22:29.976447 IP 45.32.246.179.9993 > 21.251.248.115.42390: UDP, length 41
00:22:34.767763 IP 21.251.248.115.9993 > 46.101.160.249.9993: UDP, length 137
00:22:34.767936 IP 21.251.248.115.42389 > 46.101.160.249.9993: UDP, length 137
00:22:34.768047 IP 21.251.248.115.42390 > 46.101.160.249.9993: UDP, length 137
00:22:34.768226 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:34.768333 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:34.768434 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:34.768595 IP 21.251.248.115.9993 > 131.255.6.16.9993: UDP, length 137
00:22:34.768698 IP 21.251.248.115.42389 > 131.255.6.16.9993: UDP, length 137
00:22:34.768796 IP 21.251.248.115.42390 > 131.255.6.16.9993: UDP, length 137
00:22:34.841464 ARP, Request who-has 21.251.248.113 tell 21.251.248.115, length 28
00:22:34.842202 ARP, Reply 21.251.248.113 is-at 02:50:f3:00:00:00, length 28
00:22:34.976763 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 59
00:22:34.976838 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 41
00:22:34.976862 IP 46.101.160.249.9993 > 21.251.248.115.42389: UDP, length 59
00:22:34.976881 IP 46.101.160.249.9993 > 21.251.248.115.42389: UDP, length 41
00:22:34.976898 IP 46.101.160.249.9993 > 21.251.248.115.42390: UDP, length 59
00:22:34.976961 IP 46.101.160.249.9993 > 21.251.248.115.42390: UDP, length 41
00:22:38.416588 IP 71.19.155.206.9993 > 21.251.248.115.42390: UDP, length 321
00:22:39.776383 IP 21.251.248.115.9993 > 46.101.160.249.9993: UDP, length 28
00:22:39.776674 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:39.776796 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:39.776900 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:39.777067 IP 21.251.248.115.42390 > 107.170.197.14.9993: UDP, length 28
00:22:39.869389 IP 107.170.197.14.9993 > 21.251.248.115.42390: UDP, length 37
00:22:40.016479 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 37
00:22:40.016531 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 41
00:22:44.779867 IP 21.251.248.115.42390 > 45.32.198.130.9993: UDP, length 28
00:22:44.780066 IP 21.251.248.115.42389 > 107.191.46.210.9993: UDP, length 28
00:22:44.780199 IP 21.251.248.115.42390 > 45.32.248.87.9993: UDP, length 28
00:22:44.780325 IP 21.251.248.115.42389 > 45.32.246.179.9993: UDP, length 28
00:22:44.780536 IP 21.251.248.115.42390 > 45.32.246.179.9993: UDP, length 28
00:22:44.780670 IP 21.251.248.115.9993 > 159.203.2.154.9993: UDP, length 28
00:22:44.780857 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:44.780968 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:44.781072 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:44.781236 IP 21.251.248.115.9993 > 188.166.94.177.9993: UDP, length 137
00:22:44.781342 IP 21.251.248.115.42389 > 188.166.94.177.9993: UDP, length 137
00:22:44.781564 IP 21.251.248.115.42390 > 188.166.94.177.9993: UDP, length 137
00:22:44.893434 IP 45.32.198.130.9993 > 21.251.248.115.42390: UDP, length 37
00:22:44.919441 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 37
00:22:44.919505 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 41
00:22:44.957474 IP 45.32.248.87.9993 > 21.251.248.115.42390: UDP, length 37
00:22:44.957519 IP 45.32.248.87.9993 > 21.251.248.115.42390: UDP, length 41
00:22:44.982820 IP 188.166.94.177.9993 > 21.251.248.115.9993: UDP, length 59
00:22:44.982860 IP 188.166.94.177.9993 > 21.251.248.115.9993: UDP, length 41
00:22:44.982880 IP 188.166.94.177.9993 > 21.251.248.115.42389: UDP, length 59
00:22:44.982899 IP 188.166.94.177.9993 > 21.251.248.115.42389: UDP, length 41
00:22:44.984349 IP 21.251.248.115.9993 > 107.170.197.14.9993: UDP, length 137
00:22:44.985074 IP 21.251.248.115.9993 > 188.166.94.177.9993: UDP, length 137
00:22:44.986451 IP 188.166.94.177.9993 > 21.251.248.115.42390: UDP, length 59
00:22:44.986487 IP 188.166.94.177.9993 > 21.251.248.115.42390: UDP, length 41
00:22:44.986533 IP 21.251.248.115.42389 > 107.170.197.14.9993: UDP, length 137
00:22:44.987246 IP 21.251.248.115.42389 > 188.166.94.177.9993: UDP, length 137
00:22:44.988534 IP 21.251.248.115.42390 > 107.170.197.14.9993: UDP, length 137
00:22:44.994451 IP 45.32.246.179.9993 > 21.251.248.115.42389: UDP, length 37
00:22:44.994503 IP 45.32.246.179.9993 > 21.251.248.115.42389: UDP, length 41
00:22:44.998421 IP 45.32.246.179.9993 > 21.251.248.115.42390: UDP, length 37
00:22:44.998467 IP 45.32.246.179.9993 > 21.251.248.115.42390: UDP, length 41
00:22:45.009462 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 37
00:22:45.009521 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 41
00:22:48.337450 IP 35.236.47.35.32149 > 21.251.248.115.42390: UDP, length 28
00:22:48.337854 IP 21.251.248.115.42390 > 35.236.47.35.32149: UDP, length 37
00:22:49.786074 IP 21.251.248.115.9993 > 45.32.198.130.9993: UDP, length 137
00:22:49.786224 IP 21.251.248.115.42389 > 45.32.198.130.9993: UDP, length 137
00:22:49.786332 IP 21.251.248.115.42390 > 45.32.198.130.9993: UDP, length 137
00:22:49.786503 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:49.786606 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:49.786706 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:49.786869 IP 21.251.248.115.9993 > 159.203.97.171.9993: UDP, length 137
00:22:49.786986 IP 21.251.248.115.42389 > 159.203.97.171.9993: UDP, length 137
00:22:49.787198 IP 21.251.248.115.42390 > 159.203.97.171.9993: UDP, length 137
00:22:49.877693 IP 45.32.198.130.9993 > 21.251.248.115.42389: UDP, length 59
00:22:49.877767 IP 45.32.198.130.9993 > 21.251.248.115.42389: UDP, length 28
00:22:49.877839 IP 45.32.198.130.9993 > 21.251.248.115.9993: UDP, length 59
00:22:49.877862 IP 45.32.198.130.9993 > 21.251.248.115.42390: UDP, length 59
00:22:49.879370 IP 21.251.248.115.42389 > 45.32.198.130.9993: UDP, length 37
00:22:49.931459 IP 159.203.97.171.9993 > 21.251.248.115.9993: UDP, length 59
00:22:49.931523 IP 159.203.97.171.9993 > 21.251.248.115.9993: UDP, length 41
00:22:49.932879 IP 21.251.248.115.9993 > 107.170.197.14.9993: UDP, length 137
00:22:49.933576 IP 21.251.248.115.9993 > 159.203.97.171.9993: UDP, length 137
00:22:49.999400 IP 107.170.197.14.9993 > 21.251.248.115.9993: UDP, length 59
00:22:54.791759 IP 21.251.248.115.9993 > 46.101.160.249.9993: UDP, length 28
00:22:54.792006 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:54.792121 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:54.792222 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:54.792380 IP 21.251.248.115.9993 > 107.170.197.14.9993: UDP, length 28
00:22:54.888427 IP 107.170.197.14.9993 > 21.251.248.115.9993: UDP, length 37
00:22:54.979469 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 37
00:22:54.979525 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 41
00:22:59.798009 IP 21.251.248.115.42390 > 45.32.198.130.9993: UDP, length 28
00:22:59.798211 IP 21.251.248.115.42389 > 107.191.46.210.9993: UDP, length 28
00:22:59.798340 IP 21.251.248.115.42390 > 45.32.248.87.9993: UDP, length 28
00:22:59.798463 IP 21.251.248.115.42389 > 45.32.246.179.9993: UDP, length 28
00:22:59.798583 IP 21.251.248.115.42390 > 45.32.246.179.9993: UDP, length 28
00:22:59.798706 IP 21.251.248.115.9993 > 159.203.2.154.9993: UDP, length 28
00:22:59.798887 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:22:59.798993 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:22:59.799094 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:22:59.799255 IP 21.251.248.115.9993 > 128.199.197.217.9993: UDP, length 137
00:22:59.799360 IP 21.251.248.115.42389 > 128.199.197.217.9993: UDP, length 137
00:22:59.799459 IP 21.251.248.115.42390 > 128.199.197.217.9993: UDP, length 137
00:22:59.898433 IP 45.32.198.130.9993 > 21.251.248.115.42390: UDP, length 37
00:22:59.946516 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 37
00:22:59.946610 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 41
00:23:00.020483 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 37
00:23:00.020541 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 41
00:23:00.065797 IP 128.199.197.217.9993 > 21.251.248.115.9993: UDP, length 59
00:23:00.065839 IP 128.199.197.217.9993 > 21.251.248.115.9993: UDP, length 41
00:23:00.065861 IP 128.199.197.217.9993 > 21.251.248.115.42390: UDP, length 59
00:23:00.065880 IP 128.199.197.217.9993 > 21.251.248.115.42390: UDP, length 41
00:23:00.065943 IP 128.199.197.217.9993 > 21.251.248.115.42389: UDP, length 59
00:23:00.065969 IP 128.199.197.217.9993 > 21.251.248.115.42389: UDP, length 41
00:23:03.376486 IP 35.236.47.35.32149 > 21.251.248.115.42390: UDP, length 28
00:23:03.376811 IP 21.251.248.115.42390 > 35.236.47.35.32149: UDP, length 37
00:23:04.805001 IP 21.251.248.115.9993 > 107.191.46.210.9993: UDP, length 137
00:23:04.805157 IP 21.251.248.115.42389 > 107.191.46.210.9993: UDP, length 137
00:23:04.805265 IP 21.251.248.115.42390 > 107.191.46.210.9993: UDP, length 137
00:23:04.805440 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:23:04.805544 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:23:04.805646 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:23:04.805805 IP 21.251.248.115.9993 > 159.203.97.171.9993: UDP, length 137
00:23:04.805907 IP 21.251.248.115.42389 > 159.203.97.171.9993: UDP, length 137
00:23:04.805991 IP 21.251.248.115.42390 > 159.203.97.171.9993: UDP, length 137
00:23:04.841457 ARP, Request who-has 21.251.248.113 tell 21.251.248.115, length 28
00:23:04.842529 ARP, Reply 21.251.248.113 is-at 02:50:f3:00:00:00, length 28
00:23:04.938487 IP 159.203.97.171.9993 > 21.251.248.115.9993: UDP, length 59
00:23:04.938577 IP 159.203.97.171.9993 > 21.251.248.115.9993: UDP, length 41
00:23:04.939400 IP 159.203.97.171.9993 > 21.251.248.115.42390: UDP, length 59
00:23:04.939445 IP 159.203.97.171.9993 > 21.251.248.115.42390: UDP, length 41
00:23:04.945459 IP 159.203.97.171.9993 > 21.251.248.115.42389: UDP, length 59
00:23:04.945513 IP 159.203.97.171.9993 > 21.251.248.115.42389: UDP, length 41
00:23:05.003459 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 59
00:23:05.003513 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 41
00:23:05.012460 IP 107.191.46.210.9993 > 21.251.248.115.42390: UDP, length 59
00:23:05.012503 IP 107.191.46.210.9993 > 21.251.248.115.42390: UDP, length 41
00:23:05.019454 IP 107.191.46.210.9993 > 21.251.248.115.9993: UDP, length 59
00:23:05.019505 IP 107.191.46.210.9993 > 21.251.248.115.9993: UDP, length 41
00:23:09.813598 IP 21.251.248.115.9993 > 46.101.160.249.9993: UDP, length 28
00:23:09.813875 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:23:09.813996 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:23:09.814103 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:23:09.814264 IP 21.251.248.115.9993 > 107.170.197.14.9993: UDP, length 28
00:23:09.893439 IP 107.170.197.14.9993 > 21.251.248.115.9993: UDP, length 37
00:23:10.096501 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 37
00:23:10.096575 IP 46.101.160.249.9993 > 21.251.248.115.9993: UDP, length 41
00:23:14.817048 IP 21.251.248.115.42390 > 45.32.198.130.9993: UDP, length 28
00:23:14.817237 IP 21.251.248.115.42389 > 107.191.46.210.9993: UDP, length 28
00:23:14.817367 IP 21.251.248.115.42390 > 45.32.248.87.9993: UDP, length 28
00:23:14.817491 IP 21.251.248.115.42389 > 45.32.246.179.9993: UDP, length 28
00:23:14.817614 IP 21.251.248.115.42390 > 45.32.246.179.9993: UDP, length 28
00:23:14.817736 IP 21.251.248.115.9993 > 159.203.2.154.9993: UDP, length 28
00:23:14.817916 IP 21.251.248.115.9993 > 185.180.13.82.9993: UDP, length 137
00:23:14.818023 IP 21.251.248.115.42389 > 185.180.13.82.9993: UDP, length 137
00:23:14.818124 IP 21.251.248.115.42390 > 185.180.13.82.9993: UDP, length 137
00:23:14.818286 IP 21.251.248.115.9993 > 107.170.197.14.9993: UDP, length 137
00:23:14.818374 IP 21.251.248.115.42389 > 107.170.197.14.9993: UDP, length 137
00:23:14.818485 IP 21.251.248.115.42390 > 107.170.197.14.9993: UDP, length 137
00:23:14.896504 IP 107.170.197.14.9993 > 21.251.248.115.9993: UDP, length 59
00:23:14.896587 IP 107.170.197.14.9993 > 21.251.248.115.42389: UDP, length 59
00:23:14.897403 IP 107.170.197.14.9993 > 21.251.248.115.42390: UDP, length 59
00:23:14.910360 IP 45.32.198.130.9993 > 21.251.248.115.42390: UDP, length 37
00:23:14.929418 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 37
00:23:14.929464 IP 159.203.2.154.9993 > 21.251.248.115.9993: UDP, length 41
00:23:15.024453 IP 45.32.246.179.9993 > 21.251.248.115.42389: UDP, length 37
00:23:15.024519 IP 45.32.246.179.9993 > 21.251.248.115.42389: UDP, length 41
00:23:15.028470 IP 45.32.246.179.9993 > 21.251.248.115.42390: UDP, length 37
00:23:15.028514 IP 45.32.246.179.9993 > 21.251.248.115.42390: UDP, length 41
00:23:15.075467 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 37
00:23:15.075511 IP 107.191.46.210.9993 > 21.251.248.115.42389: UDP, length 41
# zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks XXXXXXXXXXXXXXX internalnet c6:12:a7:dc:31:96 OK PRIVATE ztppiquz62 192.168.192.10/24
root@raspberrypi:/home/nolan# zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 3a46f1bf30 - -1 - PLANET
200 listpeers 8841408a2e 45.32.198.130/9993;7458;7318 108 1.1.5 PLANET
200 listpeers 9d219039f3 107.170.197.14/9993;2453;2374 59 1.1.5 PLANET
200 listpeers XXXXXXXX 1.2.3.4/9993;27486;4211 -1 1.2.4 LEAF
200 listpeers XXXXXXXX 35.236.47.35/32149;3891;3891 -1 1.4.1 LEAF
```
**Desktop:**
 - OS: Linux
 - OS/Distribution Version: Raspbian Buster
 - ZeroTier Version: 1.4.2-2
 - Hardware: raspberry pi 2

**Comment by laduke** [comment] 2019-08-22 23:49
see #867

**Comment by wscott** [comment] 2019-09-09 11:24
So these are keep-alives between peers and not updating the root servers?  I was wondering if a local moon would help.

**Comment by joseph-henry** [comment] 2020-06-25 01:06
Closing due to age and duplicate discussions. We are still considering strategies for reducing ambient traffic but have not reached a conclusion yet. See aforementioned tickets for more up-to-date info.

**Closed by joseph-henry** 2020-06-25 01:06 UTC
Labels: performance

**Comment by bojanpotocnik** [comment] 2021-09-06 19:11
> See aforementioned tickets for more up-to-date info.

This issue mentions #1174, which is closed as a duplicate of this one, and #867 which promised improvements in 1.4.0, but this issue is still very much present. Maybe it would be nice to pick a specific ticket, leave it open, and mark all others as duplicate of it.

> This is being improved in the 2.x line (currently the edge branch), but as of today don't even try to run that branch.

Is 2.x line getting stable enough to be used?

**Comment by jortorri** [comment] 2022-10-04 13:34
Any news? With version 1.6.5 the data consumption is huge yet. I get almost 2GB/month, only zerotier consumption.

**Comment by bam80** [comment] 2022-10-04 14:18
Kind of "solution" might be switching to https://tailscale.com/ instead

**Comment by bam80** [comment] 2022-10-04 16:30
I don't have a reference right now and didn't test for myself, but IIRC it was established Tailscale is a way less chatty, so definitely worth to try.
