### ISSUE TITLE
Accessing zerotier machine from LAN 

### ISSUE THREAD

**Issue by samuelxhu** [zerotier/ZeroTierOne#1666] opened 2022-05-11 07:08 UTC
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Docs Site](https://docs.zerotier.com/zerotier/troubleshooting) => Troubleshooting, quickstarts, and more advanced topics.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.
- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Older wiki.

If you are having a connection issue, it's much easier to diagnose through the discussion forum or the ticket system. 

# If you still want to file a Bug Report

## Please let us know

- What you expect to be happening.
- What is actually happening?
- Any steps to reproduce the error.
- Any relevant console output or screenshots.
- What operating system and ZeroTier version. Please try the latest ZeroTier release. 

Actually this is a question, instead of a bug or issue. Sorry if this bothers anybody...

In a homelab enviroment, i set up a NAS machine with zerotier installed and get a zerotier network address in 10.x.x.x, and my home lan address is 192.168.1.x.  I am asking, if i transfer data from 192.168.1.x to NAS machine using IP address 10.x.x.x, will the traffic directly go inside the LAN, or have to get out of my home rounter and come back again?

thanks a lot in advance for feedback

**Comment by 3freet** [comment] 2022-05-11 18:37
The first few packets might go through your router out to the internet, but might not even reach back before your computer establish a direct local connection to your NAS. You can test this with wireshark, or simply observing the latency between devices.

You can read more here: https://www.zerotier.com/2014/08/25/the-state-of-nat-traversal/  on _"The Same Network Problem"_ Section

**Comment by laduke** [comment] 2022-05-11 20:21
Yup! 
You can check `zerotier-cli peers`  also. 
Closing because not a bug. Keep chatting if you like.

**Closed by laduke** 2022-05-11 20:21 UTC
