### ISSUE TITLE
Waiting for identity generation

### ISSUE THREAD

**Issue by zhonger** [zerotier/ZeroTierOne#367] opened 2016-07-25 01:26 UTC
When I update ZT 1.1.4 to 1.1.14 in Ubuntu 14.04, I use "curl -s https://install.zerotier.com | sudo bash" command.But when it comes 'Waiting for identity generation', it will remain and report a problem to system.
![_003](https://cloud.githubusercontent.com/assets/12064158/17088141/d2aa95e6-5249-11e6-9b8b-93f889984e37.png)

**Comment by adamierymenko** [comment] 2016-07-25 15:34
The service is probably not running... it could be an issue upgrading from the old package.

Hit CTRL+C and try manually restarting it:

    service zerotier-one restart

**Comment by adamierymenko** [comment] 2016-07-25 15:47
Turns out this is a duplicate of #355 -- will try this ourselves and should be able to fix the installer script.

**Closed by adamierymenko** 2016-07-25 15:47 UTC
Labels: question

**Comment by mystica555** [comment] 2023-11-19 12:33
Necrobumping this bug in 2023 because on Debian 12 libssl1.1 isn't installed by default, the .deb doesn't have it as a dependency, the service fails to start (and systemctl doesnt realize this and error(should it?)) and the installer hangs in the while loop waiting for the identity file to be created by the service.

The deb needs to depend on libssl1.1, or, modify the installer script to not only install gpg, but also libssl1.1
