### ISSUE TITLE
Invalid JSON on Crontroller API crashes application

### ISSUE THREAD

**Issue by wendelb** [zerotier/ZeroTierOne#1003] opened 2019-08-12 17:28 UTC
**Describe the bug**
When POSTing invalid JSON to the Controller API, the zerotier-one process crashes with a SEGV

**To Reproduce**

Send an invalid JSON request to the Create Network API Endpoint:
`curl -H "X-ZT1-Auth: <secret>" -d '{""}' http://localhost:9993/controller/network/<YOUR-ID>______`

The System Journal shows the following entries:

```
systemd[1]: zerotier-one.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: zerotier-one.service: Unit entered failed state.
systemd[1]: zerotier-one.service: Failed with result 'signal'.
```

The `zerotier-one`application is thereafter restarted by systemd which can be seen in the output of `systemctl status zerotier-one.service`

**Expected behavior**
There should be a way to handle the situation more gracefully. Currently the program just crashes with a Segmentation Fault. An error message would be nice, though

**Environment:**
 - Raspberry Pi 2
 - OS: Raspbian GNU/Linux 9.9 (stretch)
 - ZeroTier Version 1.4.0

**Comment by adamierymenko** [comment] 2019-09-04 19:50
Closing for now since I think this is actually a dupe of #1017

**Closed** 2019-09-04 19:57 UTC
Labels: bug
