### ISSUE TITLE
libzerotiercore build process can be better

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#857] opened 2018-09-23 17:21 UTC
Thanks for providing a CMakeLists.txt to build libzerotiercore.

This can be improved, as it's still difficult to use this as an "imported" external project.

The CMakeLists should list the ZeroTierOne.h header (to be completely honest I wish we delivered this as zerotiercore.h -- to match the library name).

A cmake config file should be generated as well, so that this package could be found with FindPackage() in cmake dependency packages.

The header and the static library should actually be delivered.

Also, it would probably be helpful to some projects if the library was built shared sometimes.  This would even be better if libzerotiercore was distributable under the terms of the LGPL.  (I still lament the choice of GPL, which makes inclusion in 3rd party open source projects that want to use other license terms like Apache impossible - I wish the core were available under a more liberal license, but I realize that's out of scope here.)

I am willing to spend some effort to improve the CMakeLists package and generate a PR, or possibly create a new repo that does all of the above (except licensing of course!) using your project as a git submodule.  I would appreciate guidance as to which direction we should take though.

(@janjaapbos This affects the NNG ZeroTier transport.)

**Comment by gdamore** [comment] 2018-09-24 02:00
For an initial swag at this, please have a look here:

https://github.com/staysail/libzerotiercore

I will probably wind up using the above project, which is mostly build machinery on top of ZeroTierCore, for my own projects.

I would be happy to have ZeroTier just take that repo and use it directly.

**Comment by adamierymenko** [comment] 2018-09-25 20:55
I'm going to mark this a duplicate of #596 -- we will take a look at that repo.

**Closed by adamierymenko** 2018-09-25 20:55 UTC
Labels: backlog
