### ISSUE TITLE
segfault on armhf when trustedPathId defined in local.conf

### ISSUE THREAD

**Issue by pigmej** [zerotier/ZeroTierOne#944] opened 2019-04-30 23:06 UTC
Given the config file (local.conf):
```
{
        "physical": {
                "192.168.4.0/24": {
                        "trustedPathId": 117
                }
        }
}
```
`zerotier-one` v1.2.12 will segfault on armhf on Linux (Debian stretch/Armbian). Same config, same version works fine on x86 though.

**Comment by adamierymenko** [comment] 2019-05-01 16:15
Alignment issue for sure. Will fix as 1.4 heads for the door.

**Comment by pigmej** [comment] 2019-05-02 22:17
@adamierymenko  not that I'm pushing etc but any ETA ? :)  (sorry not familiar with release cycle yet)

**Comment by gy6221** [comment] 2019-05-25 09:14
Just tried on my armbian devices, and i found that this issue is not only happens when setting trusted path, but also happens when setting blacklist on physical paths. Also, I'm looking forward to the new features for 1.4.0. This is not a pushing but is there any roll out plan for 1.4.0? Thanks.

**Comment by adamierymenko** [comment] 2019-06-11 16:54
Will have to test this. Searched the code and didn't find any spots where trusted path was subjected to any "type punning" or aggressive casting, which so far has been what has caused these kinds of bugs.

**Comment by adamierymenko** [comment] 2019-06-11 16:56
Okay so the only conceivable place I can find is:

````
	template<typename T>
	inline T at(unsigned int i) const
	{
		if (unlikely((i + sizeof(T)) > _l))
			throw ZT_EXCEPTION_OUT_OF_BOUNDS;
#ifdef ZT_NO_TYPE_PUNNING
		T v = 0;
		const uint8_t *p = reinterpret_cast<const uint8_t *>(_b + i);
		for(unsigned int x=0;x<sizeof(T);++x) {
			v <<= 8;
			v |= (T)*(p++);
		}
		return v;
#else
		const T *const ZT_VAR_MAY_ALIAS p = reinterpret_cast<const T *>(_b + i);
		return Utils::ntoh(*p);
#endif
	}
````

Will have to investigate more since that macro should always be defined on everything but x86 and x64.

**Comment by adamierymenko** [comment] 2019-06-11 17:05
Found some suspect code in the JSON library we use and updated it to the latest version. It's possible that this will resolve.

**Comment by adamierymenko** [comment] 2019-06-19 19:29
Can you post `/proc/cpuinfo` from this device so I can see its exact CPU make/model/stepping?

**Comment by gy6221** [comment] 2019-06-20 06:34
`processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 50.52
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 50.52
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 4

Hardware	: Allwinner sun7i (A20) Family
Revision	: 0000
Serial		: 165166580502ae79
`
Please see the above info.

**Comment by halfpast3** [comment] 2019-06-23 15:20
I’ve got the same issue by different generation processor. Here is my CPU info:

cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 3.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

processor       : 1
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 3.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

processor       : 2
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 3.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

processor       : 3
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 3.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

Hardware        : Freescale i.MX6 Quad/DualLite (Device Tree)
Revision        : 0000
Serial          : 0000000000000000

**Comment by adamierymenko** [comment] 2019-09-04 20:03
This may be a duplicate of #1003 and #1017

**Comment by adamierymenko** [comment] 2019-09-04 20:04
We are going back to our static builds for `armhf` and have also done a few things in compiler flags that may help, but this is a weird issue. Apparently exceptions in C++ sometimes crash `armhf` binaries built on *some* compilers.

**Comment by adamierymenko** [comment] 2019-09-04 20:04
Closing but may re-open

**Closed by adamierymenko** 2019-09-04 20:04 UTC
Labels: bug
