### ISSUE TITLE
Huge Memory Leak

### ISSUE THREAD

**Issue by gabefair** [zerotier/ZeroTierOne#1351] opened 2021-02-15 00:43 UTC
## Required

- What is actually happening?
  -  ZeroTier has a memory leak that consumes all Swap RAM until disk is full.
- Any steps to reproduce the error.
  - Download and clean Install ZeroTierOne for Windows but do not login to any accounts.
  - Just let it run minimized in the taskbar for 3 days.
  - Do not restart or shutdown your windows computer. Just let ZeroTier run.
- Screenshot
![image](https://user-images.githubusercontent.com/2096785/107893839-6bd68680-6efb-11eb-8ea1-323d6a9e2b66.png)

## Additional information 

**Desktop (please complete the following information):**
 - OS: Windows 10 pro x64 (20H2) [Build 10.0.19042.804] 
 - ZeroTier Version: 1.6.3
  

**Additional context**
- ZeroTier Network Configuration: None. Not configured or logged in.

**Comment by adamierymenko** [comment] 2021-02-17 16:38
We'll see if we can reproduce this. In the meantime are you doing any of the following?

 * Bridging
 * Sending a lot of multicast traffic
 * Using non-IP protocols like IPX (e.g. for old games)

Thanks.

**Comment by gabefair** [comment] 2021-02-21 15:23
I had not logged into or configured zerotier. I just had installed it and forgot about it.

But on this computer I was:
1) Using Tailscale
2) Using Teamviewer
3) Using RDP
4) Using VMWare Player

**Comment by justledbetter** [comment] 2021-03-03 05:11
I've been experiencing this same issue since 1.6.0 - The service randomly spins up to 100% of CPU and consumes gigs of virtual memory; On a mix of Windows Server 2012R2, Hyper-V Server 2016, and Hyper-V Server 2019.

**Comment by justledbetter** [comment] 2021-03-10 02:28
I don't believe it happens with no-networks joined - and I think it may stop happening if IPv6 is disabled on the Windows host.  (I've only run into this on my production network and have not had the spare machines to try and experiment with it, sorry!)

**Comment by riaqn** [comment] 2021-05-09 17:32
This happending to me on linux 5.12.1. Zerotier version 1.6.5. 
Consumes 100% CPU and all memory until getting killed by OOM killer.

**Comment by jonathonf** [comment] 2021-05-19 10:32
If it's happening under Linux (and I've started seeing OOM logs on a node that has been running without other issues for a few years now) then it might be related to https://github.com/zerotier/ZeroTierOne/issues/1318 ?

**Comment by danmanners** [comment] 2021-06-28 01:00
I'm seeing this too with Zerotier v1.6.5 on Ubuntu 20.04 in both Digital Ocean and Google Cloud. Over the course of ~35 minutes or so it grows up to the full 4GiB memory of the host and then causes it to hang.

**Comment by laduke** [comment] 2021-06-28 18:30
@danmanners  Anything else installed on those instances other than what comes default? Would love to be able to reproduce this.

**Comment by joseph-henry** [comment] 2022-04-12 04:43
Is this still an active issue for anyone or can we close this ticket?

**Closed** 2022-04-26 16:41 UTC
Labels: bug, Windows

**Comment by germanalca** [comment] 2023-03-29 21:03
> He estado experimentando este mismo problema desde 1.6.0: el servicio gira aleatoriamente hasta el 100% de la CPU y consume gigas de memoria virtual; En una combinación de Windows Server 2012R2, Hyper-V Server 2016 y Hyper-V Server 2019. La única solución viable que he encontrado es degradar todos los servidores de Windows a 1.4.6. (Acabo de volver a probar con 1.6.4 y todavía está sucediendo, pero no tan inmediatamente como lo fue 1.6.0).

Hello, any solution?? I have same problem. Thanks.

**Comment by germanalca** [comment] 2023-03-29 22:06
> @germanalca In order to help you we need to know more details about (your) specific case. Can you open a new ticket and provide the information it asks for? Thanks.

On a Windows server 2012 with Hiper-v, I have mounted another with server 2016, I have installed the zerotier, but at the moment the use of ram collapses. In the same zerotier network there are other computers and without problems, only in the hyper--v server. I have tried several versions but with all of them it happens.

**Comment by gabefair** [comment] 2023-03-30 13:58
I gave up on using ZeroTier. Just use Tailscale now. Much smaller footprint.
