### ISSUE TITLE
Better documentation of controller

### ISSUE THREAD

**Issue by the-maldridge** [zerotier/ZeroTierOne#350] opened 2016-07-07 06:19 UTC
Currently there seems to be instructions for building with support for a node to be a controller, but the mentioned interface for actually controlling the controller seems to have vanished.  If this is still a feature that exists it would be nice to have it documented somewhere.

**Comment by fkooman** [comment] 2016-07-07 08:36
See also #344.

**Comment by adamierymenko** [comment] 2016-07-07 16:14
Closing as duplicate of #344

We're probably going to do a 1.1.6-2 tag with a very minor fix to the controller ( #343 ) and better docs. There have also been fixes/improvements to linux-build-farm.

No need to re-release all binary packages or bump the version for that since it only affects the controller (which must be built from source anyway right now) and docs in the repo.

**Closed by adamierymenko** 2016-07-07 16:14 UTC
