### ISSUE TITLE
Faster IP assignments

### ISSUE THREAD

**Issue by roman-cnd** [zerotier/ZeroTierOne#695] opened 2018-03-14 20:48 UTC
Hi,

We're testing zt and noticed that it takes a long time (sometimes > 1 min) for the client to get IP (after authorization). IP is needed to bootstrap virtual machines properly.

Before starting to look into DHCP servers, I wanted to ask about possible optimizations to have IPs assigned faster?

Thanks!
Roman

**Comment by joseph-henry** [comment] 2018-03-14 20:54
Hello, 

We are actually looking into this. It's on our wishlist as well. No definite timeframe on this but we will probably start looking into it after our next release.

**Comment by adamierymenko** [comment] 2018-03-29 17:56
Basically a dupe of #677

**Closed by adamierymenko** 2018-03-29 17:56 UTC
