### ISSUE TITLE
Broken MTU Segmentation when using Routing?

### ISSUE THREAD

**Issue by sheggy012** [zerotier/ZeroTierOne#1133] opened 2020-01-29 10:09 UTC
Hello, everybody,
i have the problem that when using routes the tunnel breaks away when i copy larger data (SMB). Single ping packets are no problem. The same setup with Tinc as side-to-side VPN on the same 2 VMS runs without problems.  I suspect it has something to do with a wrong MTU or segmentation, but I can't find any way to tell how full the packets should be packed. The WAN port on one side is a Dual Stack Lite" port. The MTU of 2800 is a virtual MTU for the VPN network. How can the physical MTU be set? 

Following structure:
`192.168.2.10/24(Client) --- Eth0 1500MTU (Zertotier VM) ztr2qs5lgf 2800MTU --- 192.168.200.1/24(VPN) --- (WAN Network) --- 192.168.200.2/24(VPN) ztr2qs5lgf 2800MTU (Zertotier VM)  Eth0 1500MTU --- 192.168.1.50/24(SMB-Server)`

This ist how the Routing Table looks like on VM1:

default via 192.168.2.1 dev eth0 proto dhcp src 192.168.2.5 metric 1024
192.168.1.0/24 via 192.168.200.2 dev ztr2qs5lgf
192.168.2.0/24 dev eth0 proto kernel scope link src 192.168.2.5
192.168.2.1 dev eth0 proto dhcp scope link src 192.168.2.5 metric 1024
192.168.200.0/24 dev ztr2qs5lgf proto kernel scope link src 192.168.200.1

If I equip the SMB server and my Client with a Zerotier Client and I use this VPN address to contact the server, the connection works without problems. So everything should work with the actual VPN connection.

**Comment by sheggy012** [comment] 2020-01-30 08:02
Okay what I found out so far, the routing works fine. There seems to be also no problem with the MTU. The problem is that the CPU shoots directly to 100% and disconnects all connections. I suspect it's a duplicate of #779 .

**Comment by adamierymenko** [comment] 2020-02-05 17:16
This is indeed a duplicate of an existing bug and should be fixed in 2.x, closing

**Closed by adamierymenko** 2020-02-05 17:16 UTC
