### ISSUE TITLE
Android Connection Problems

### ISSUE THREAD

**Issue by AsumYT** [zerotier/ZeroTierOne#855] opened 2018-09-18 19:08 UTC
**Alternative, faster ways to get help**
If you have just started using ZeroTier, here are some places to get help:
- my.zerotier.com has a _Community_ tab. It's a live chat with other users and the developers. 
- [ZeroTier Knowledge Base](https://support.zerotier.com/knowledgebase.php?s=MQ__)
- www.zerotier.com has a Contact Us button
- email contact@zerotier.com

**Describe the bug**
When i try to connect to a Network, it's not working mostly. At the Bottom i can see "ONLINE", but it's not connected to the VPN. I must try 9-10 times before it's working.

**To Reproduce**
1. Connect to a network with the phone
2. In 60% of the cases, you are not connected and you cannot see the VPN Key in the Notification Bar

**Expected behavior**
I will connect to the network without these bug.
 
**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S6]
 - OS: [Android]
 - ZeroTier Version: [1.2.12]
 - Version [7.0 Nougat]

**Additional context**
- ZeroTier Network Configuration
    * IPv4 Network, no IPv6 because my ethernet at home doesn't support this
    * Public Network
    * Enabled Broadcast
    * Standard/Uncustomized Flow Rules
- Firewall Config (try turning the firewall off)
    * No Firewall on Android Devices
- General Network Environment: [ e.g Home, University Campus, Corporate LAN ]
    * Home
    * Cellular (With enabled Use Cellular Option in the App)

**Comment by adamierymenko** [comment] 2018-09-19 17:46
We'd need more info about the network environment. We use Android all the time and it works fine, but things like routers/firewalls or policies imposed by wireless ISPs can make a difference.

**Comment by AsumYT** [comment] 2018-09-27 15:59
I have an Android Device with Cellular Data and an Raspberry Pi 3 with Raspbian as operating System. The Raspberry Pi is behind an Carrier-Grade NAT. On both Devices and the Router the Firewall is turned off. Zerotier and the Raspberry Pi is working fine, because when i'm connect through a PC to the Pi through the Zerotier Network, it works fine. But when i use my Android Device, i must try 9-10 times before it is working.

I hope i can help to reproduce the problem.

Regards.
PS: Sorry for bad English, i come from Germany.

**Comment by drfruct** [comment] 2018-10-30 16:23
Same in my case .On the bottom line the status changes to ONLINE, but the connection does not occur. If I open the connection details, the status line endlessly shows the REQUESTING CONFIGURATION.

* OS: [Android]
* ZeroTier Version: [1.2.12-2]
* Device: [OnePlus 6]
* Version: [OxygenOS 9.0 (Android 9)]

**Comment by glimberg** [comment] 2018-10-30 16:34
@drfruct Have you authorized your android device on the network on https://my.zerotier.com?  If not it'll stay at requesting configuration for a while before transitioning to ACCESS DENIED.

**Comment by AsumYT** [comment] 2018-10-30 17:08
Yes, i have authorized it.

**Comment by justusiv** [comment] 2018-11-19 19:58
I'm sure this is a duplicate of https://github.com/zerotier/ZeroTierOne/issues/781 however i will chime in i am also effected by this, using a galaxy note 9 on the Verizon network. it works sometimes other times the key never shows up.

**Comment by AsumYT** [comment] 2018-11-21 15:50
Yes, this is the same problem. But i have this problem on Cellular **and** WIFI. But i don't know, what i can do to fix this.

**Closed** 2019-02-01 15:03 UTC
Labels: cantreproduce

**Comment by epatels** [comment] 2019-04-03 09:54
I too am facing the same issue on my Redmi Note 5 Pro
On the phone Status Bar I can see VPN badge.
I have not installed any other VPN

I have authorised the device on ZeroTier Central. I can also see the ipaddress assigned to my phone.
But when I ping the phone from my PC, I get Request timed out.

My phone does not show the IP Address assigned to it by Zero Tier. It only show the global IP address.

Can someone please suggest a solution to this?
Thanks in advance.

**Comment by qingfengshi** [comment] 2019-12-16 06:26
I face the same problem too.
After I press the connect button, there is  not VPN connection sign on the phone status bar. My phone is not connected to the VPN network. However, the status at the bottom of the software interface shows "ONLINE".
At the same, I cannot find my Android device on the network on https://my.zerotier.com

**Comment by cookins** [comment] 2021-03-08 16:19
Same thing on Lenovo Tab 2 - by cellular, shown and auth in clients list, but device can't see software as vpn (no vpn icon in bar).

**Comment by andrewlytvyn** [comment] 2022-01-06 20:00
Poco x3pro cellular data works fine, on wifi show conected but no ping and other data(

**Comment by LoginByCall** [comment] 2024-10-10 19:35
When I connect with my Android smartphone from any Wi-Fi network - everything works.
When I connect through the GSM network - it says "online", but there is no ping to the nodes in my VPN network.

Hypothesis: GSM operator blocks port 9993.
Suggestion: add the ability to use any port, even 443.

Device: [Samsung SM-G965F]
OS: [Android 10]
ZeroTier Version: [1.14.0-2]
