### ISSUE TITLE
peer discovery status

### ISSUE THREAD

**Issue by ort163** [zerotier/ZeroTierOne#924] opened 2019-03-02 11:25 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I am unsure if all the peers are ready (and reachable). This will be of immense help to fix problems of nodes.

**Describe the solution you'd like**

When running `zerotier-cli status` it can output:
```
15 out of 40 peers online
10 out of 40 peers are direct
```

When running `zerotier-cli listplanets` it can output:
`5 out of 15 reachable`

**Describe alternatives you've considered**

May be parse the json output from https://github.com/zerotier/ZeroTierOne/issues/919

**Additional context**

Alternatively, a new commandline switch:
```
$ zerotier-cli status 'another nodeID'
200 listpeers e3b0e3e4ee 1.2.12 DIRECT 147.75.38.119/9993
```
```

$ zerotier-cli status 'another nodeID'
200 listpeers e3b0e3e4ee 1.2.12 RELAY   147.75.38.119/9993
```

**Comment by laduke** [comment] 2019-08-06 18:17
Not exactly what you were suggesting but, try `zerotier-cli peers` in version 1.4

**Comment by adamierymenko** [comment] 2019-08-14 20:08
Marking as dupe of #526

**Closed by adamierymenko** 2019-08-14 20:08 UTC
Labels: usability
