### ISSUE TITLE
Moon Issue between versions

### ISSUE THREAD

**Issue by d0wnblog** [zerotier/ZeroTierOne#774] opened 2018-05-31 20:55 UTC
Hey,
I saw some trouble between 1.2.8 and 1.2.10 and the moon feature.
I started a moon with version 1.2.8 and saw an issue which said I need to upgrade to 1.2.10. I updated to the latest version and added some more moons to the moon.json but after that none of the moons are shown up on the zerotier-cli listpeers as moons... Each moon was with the role "LEAF" in my list. I tested arroud and created a new orbit with version 1.2.8 and updated to 1.2.10. This works but if I try to change and resign my moon.json it will break the whole thing.

**Comment by glimberg** [comment] 2018-05-31 20:58
Could you please list the specific steps to reproduce this issue?

**Comment by d0wnblog** [comment] 2018-05-31 21:18
Sure :)

zerotier-idtool initmoon <identity.public of one root> >>moon.json

With version 1.2.8:
add some lines to moon.json

zerotier-idtool genmoon moon.json

mv 000000deadbeef00.moon moons.d/000000deadbeef00.moon

add client to this orbit

Update to version 1.2.10 so that the moon will work and shown up at zerotier-cli listpeers

Make some changes to your moon.json

zerotier-idtool genmoon moon.json

mv 000000deadbeef00.moon moons.d/000000deadbeef00.moon

systemctl restart zerotier-one.service

And from now if you restart a clients zerotier you will see only a "LEAF" instead of "MOON".

**Comment by adamierymenko** [comment] 2018-07-20 23:03
I believe this is fixed. We're going to push 1.2.12 soon. After we do that please let us know if this is still a problem. Try the `dev` branch if you want to test beforehand.

**Comment by hhhnb** [comment] 2019-02-17 13:43
> Hello,
> 
> I'm having the same issue, with the exception that my laptop is displaying "MOON" correctly, but when I try to do the same on a client RPi it doesn't work. I don't know if it was someone else case but the reason I run different versions of ZT is simply because of the versions availability for different OS'es. But the thing is I would have thought the newer version would be compatible with files generated by older version, not the other way around... and it is working for the mac client (even though I had to manually add the files + use the orbit command after), but I can't get the linux client to recognise the moons. Tried with and without leading zeros for the network, no change
> 
> To explain my setup a little :
> **Moons**:
> Root 1: Synology DSM 6.2 **ZT 1.2.8r0** _(on which I generated the .moon config file)_
> Root 2: RaspberryPi 3B+ Raspian Linux 4.14.79-v7+ **ZT 1.2.12**
> 
> **Clients**:
> Client 1: macOS 10.14.1 **ZT 1.2.12**
> Client 2: RaspberryPi 3B+ Raspian Linux 4.14.79-v7+ **ZT 1.2.12**
> 
> Edit: I also tried generating the .moon file on the root 2 (Raspberry with ZT 1.2.12) with same issue, mac client OK but RPi client only sees LEAF where it should be MOON
> 
> Edit 2: I picked a VPS now to try with a public static IP, clean machine. Debian Jessie, ZT version 1.2.12 and trying to make it a moon for the 2 clients just make the same result : mac client seen it as a MOON, the raspberry as a LEAF. I'll have a try on windows perhaps.
> _Thing I noticed, when I compare the too answers to the listpeers command is that the moon is listed with /9993 port on the mac, but with a random /27811 port on the RPi_

stableEndpoints”: [ ]  How to set it up? Domain name format is not supported

**Comment by adamierymenko** [comment] 2019-06-11 18:08
Closing since moons are going to die.

**Closed by adamierymenko** 2019-06-11 18:08 UTC

**Comment by li2xi** [comment] 2019-07-01 13:39
@adamierymenko  Is moon going to be deprecated in the future? Are there any alternative solution for the area that can't get access to zerotier root server?
