### ISSUE TITLE
Can't see SMB Shares

### ISSUE THREAD

**Issue by ShikuTeshi** [zerotier/ZeroTierOne#1365] opened 2021-03-09 02:05 UTC
I was originally using ZeroTier 1.6.2 to do a SMB share with a friend. Starting off there were no problems whatsoever. Then one day he just couldn't see my PC in the network but I could still see his. 

However when we list the networks ZeroTier reports on both ends that we can see one another. So maybe it was a Windows thing just not actually opening the share? But I could still connect to my own share from a device on the local network. So we're thinking it's just not getting communicated through ZeroTier anymore.

After searching around I came across a report of 1.6.2 going into a 'coma' which I'm not entirely sure if that was our problem or not. But nonetheless we updated to 1.6.4 without any success.

**Desktop:**
 - OS: Windows 10
 - OS/Distribution Version: 1909 & 20H2
 - ZeroTier Version: 1.6.2 & 1.6.4

**Comment by MrNope21** [comment] 2021-03-20 16:41
Same issue here. I used ZeroTier as personal cloud across multiple systems, but sometime between february and march, the SMB and FTP stopped working. There was no change at my side, settings, versions and HW are same as before.

**Comment by MrNope21** [comment] 2021-03-21 00:26
Sorry guys, seems like Windows related issue for me. Meanwhile I was a bit poking around windows SMB settings and it magically started working again. Not sure about the cause of this. Kinda weird for me is the fact that SMB was working on physical local network all the time, but didn't work on the virtual local network (ZeroTier). Multiple turn on/off SMB, restarting some services, rebooting the "server" and it is ok again. If I get some actually useful info in the future, I will add it there.

**Comment by joseph-henry** [comment] 2021-05-04 16:43
Thanks, closing for now but feel free to re-open.

**Closed by joseph-henry** 2021-05-04 16:43 UTC
