### ISSUE TITLE
Kernel error handling kext request - (os/kern) failure.

### ISSUE THREAD

**Issue by Fusion** [zerotier/ZeroTierOne#429] opened 2016-12-28 21:58 UTC
Sadly, the client is not working for me on OS X Sierra. I believe it's because it's not able to start the tap driver. Here is the tail output of `sudo kextutil -v 6 /Library/Application\ Support/ZeroTier/One/tap.kext`. Note the 'os/kern' failure.

```
Requesting start of /Library/Application Support/ZeroTier/One/tap.kext.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Start' request from user space.
(kernel) Kext com.zerotier.tap calling module start function.
(kernel) Kext com.zerotier.tap did not start (return code 0x5).
Kernel error handling kext request - (os/kern) failure.
Failed to start /Library/Application Support/ZeroTier/One/tap.kext - (os/kern) failure.
/Library/Application Support/ZeroTier/One/tap.kext failed to start - (os/kern) failure.
Reading load info for 1 kext.
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
"com.zerotier.tap" = {
    "OSBundleWiredSize" = 28672
    "CFBundleIdentifier" = "com.zerotier.tap"
    "OSBundleStarted" = false
    "OSBundleLoadTag" = 180
    "OSBundleCPUType" = 16777223
    "OSBundleUUID" = <8ba59c0a b3a73418 bff5b491 4ce7734a>
    "OSKernelResource" = false
    "CFBundleVersion" = "1.0"
    "OSBundleLoadAddress" = -551851294720
    "OSBundleDependencies" = (
        1
        5
        7
        4
    )
    "OSBundlePath" = "/Library/Application Support/ZeroTier/One/tap.kext"
    "OSBundleRetainCount" = 0
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = false
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 28672
}
}

/Library/Application Support/ZeroTier/One/tap.kext (version 1.0, UUID 8BA59C0A-B3A7-3418-BFF5-B4914CE7734A) is loaded.
setting load address of /Library/Application Support/ZeroTier/One/tap.kext to 0xffffff7f83198000
Requesting unload of /Library/Application Support/ZeroTier/One/tap.kext (with termnation of IOServices).
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Unload' request from user space.
(kernel) Kext com.zerotier.tap unloading.
(kernel) Kext com.zerotier.tap unwiring and unmapping linked executable.
(kernel) Kext com.zerotier.tap unloaded.
(kernel) Kext com.zerotier.tap removing all personalities naming it from the IOCatalogue.
Successfully unloaded /Library/Application Support/ZeroTier/One/tap.kext.
Unloading kext /Library/Application Support/ZeroTier/One/tap.kext after failing to start/send personalities.
/Library/Application Support/ZeroTier/One/tap.kext unloaded.
```

**Comment by adamierymenko** [comment] 2017-03-06 23:32
We run on many Macs and have never encountered this problem. Is it still happening for you?

**Comment by adamierymenko** [comment] 2017-03-15 15:05
We tested 1.2.0 (same kext) on 10.7, 10.8, and 10.12, and could not reproduce so I'm closing this. Likely some kind of problem with the machine.

**Closed by adamierymenko** 2017-03-15 15:05 UTC
Labels: cantreproduce
