### ISSUE TITLE
Moon: Cannot ping ZT addresses while the moon is accessible and listed

### ISSUE THREAD

**Issue by AlexisTM** [zerotier/ZeroTierOne#872] opened 2018-10-31 15:53 UTC
Hello, I have a moon connected to a Private LTE setup 
- All hosts have v1.2.12
- I can ping & ssh bidirectionally with the static IPs.
- The moon IP is detected by zerotier-cli listmoons `200 listpeers c05e3f2717 192.168.0.55/9993;2356;2311 53 1.2.12 MOON`

Yet, **no connection between hosts** is available, I cannot ping any of the Zerotier IPs (172.28.1.x)
I cannot even ping the MOON zerotier IP.

**Comment by laduke** [comment] 2018-11-05 19:36
From above, it looks like zerotier is working. There is an ip address for the moon, so zerotier knows a direct path. 

Maybe a firewall is blocking ICMP, or the members aren't authorized on the network.

**Comment by AlexisTM** [comment] 2018-11-05 20:40
It has for sure a direct link and all the ports are available on the moon side.

**Comment by laduke** [comment] 2018-11-06 17:31
Forgot to mention 
> We recommend that root servers do not act as network controllers, join networks, or perform any other overlapping functions.

Not sure if that's the cause of the issue though

**Comment by AlexisTM** [comment] 2018-11-06 17:53
I might have wrongly done something: 

The moon is connected to the network I have and has the exact configuration as the other systems but has a static IP

**Comment by adamierymenko** [comment] 2018-11-28 16:50
Marking as duplicate of #882 -- fix in the form of redesign is coming soon.

**Closed by adamierymenko** 2018-11-28 16:50 UTC
