### ISSUE TITLE
node A can access B and C, but B and C can't access each other

### ISSUE THREAD

**Issue by kylemcdonald** [zerotier/ZeroTierOne#612] opened 2017-11-06 09:39 UTC
I have a network with a few devices:

- A 10.241.161.0
- B 10.241.106.104
- C 10.241.81.250

In this case, A and B are remote servers and C is my laptop. 

- ping from server A to server B or vice versa: 30ms
- ping from server A to laptop C or vice versa: 300ms
- ping from laptop C to server B: Request timeout
- ping from server B to laptop C: Destination Host Unreachable

I'm on a bad wifi connection, but everything was working earlier so I'm not sure what's going on. How can I debug this?

For comparison, laptop C can access server B via TeamViewer.

I tried restarting laptop C and server B and it didn't seem to fix anything at first, but after a few minutes it started working again. I'm not sure whether it's connected to the restart or not.

Update: it went down again after a few hours. For comparison, here is what it looks like pinging from C to A:

```
...
64 bytes from 10.241.161.0: icmp_seq=73 ttl=64 time=208.195 ms
64 bytes from 10.241.161.0: icmp_seq=74 ttl=64 time=207.058 ms
64 bytes from 10.241.161.0: icmp_seq=75 ttl=64 time=206.291 ms
64 bytes from 10.241.161.0: icmp_seq=76 ttl=64 time=206.552 ms
64 bytes from 10.241.161.0: icmp_seq=77 ttl=64 time=240.747 ms
^C
--- A.local ping statistics ---
79 packets transmitted, 78 packets received, 1.3% packet loss
round-trip min/avg/max/stddev = 204.466/274.949/512.720/95.914 ms
```

Here's what it looks like pinging from C to B (mainly timeouts, with a few exceptions):

```
...
Request timeout for icmp_seq 16
64 bytes from 10.241.106.104: icmp_seq=15 ttl=64 time=2062.622 ms
64 bytes from 10.241.106.104: icmp_seq=16 ttl=64 time=1059.912 ms
64 bytes from 10.241.106.104: icmp_seq=17 ttl=64 time=238.308 ms
64 bytes from 10.241.106.104: icmp_seq=18 ttl=64 time=249.326 ms
64 bytes from 10.241.106.104: icmp_seq=19 ttl=64 time=265.093 ms
Request timeout for icmp_seq 22
...
Request timeout for icmp_seq 34
64 bytes from 10.241.106.104: icmp_seq=35 ttl=64 time=235.507 ms
Request timeout for icmp_seq 36
...
Request timeout for icmp_seq 57
^C
--- B.local ping statistics ---
59 packets transmitted, 6 packets received, 89.8% packet loss
round-trip min/avg/max/stddev = 235.507/685.128/2062.622/683.875 ms
```

**Comment by StrikerTwo** [comment] 2017-11-06 11:23
I'm having sporadic issues like that as well. They resolve themselves without me doing anything, but often it's bad enough that my RDP sessions time out.

All devices show as "online" in my.zerotier.com when this happens. A can ping B and C, C can ping A, B and C won't talk to each other. It looks like ZeroTier also drops the ZT LAN route when this happens, because traceroutes from B to C at that time go to my ISPs router (and straight back to B because there is a static route set in the router).

In my case A is a Windows 10 laptop at work, B is a Windows Server 2012 box at home, C is a OPNsense VM in a datacenter.

**Comment by adamierymenko** [comment] 2017-11-17 22:05
Dupe of #619

**Closed by adamierymenko** 2017-11-17 22:05 UTC

**Comment by kylemcdonald** [comment] 2018-01-03 05:44
in case anyone else runs into this: i found one temporary solution, which is to disable and re-enable the zerotier network on my laptop (from the zerotier GUI in the menu bar). at least, it worked this time.

**Comment by StrikerTwo** [comment] 2018-01-03 10:36
That's... not really a solution.

Any ETA on 1.2.6?

**Comment by kylemcdonald** [comment] 2020-02-18 16:45
I'm having this issue again. Currently running version 1.4.6 on all three machines. Something I'm noticing this time is that machine C (my laptop) has an IPv6 physical IP while both A and B are IPv4 physical IPs.

**Comment by estsauver** [comment] 2020-04-01 06:34
I'm having this issue as well. Zerotier support has basically said they can't/won't help even after we upgraded to the paid version.

**Comment by igiann** [comment] 2021-05-26 11:14
I have the same issue. I can ping from A to B, but i can not ping from B to A. This is very strange

**Comment by Mrproex** [comment] 2022-12-17 16:08
Any news on this ? Im having the same problem, no firewall enabled.
