### ISSUE TITLE
zerotier-1.2.8 on iOS 9 immediately drops connection

### ISSUE THREAD

**Issue by json00000** [zerotier/ZeroTierOne#745] opened 2018-05-13 16:14 UTC
Although I had ZeroTier working on iOS about a year ago, all recent attempts to connect to any ZeroTier network result in the VPN connection being dropped within a second of attempting to establish. After adding the network, I touch the "enable" button (it's not really a button, but more of a toggle) within the ZeroTier application, and for a second it flips "on" but then it quickly flips back to "off".

I do the same thing within Settings -> VPN (thinking that I could work around the issue by "launching" the VPN from Settings). I toggle the VPN, and for about a second it momentarily turns on. But then immediately it turns itself off.

There is no warning or error message within the iOS ZeroTier application. However, the only information I was able to find is dmesg output from the iOS device: "SIOCPROTODETACH_IN6: utun0 error=6". I can confirm that the identity.public (and secret) files exist, but my ZeroTier central shows no indication that this device ever attempted to connect. I also tried manually prepopulating an "approval" of that identity.public value in case it was an issue with the client being denied. But that didn't have an effect. I also completely deleted the ZeroTier application, confirmed that the previous identity.public was no longer there, and reinstalled from scratch. Still, I get the exact same result. The same device had been working fine before.

One issue here is that I have no idea how to debug this further. I don't know of a system log where I might expect to find details of the error. It would also be helpful if the ZeroTier application gave some indication about what went wrong. In any case when the state changes from enabled (at my request) to deactivated (due to some error condition), I'd want to know why.

**Comment by glimberg** [comment] 2018-05-14 00:25
Duplicate of #742 and already fixed.  New build rolled out on Friday evening

**Closed by glimberg** 2018-05-14 00:25 UTC
Labels: duplicate

**Comment by bsapwindows** [comment] 2018-06-12 19:05
Hi @glimberg , my device is still not connecting. Reinstall the app fixed the issue for a while (I can see the VPN icon sticks at the top), but once I re-auth the device in ZT Central, the connection drops again, and can't connect anymore. (flips back to "off" in seconds)

Another thing is, even I installed the latest version of ZT, but in ZT Central it shows the newly joined device is using v1.2.8, is this relevant to the problem? Is iOS 9.3.2 too old for ZT? How do I get back to 1.2.5?

**Comment by cabsandy** [comment] 2018-07-26 11:42
Bumping this up-on a iPhone5SE. Does the manual setting of DNS servers work for people?-no matter what I try, I cannot use the phone as a default route to my Digital Ocean server.MacBook and Android phone from same wifi AP work great-only one that doesn't is the 5SE. Thanks!

**Comment by RoelWKramer** [comment] 2019-10-01 12:00
The fix is indeed not working, i discovered that when i create a new network it works fine, but using an old (and migrated) network, it does not. The ios vpn stops after a while (no vpn icon displayed).
@glimberg if you want more test data, let me know. This is my network config:

```
#
# This rule set was generated automatically from the list of allowed ethernet protocols
# for your network on an old version of ZeroTier Central. You are free to edit it and
# add more advanced rules, capabilities, and tags, but keep in mind that versions of
# ZeroTier prior to 1.2.0 do NOT implement the rules engine.
#
# Since both senders and receivers enforce rules, you will get the following
# behavior in a network with both old and new versions:
#
# (old: 1.1.14 and older, new: 1.2.0 and newer)
#
# old <--> old: No rules are honored.
# old <--> new: Rules work but are only enforced by new side. Tags will NOT work, and
#               capabilities will only work if assigned to the new side.
# new <--> new: Full rules engine support including tags and capabilities.
#
# We recommend upgrading all your devices to 1.2.0 as soon as convenient. Version
# 1.2.0 also includes a significantly improved software update mechanism that is
# turned on by default on Mac and Windows. (Linux and mobile are typically kept up
# to date using package/app management.)
#

# All ethernet protocols were allowed in your previous configuration.
# Uncomment this example to hard-drop all but IPv4/ARP and IPv6.
#drop
#	not ethertype ipv4
#	not ethertype arp
#	not ethertype ipv6
#;

accept;

```

it does work on macos however.
