### ISSUE TITLE
DesktopUI-1.8.4  compile fail: DesktopUI-1.8.4\vendor\windows_x86_64_msvc\lib/windows.lib

### ISSUE THREAD

**Issue by soarway** [zerotier/ZeroTierOne#1588] opened 2022-03-14 00:27 UTC
PS D:\NewDev\DesktopUI-1.8.4> make
make -C tray clean
make[1]: Entering directory 'D:/NewDev/DesktopUI-1.8.4/tray'
del /q *.o *.a example *.exe *.lib
make[1]: Leaving directory 'D:/NewDev/DesktopUI-1.8.4/tray'
make -C tray zt_lib
make[1]: Entering directory 'D:/NewDev/DesktopUI-1.8.4/tray'
gcc -O -DTRAY_WINAPI=1 -std=c99 -m64 -fno-exceptions -c -o zt_desktop_tray.o zt_desktop_tray.c
ar rcs zt_desktop_tray.lib zt_desktop_tray.o
make[1]: Leaving directory 'D:/NewDev/DesktopUI-1.8.4/tray'
cargo build --release --target=x86_64-pc-windows-msvc
error: failed to calculate checksum of: D:\NewDev\DesktopUI-1.8.4\vendor\windows_x86_64_msvc\lib/windows.lib

Caused by:
failed to open file D:\NewDev\DesktopUI-1.8.4\vendor\windows_x86_64_msvc\lib/windows.lib

Can this problem be solved help me?
Thank you!

**Comment by glimberg** [comment] 2022-03-14 15:33
Duplicate of https://github.com/zerotier/DesktopUI/issues/31

**Closed by glimberg** 2022-03-14 15:33 UTC
