### ISSUE TITLE
High CPU usage on Windows 64 bit with Hyper-V enabled

### ISSUE THREAD

**Issue by lewisl9029** [zerotier/ZeroTierOne#308] opened 2016-02-21 20:37 UTC
Not sure if related to https://github.com/zerotier/ZeroTierOne/issues/277, but on my desktop, installing ZeroTier One caused the system process (not ZeroTier itself) to use 30%~ CPU constantly and slowed things to a crawl. Uninstalling ZeroTier One resolves this. Strangely enough, on my laptop this doesn't happen. 

The main difference between the two machines is I have Hyper-V enabled on my desktop but not my laptop. Maybe try reproducing with Hyper-V and a few Virtual Switches set up? Seems like that might have a chance to conflict with ZeroTier's networking stack.

Let me know if you need any more information.

**Comment by janjaapbos** [comment] 2016-02-21 21:37
Did the CPU increase happen directly after installing ZeroTier, without actually defining networks in ZeroTier?

If you did define networks in ZeroTier, perhaps you can give some background info on how these networks were configured and used on the machine. Did you for instance configure bridging with HyperV networks?

**Comment by lewisl9029** [comment] 2016-02-21 21:51
Yes I did define networks in ZeroTier. It consists of 3 machines, the aforementioned desktop and laptop, and a remote server that I occasionally boot up for backup purposes. The settings for my network are below:

![screenshot](https://cloud.githubusercontent.com/assets/6934200/13205651/98860fde-d8a1-11e5-97ba-47c953340987.png)

As you can see, I didn't configure any bridging.

**Comment by janjaapbos** [comment] 2016-02-21 21:56
What happens if you leave the zerotier network from your hyperv host?

**Comment by janjaapbos** [comment] 2016-02-21 22:02
Can you also check what happens when only your hyperv host has joined and
the others have left the ZeroTier network, so the hyperv host is the single
member of that ZeroTier network.

**Comment by lewisl9029** [comment] 2016-02-21 22:38
Did a bit more troubleshooting and here's what I've found:

Leaving the network as you suggested didn't immediately reduce the CPU usage, but things went back to normal after a restart.

I then tried creating a new network with default settings and joining it. Everything was fine at this point. However, as soon as I chose a ZeroTier managed IPv4 block (I chose the first one, 10.147.17.*), the CPU usage rose again. No other computers have joined the network.

Hopefully that helps. Let me know if there's anything else you'd like me to try.

**Comment by adamierymenko** [comment] 2016-02-26 19:29
Seems like there might indeed be a conflict here -- wonder if #277 is a dupe of this. Will have to get HyperV on a Windows box for testing.

**Comment by adamierymenko** [comment] 2016-03-03 03:14
[ZeroTier One [1.1.5 prerelease].zip](https://github.com/zerotier/ZeroTierOne/files/156108/ZeroTier.One.1.1.5.prerelease.zip)

Here is a prerelease build of 1.1.5 that contains a few fixes. I can't reproduce this yet but I went through WindowsEthernetTap and tried to tie down some things that looked suspicious.

**Comment by adamierymenko** [comment] 2016-04-01 21:27
See also #277 -- likely duplicate of same issue.

This may be related to route/IP management.

**Comment by adamierymenko** [comment] 2016-11-29 19:41
Closing since #357 is almost certainly the same thing.

**Closed by adamierymenko** 2016-11-29 19:41 UTC
Labels: bug, cantreproduce
