### ISSUE TITLE
cpu pegged at 100% (reopening older issue)

### ISSUE THREAD

**Issue by jwh** [zerotier/ZeroTierOne#1079] opened 2019-11-08 01:55 UTC
(old bug wasn't reproducible apparently)

So for a while this has been an issue - when trying to push even moderate amounts of traffic the cpu on KVM gets pegged at 100% and it stalls entirely - initially this looked like a VM specific issue as it doesn't occur on baremetal, however it looks like its only unusable on a single core VM (although still a bit sketchy on multi core)

Is it possibly something like thread contention given the multithreading?

Still happens on 1.4.6, Linux (multiple distros)

**Comment by joewholden** [comment] 2019-11-08 22:52
Having a look further, it does indeed appear that 2 threads are fighting for the same cpu time - likely scheduled on different cores in a multicore VM, they aren't named though so it's not clear what they're for

**Comment by joewholden** [comment] 2020-01-04 04:24
Nothing?  If it's not usable on a 3ghz Xeon core how is it supposed to be useful on embedded devices?

**Comment by 66CCFF** [comment] 2020-03-31 16:45
Same Issue here for zerotier-one 1.4.6 running in single core Linux vm.
It seems that when sending and receiving bursts of heavy traffic, zerotier-one becomes less efficient and stuttered. Restricting the maximum traffic on the port to, for example, 100Mbps can also alleviate this problem.

**Comment by jan-z** [comment] 2020-04-19 12:10
I can confirm there is a performance problem using 1.4.6 on a single core VM on DigitalOcean.

iperf3 between both DigitalOcean droplets for comparison of network performance over public interface:

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.97 GBytes  1.69 Gbits/sec  427             sender
[  5]   0.00-10.02  sec  1.97 GBytes  1.69 Gbits/sec                  receiver
```


iperf3 over ZT on DigitalOcean **1vCPU** (sender):

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  8.06 MBytes  6.76 Mbits/sec    1             sender
[  5]   0.00-10.37  sec  5.75 MBytes  4.66 Mbits/sec                  receiver
```

CPU usage is shown as 100% for the zerotier-one process in `top` on the sender side.



iperf3 over ZT on DigitalOcean **2vCPU** (sender):

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   378 MBytes   317 Mbits/sec  131             sender
[  5]   0.00-10.01  sec   376 MBytes   315 Mbits/sec                  receiver
```

The second test shows 50-70% CPU usage for the zerotier-one process.

I verified that tcpFallbackActive is false on both nodes.

The iperf server (receiver) had 1 vCPU in both tests.

@adamierymenko I'm willing to pay to get the 1vCPU performance fixed. Should I get a subscription?

**Comment by joewholden** [comment] 2020-04-26 23:44
> Same Issue here for zerotier-one 1.4.6 running in single core Linux vm.
> It seems that when sending and receiving bursts of heavy traffic, zerotier-one becomes less efficient and stuttered. Restricting the maximum traffic on the port to, for example, 100Mbps can also alleviate this problem.

Traffic load does not matter so much in my case, it can happen with 100kbps or 1gbps, it seems to be timing more than anything

**Comment by lflare** [comment] 2020-06-16 17:01
I can confirm this issue appears to be apparent in my single-core VMs too. Issue went away with more than 1 core.

**Comment by jwh** [comment] 2020-12-21 22:20
Now on 1.6.2 and this is *still* an issue, one machine is on its knees at ~400kbps.

**Comment by jwh** [comment] 2020-12-30 23:38
Closing this as there is obviously no interest in fixing it and there are other issues like exponential memory usage growth with routing table churn, vpncloud offers a standalone alternative without these issues so we're switching to that anyway.

**Comment by jwh** [comment] 2021-01-01 22:14
@glimberg 
If you're going to reopen my issue then at least bother to comment on it.

**Comment by lflare** [comment] 2021-01-02 06:59
Considering this is still a bug, I'm not too sure why you would close the issue. Even if it does not affect you anymore, it is still a present bug in 1.6.2, and something the developers should have an open issue for so they can keep track of it.

**Comment by jwh** [comment] 2021-01-02 13:15
Like many other bugs, zero activity == zero interest in fixing it, it's been over a year without a single comment or even acknowlegement especially as my previous issue was dismissed as a non-issue.

**Comment by joseph-henry** [comment] 2021-05-12 18:30
I apologize that there hasn't been any official communication on this issue yet but the reality is that the issues mentioned here are likely a constellation of issues that seem similar but are unrelated and it is such a rare occurrence it is nearly impossible for us to replicate it. Can you tell me the exact CPU arch, kernel version, and list any other network-adjacent software you have running?

Additionally, there's a chance that `1.6.5` could fix this. I would give that a try and let us know if it doesn't fix the issue.

**Closed** 2021-06-08 18:18 UTC
Labels: Linux, bug

**Comment by jwh** [comment] 2021-09-05 18:53
Reproduction is very easy, as per multiple comments on this issue, it's still present (and actually, worse, as lack of connectivity is now manifesting without high CPU as well, which may be a new problem since upgrading to 1.6.x), I no longer use zerotier though because it's unusable.

**Comment by klardotsh** [comment] 2021-09-20 22:41
1.6.5, at least on Alpine, does not seem to have fixed this - sending even tiny messages across the ZT interface on my single core Linode pegs the CPU to 100%, suffocating the service actually trying to send/recv said message.

**Comment by laduke** [comment] 2021-09-22 16:18
It can definitely fall over on tiny VPS's during high bandwidth. 
Haven't seen it with tiny messages, but haven't tried on alpine. 
You can try to limit bandwidth with some qos/traffic control for a workaround.
