### ISSUE TITLE
Member "push route" option

### ISSUE THREAD

**Issue by jdrews** [zerotier/ZeroTierOne#323] opened 2016-04-29 04:16 UTC
Looking for a way to assign routes that would get set on a member. Once the member connects up to the ZeroTier network, the ZeroTier-One client software will set external routes. 

Example:

> ZeroTier network IPv4 10.1.1.0/24
> 
> Member 0000001 10.1.1.1 office-router
> 
> Member 0000023 10.1.1.23 road-warrior23
> push-route 172.25.3.0/24 10.1.1.1
> push-route 192.168.62.0/24 10.1.1.1

Where 10.1.1.1 is a ZeroTier member with access into 172.25.3.0/24 and 192.168.62.0/24 and capable of routing 10.1.1.0/24 traffic into said networks. 

I would hope this could be set from the ZeroOne Central page. If there's a cleaner way to do this I'm all ears. 

See OpenVPN documentation here on "push-route" capabilities. We use this extensively in our network.
https://openvpn.net/index.php/open-source/documentation/howto.html#scope

**Comment by jdrews** [comment] 2016-04-29 04:17
Slightly related to #178 except I'm not looking for a "default" route to be set on the member. Instead I'm looking for specific routes to be added.

**Comment by adamierymenko** [comment] 2016-05-06 17:00
I'm closing as a duplicate of #178, but since #178 is in progress I'm going to make sure to allow routes that are more than just default. You will want to be able to route to e.g. remote subnets.

So thanks for posting! Helps in dev.

**Closed by adamierymenko** 2016-05-06 17:00 UTC
