### ISSUE TITLE
Cannot install 1.1.14 on elementaryOS Freya (Ubuntu 14.04 LTS-based)

### ISSUE THREAD

**Issue by bonki** [zerotier/ZeroTierOne#400] opened 2016-10-10 07:12 UTC
I currently have `1.1.4` installed which was installed pre-quick-installer. I have now installed the new repo via the quick installer but the new version it's trying to pull in (`1.1.14`) has unmet dependencies:

```
# aptitude install -V zerotier-one
The following NEW packages will be installed:
  liblz4-1{a} [0.0~r114-2ubuntu1]  libnatpmp1{a} [20110808-3ubuntu2]  
The following packages will be upgraded:
  zerotier-one{b} [1.1.4 -> 1.1.14]  
1 packages upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 277 kB of archives. After unpacking 66,6 kB will be freed.
The following packages have unmet dependencies:
 zerotier-one : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is installed.
                Depends: init-system-helpers (>= 1.18~) but 1.14 is installed.
The following actions will resolve these dependencies:

     Remove the following packages:
1)     zerotier-one                

Accept this solution? [Y/n/q/?]
```

```
# lsb_release -a -u
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:   trusty
```

```
# cat /etc/apt/sources.list.d/zerotier.list 
deb http://download.zerotier.com/debian/jessie jessie main
```

The current version of `init-system-helpers` in trusty _is_ `1.14`, see http://packages.ubuntu.com/trusty/init-system-helpers.

Is Ubuntu 14.04 no longer supported?

**Comment by keesbos** [comment] 2016-10-10 15:41
Did you try the trusty source in /etc/apt/sources.list.d/zerotier.list ?
deb http://download.zerotier.com/debian/trusty trusty main

**Comment by jonathonf** [comment] 2016-11-22 21:00
I'd suggest this is invalid.

From the [trusty deb](http://download.zerotier.com/debian/trusty/pool/main/z/zerotier-one/zerotier-one_1.1.14_amd64.deb)'s control file:

```
Depends: libc6 (>= 2.15), libgcc1 (>= 1:4.1.1), liblz4-1 (>= 0.0~r113), libnatpmp1 (>= 20101211), libstdc++6 (>= 4.6), init-system-helpers (>= 1.13~), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), iproute2
```

All the deps are valid for trusty.

**Comment by bonki** [comment] 2016-11-23 14:09
Yes and no, the OS detection does not cover this case which is why it incorrectly installs the `jessie` instead of the `trusty` repository. `trusty` works once installed manually, but the install script does not do the right thing(tm).

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: elementary OS
    Description:    elementary OS Freya
    Release:        0.3.2
    Codename:       freya

    $ lsb_release -a -u
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04 LTS
    Release:        14.04
    Codename:       trusty

    $ cat /etc/debian_version 
    jessie/sid

The install script only check `lsb_release -a` (without the upstream flag, which I assume doesn't exist on vanilla Debian/Ubuntu) and falls back to checking `/etc/debian_version` which, for some reason I don't know, doesn't contain the correct version.

Ideally we should check if `lsb_release` supports `-u` and also run this, which should cover other Ubuntu-based distributions as well.

**Comment by jonathonf** [comment] 2016-11-29 18:44
In which case this is a dupe of #379 ? (or 379 is a dupe of this)

**Closed** 2017-04-21 21:00 UTC
Labels: build problem, compatibility
