### ISSUE TITLE
device is online，but cannot show the Physical IP，and cannot connect to the other device

### ISSUE THREAD

**Issue by angussleeping** [zerotier/ZeroTierOne#1777] opened 2022-11-10 05:51 UTC
This morning I get connect with my nas as usual,but I cannot connect to my nas , then I check  my zerotier connect on the website,I found that my computer is online but the Physical IP cannot shows in the website , then I check my route list and ipconfig , they are as usual.
How can I fix my connect?
<img width="945" alt="zerotier" src="https://user-images.githubusercontent.com/34022591/201011208-8b7b919d-faec-4512-9378-5835698e8879.png">
<img width="409" alt="ipconfig" src="https://user-images.githubusercontent.com/34022591/201011218-5bac5b1c-6dbe-46e3-9c5c-e84bfac7e01b.png">
<img width="477" alt="route" src="https://user-images.githubusercontent.com/34022591/201011221-7502abbb-6e60-41c7-be15-8f72a0a9800d.png">

**Comment by crazyshitass** [comment] 2022-12-04 14:32
Same here. Need a fix release.

**Comment by joseph-henry** [comment] 2022-12-05 21:43
This is a duplicate of #1780. Please see the advice there. If that doesn't help, please let us know what you tried and we can consider re-opening one of these tickets.

**Closed by joseph-henry** 2022-12-05 21:43 UTC
