### ISSUE TITLE
Dropped packets on Windows PCs

### ISSUE THREAD

**Issue by iball** [zerotier/ZeroTierOne#1895] opened 2023-03-09 03:05 UTC
Prior to 1.10.4 when both my Win 10 Enterprise and Windows 11 Pro PCs were on 1.10.3 there were no issues pinging to those Windows machines from all my different services (Ubuntu VPS, Proxmox containers, virtual machines, etc.).  
  
Upgraded everything to 1.10.4 and was immediately hit with occasional dropped packets but *only* to those Windows machines - the only Windows machines I have on my zerotier network.  Nothing else was installed on those Windows machines since installing 1.10.4.  
  
Uninstalled 1.10.4 and re-installed 1.10.3 and that dropped packet issue went away.

Is anyone else also seeing this behavior?  Until 1.10.4 everything was fine on those Windows machines with ZeroTier for over a year.

**Comment by tinola** [comment] 2023-03-09 10:45
Well, yes. I can confirm dropping packets. Sometimes I have to ping other machine from Windows (it doesn't matter it is *nix or Windows target) to get connection back.

**Comment by tinola** [comment] 2023-03-09 17:40
IMO ping it's half the problem, dropping connection from Windows to any other platform is the key. To recover connection I have had to ping sometimes pore than 30-40 seconds to establish p2p connection. This behavior I observed also in 1.10.3.
Now I'm testing connection stability on version 1.10.2, where it seems to work OK.

**Comment by glimberg** [comment] 2023-03-09 17:52
We're looking into the issue.

**Comment by chuckofthenorth** [comment] 2023-03-21 17:19
I think this issue is caused by #1920 
In my case my 3 Windows machines running 1.10.4 would run for 10-50 OK seconds OK and then start dropping packets (watched it using iperf3 and ping tests).  Turns out the cpu and memory were getting saturated dealing with spawning an infinite number of firewall rules as described in #1920.

**Comment by laduke** [comment] 2023-03-21 17:23
should be fixed in 1.10.5. Let use know if not!

**Closed by laduke** 2023-03-21 17:23 UTC
