### ISSUE TITLE
Internet breaks when ZT allow default, linux, fallbacktcp active

### ISSUE THREAD

**Issue by terry98** [zerotier/ZeroTierOne#1479] opened 2021-11-02 18:30 UTC
Hi, I'm using manjaro at work and I can  only connect ZT through tcp 443, and it connects..

After connected I can't ping anything in my zt network unless I set rpfilter=2 in the sysctl config, after that I can ping my server.. If I set allowdefault=true (I need this to use ZT as vpn) the internet does not work anymore, no ping to anything.

ZT does work correctly when used in windows and the same work network, this is happening in linux.

**Comment by adamierymenko** [comment] 2021-11-10 21:14
Closing as duplicate of #1482 and considering that to be an omnibus "default route override problems on Linux" ticket.

**Closed by adamierymenko** 2021-11-10 21:14 UTC
