### ISSUE TITLE
ZeroTierOne default gateway settings cause internet connection broken.

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#334] opened 2016-06-06 01:46 UTC
ZeroTierOne Windows Client will set the default gateway to zt0. It cause internet connection broken.

**Comment by jdrews** [comment] 2016-06-07 18:53
Strange. This doesn't happen on my Windows 10 client. What Windows client are you using?

**Comment by adamierymenko** [comment] 2016-06-07 19:01
ZeroTier One on Windows creates a pseudo-default-gateway with a high metric. This is done because Windows is unable to set firewall settings on an interface that does not have a default gateway, as it uses the MAC address of the default gateway to uniquely identify the network. This is a hack without which Windows can't set security policy on a network.

(Yes Windows is that awful.)

**Comment by adamierymenko** [comment] 2016-06-21 21:52
Unable to reproduce this on Windows 7 or 10 -- closing for now.

**Comment by adamierymenko** [comment] 2016-06-21 21:53
If you see this again, use the Windows 'route' command to get the current route to an Internet host like 8.8.8.8 and see what it says. Also `route print` could be helpful.

**Closed by adamierymenko** 2016-06-21 21:52 UTC

**Comment by xsrf** [comment] 2018-01-09 07:08
Hey, I have the same problem and it's not new to me. I had it with Hamachi and OpenVPN too.
It's not that the internet connection is permanently broken - at least not in my case. But every few minutes Windows routes the default traffic via the default gateway of the ZeroTier interface and then switches back, leading to spontaneous connection losses.
I already disabled automatic metric on my Wifi and my ZeroTier Adapter and assigned them manually for IPv4 and IPv6. `route print` shows these changes accordingly. Nevertheless, the issue still exists.
To solve the problem on my OpenVPN connection, where I was able to configure all my routes myself, I changed the default route from 0.0.0.0/0 to a split route (0.0.0.0/1 + 128.0.0.0/1) which, as far as I remember, convinced windows to never use it as long as a 0.0.0.0/0 route existed somewhere other.
I know this problem for years now - it also existed with Windows 7 and 8. I never fount out why and when Windows does that. It clearly is not fault of ZeroTier, but you should be aware.
I found this issue, because I was looking for a way to configure/remove the default gateway from a ZeroTier network right now...
