### ISSUE TITLE
Use uTun interface on Mac OS X if tap.kext is not installed/available

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#278] opened 2015-12-18 06:08 UTC
The bug mentioned here seems to be happening affecting Zerotier too: https://discussions.apple.com/thread/5483717?tstart=0

Solution by other projects are here: 
http://www.gossamer-threads.com/lists/vpnc/devel/4099
https://github.com/breiter/vpnc

Would also make Zerotier listed under Mac OS X System Preferences GUI for easy dhcp and manual ip configuration.

**Comment by adamierymenko** [comment] 2015-12-21 18:15
We've done some work to support utun but it's not merged and there are several issues:

1. You lose some functionality, since Bonjour will not run over utun devices nor will some other multicast-based protocols. This is apparently a hard-coded limit in the Bonjour source (we found the actual lines at opensource.apple.com) that cannot be changed or worked around.

2. Utun requires emulation of ARP and IPv6 NDP, which we know how to do but it's a bit of work and we don't want to introduce regressions in performance. We do it for Android so it's certainly do-able.

3. Utun can't be bridged, which is also a loss of functionality.

In the future we might make the OS X client use utun by default and then give users the option of installing the tuntaposx-derived zt# driver as an optional package.

**Comment by heri16** [comment] 2015-12-22 01:49
The proposed option sounds great! Wondering what is the reasoning behind apple blocking mDNS over uTun...

**Comment by adamierymenko** [comment] 2015-12-22 01:50
The comments in Apple's code say it's because this is to avoid running up people's bandwidth... which is probably outdated. Comment is rather old.

Although I suppose it depends on where you live.

**Comment by heri16** [comment] 2015-12-22 01:51
Running IPv6 on Zerotier is great, but as DNS stack on Mac OS X refuses to resolve Zerotier IPv6 addresses, that is the dealbreaker.

**Comment by adamierymenko** [comment] 2019-06-11 18:14
Closing since we now have an even more clever tap interface method on MacOS as of 1.4

**Closed by adamierymenko** 2019-06-11 18:14 UTC
Labels: backlog
