### ISSUE TITLE
One Plus 6 (Android 10) stays OFFLINE

### ISSUE THREAD

**Issue by StarkillerGDN** [zerotier/ZeroTierOne#1132] opened 2020-01-29 10:05 UTC
**Description** 
My phone can't connect to a network because it stays always in offline mode (no ID attribute).
I test every options of the app, install/uninstall, clear cache, test an old version but still same problem. My other devices (computers) are connected to my zerotier network and work fine. There is only on the Android app, I've got a problem.

**Application** 
Android, use on One Plus 6
Version : 1.4.4-1 / 1.2.12-2

Thank you for your help ! :)

**Comment by jimzhong** [comment] 2020-02-01 14:40
Sounds like a duplicate of #1112. Does it stay off-line when using mobile data?
And also https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips might be helpful.

**Comment by StarkillerGDN** [comment] 2020-02-06 07:38
Yes it stay off line in WIFI and when I'm using mobile data. I don't know why...

**Comment by joseph-henry** [comment] 2020-06-25 01:19
Are you still experiencing this issue? 

To clarify, on WIFI it works as expected but on mobile data it does not come online? What carrier do you have?

**Comment by StarkillerGDN** [comment] 2020-06-25 07:25
No it's fixed! In fact I deactivate my VPN, delete it from my phone and It was OK! So the issue can be close

**Comment by laduke** [comment] 2020-06-25 16:10
👍

**Closed by laduke** 2020-06-25 16:10 UTC
