### ISSUE TITLE
Zerotier service crash after fail to set a friendly interface name

### ISSUE THREAD

**Issue by marcussacana** [zerotier/ZeroTierOne#1883] opened 2023-03-01 20:02 UTC
Hi, I got this problem in the last day and asked for help [here](https://discuss.zerotier.com/t/zerotier-service-shutting-down/12082/), but without lucky I keep looking for the reason, and after debug a while, I noticied the crash happening in this **line 114**:
![image](https://user-images.githubusercontent.com/10576957/222245388-20e09e4b-abec-4d44-bcb1-60eb7d9f3e9f.png)
luckly this functions references a very specifc string, this one.
![image](https://user-images.githubusercontent.com/10576957/222245581-592d886c-2fe1-4ff0-8f5c-671d5e3818e5.png)
and that lead me supect of this code:
https://github.com/zerotier/ZeroTierOne/blob/dc54e0e1c4a0566deb6261291691f17d4220e08d/osdep/WindowsEthernetTap.cpp#L842-L864
I failed to understand the IDA code very well, but by the source I think the problem is here:
https://github.com/zerotier/ZeroTierOne/blob/dc54e0e1c4a0566deb6261291691f17d4220e08d/osdep/WindowsEthernetTap.cpp#L850-L853
Seems `GetProperties` fails and keep the pointer empty, and right after that the code tries to access this pointer without checks.

**Comment by glimberg** [comment] 2023-03-01 21:34
Hi, @marcussacana!

Thanks so much for digging into this.  That's a strange one that we've never seen before for sure.  It's not something I can reproduce over here, but that spot does look likely.  If that is the spot, I'm definitely curious about the root cause of the failure. 

Is there any way I can convince you to try building ZeroTier in the Debug configuration and running in the debugger to verify the location of the error?  The main Visual Studio solution file is `windows/ZeroTierOne.sln`.  The two caveats:

* You'll need the Rust compiler & ecosystem installed (https://rustup.rs) 
* Visual Studio must be run as Administrator in order to run ZeroTier in the Visual Studio debugger.

You won't need to build the driver.

**Comment by glimberg** [comment] 2023-03-01 21:35
Also, what version of Windows are you running?

**Comment by marcussacana** [comment] 2023-03-01 21:39
Windows 11 Pro 22H2.
I tried to build before debug without the symbols but maybe is the rust missing that made the build fail, I will try again.

**Comment by marcussacana** [comment] 2023-03-01 21:55
@glimberg what about this build error? I never used rust, sorry 🤔 
```
1>EXEC : error : the listed checksum of `C:\Users\Marcus\Documents\GitHub\ZeroTierOne\zeroidc\vendor\base64\tests/encode.rs` has changed:
1>expected: 072f079f0250d542ff964e8e72b7d13e2336fbee7395367ff737e140c38ac459
1>actual:   49bc043eec2402a79ecbd863be05d941a8a86296e1d5cf6331474865f4500b38
1>
1>directory sources are not intended to be edited, if modifications are required then it is recommended that `[patch]` is used with a forked copy of the source
```
notice that i'm trying to build from a clean clone of this git, not sure if I need to run any cmake script before

**Comment by glimberg** [comment] 2023-03-01 22:17
No.  No CMake required.

IIRC, that's a line ending issue.  Windows by default wants `\r\n`, but those cargo hashes are based on the line endings being `\n`.

I just pushed a change to the `.gitattributes` for the rust code that *should* fix that

**Comment by marcussacana** [comment] 2023-03-01 22:21
I will try again then.

**Comment by glimberg** [comment] 2023-03-01 22:22
First attempt broke CI.  Still working on it

**Comment by marcussacana** [comment] 2023-03-01 22:23
Fine, I will eat something and I'll be back soon then.

**Comment by glimberg** [comment] 2023-03-01 23:09
Ok.  Sorry about the delay.  It *should* be fixed now.  You may have to re-clone the repo for it to work though.

**Comment by marcussacana** [comment] 2023-03-01 23:11
fine

**Comment by marcussacana** [comment] 2023-03-01 23:15
```
1>EXEC : error : the listed checksum of `C:\Users\Marcus\Documents\GitHub\ZeroTierOne\zeroidc\vendor\base64\README.md` has changed:
1>expected: 99e61de0bafd6985761b596f9aa970dee5b4d0cfbfc05cd6565b5ffa139cb34f
1>actual:   e4818606f8a645bb24350e385755a8dc05edf4417de06b6840cca6d0014c9325
1>
1>directory sources are not intended to be edited, if modifications are required then it is recommended that `[patch]` is used with a forked copy of the source
```
I will try clone using WSL2 and build in my windows.

**Comment by glimberg** [comment] 2023-03-01 23:16
Only other suggestion I have is to set `git config --global core.autocrlf false`, but I'm trying to avoid that as it's not a good solution.  It turns off autocrlf on everything git.

**Comment by marcussacana** [comment] 2023-03-01 23:22
`git config --global core.autocrlf false` did the trick, I will try build it then.

**Comment by marcussacana** [comment] 2023-03-01 23:34
As expected is where the bug is
![image](https://user-images.githubusercontent.com/10576957/222291016-7baa34af-3641-468b-9c17-b188e2fb5315.png)
![image](https://user-images.githubusercontent.com/10576957/222291114-a3d1874e-36e9-4145-bf51-d8528e403ea9.png)

**Comment by glimberg** [comment] 2023-03-01 23:35
Great.   Thanks so much for your help on this.  I'll get a PR in and this will be taken care of in the next release

**Comment by marcussacana** [comment] 2023-03-01 23:36
:) Fine, I'll be waiting the next release then

**Closed** 2023-03-02 02:01 UTC
