### ISSUE TITLE
Memory leak under Windows 10

### ISSUE THREAD

**Issue by hldgaofeng** [zerotier/ZeroTierOne#1008] opened 2019-08-14 10:33 UTC
Memory leak under Windows 10

After startup, memory grows at about 60 KB per second until it runs out of memory

 - OS: Windows 10 64 bit
 - ZeroTier 1.4.2

**Comment by adamierymenko** [comment] 2019-08-14 14:46
We don't see this but will investigate further with a stress test on Windows 10.

**Comment by adamierymenko** [comment] 2019-08-14 15:49
Is this in the service or the Windows GUI / tray app component? We can't reproduce this and have been flood pinging the service for hours.

**Comment by glimberg** [comment] 2019-08-14 17:34
I can get memory to balloon a bit on initialization, but the memory is released once everything is up & running.  Not seeing any memory leaks in the profiler either.  Looking into why it uses so much RAM at startup (up to 500MB in my case), but there's definitely not a leak.

**Comment by adamierymenko** [comment] 2019-08-14 17:55
It looks like this is related to Windows spewing multicasts on new interfaces. We have a fix for this in `dev`.

**Comment by hldgaofeng** [comment] 2019-08-15 05:30
![image](https://user-images.githubusercontent.com/9069283/63074659-cb4b8300-bf60-11e9-99ae-917c6532354f.png)

**Comment by adamierymenko** [comment] 2019-08-23 16:45
We are oddly unable to reproduce this. :(

**Comment by adamierymenko** [comment] 2019-08-23 16:46
Leaving open for further investigation.

**Comment by nopjmp** [comment] 2019-08-26 10:43
I'm curious if they are in China and are behind the "GFW" and if it's manipulating the protocol and causing a memory leak.

**Comment by hldgaofeng** [comment] 2019-08-27 03:47
> I'm curious if they are in China and are behind the "GFW" and if it's manipulating the protocol and causing a memory leak.

Why is there no such memory leak problem under Linux operating system, which is also behind the china's "GFW"?

**Comment by adamierymenko** [comment] 2019-09-04 20:01
I believe this is fixed and was related to a build-up of outgoing multicast. We have added a sane limit.

**Closed by adamierymenko** 2019-09-04 20:01 UTC
Labels: bug, cantreproduce

**Comment by psychomelet** [comment] 2019-09-21 02:55
![Image Pasted at 2019-9-21 10-52](https://user-images.githubusercontent.com/39754068/65367027-2f4b2080-dc5e-11e9-9439-dd3a928da677.png)

The problem seem to persist with latest 1.4.6
