### ISSUE TITLE
Zero-copy networking, "super batching," etc. to avoid kernel/user context switches.

### ISSUE THREAD

**Issue by unicomp21** [zerotier/ZeroTierOne#685] opened 2018-02-15 11:45 UTC
On server side, to mitigate overhead of user/kernel context switch, which has gotten worse w/ spectre and meltdown, start using kernel-bypass techniques like DPDK to improve recv side throughput at high packet rates.  Then batch recv side packets into larger packets before relaying to zerotier clients.  This would also open the door for a "firehose" zerotier client which uses a UDP protocol to create the equivalent of a massive TCP window (spanning many ZT tcp sessions), similar to Aeron, dramatically increasing throughput for concepts such as pub/sub.

https://github.com/real-logic/aeron

**Comment by adamierymenko** [comment] 2018-03-29 17:33
Zero-copy networking is probably a 1.4 tree thing.

**Comment by adamierymenko** [comment] 2018-03-29 17:48
Marking as duplicate of #595

**Closed by adamierymenko** 2018-03-29 17:48 UTC
Labels: backlog, enhancement, performance
